"""Apply the story text in tools/story/*.json to the game data.

usage: apply_story.py [<dir with main.json, expansion.json, missions.json, regions.json,
                        things_original.json, things_generated.json, bosskits.json>]

Copies the given files into tools/story/ (default: use what is already there), then
- replaces the STORY / EXPANSION_STORY / MISSIONS / REGION_STORY objects in src/data/*.ts,
- writes src/data/landmarkText.ts (landmark examine-text and frontier lines, applied by rooms.ts),
- patches the boss battle text in tools/dib_kits.json and regenerates src/data/dibCreatures.ts.
Run it again after any generator (gen_story / gen_expansion / gen_missions / gen_regions) re-runs.
"""
import json
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STORE = os.path.join(ROOT, 'tools', 'story')
os.makedirs(STORE, exist_ok=True)
if len(sys.argv) > 1:
    for f in os.listdir(sys.argv[1]):
        if f.endswith('.json'):
            shutil.copy(os.path.join(sys.argv[1], f), os.path.join(STORE, f))
load = lambda n: json.load(open(os.path.join(STORE, n + '.json')))


def replace_payload(path, var, value):
    src = open(path).read()
    i = src.index('export const ' + var)
    j = src.index('= ', i) + 2
    _, end = json.JSONDecoder().raw_decode(src[j:])
    open(path, 'w').write(src[:j] + json.dumps(value, indent=1, ensure_ascii=False) + src[j + end:])


def current(path, var):
    src = open(path).read()
    i = src.index('export const ' + var)
    j = src.index('= ', i) + 2
    return json.JSONDecoder().raw_decode(src[j:])[0]


data = os.path.join(ROOT, 'src', 'data')
# Missions: only the words change; ids, foes, items and quest ids stay exactly as generated.
mis_now, mis = current(os.path.join(data, 'missions.ts'), 'MISSIONS'), load('missions')
for a, b in zip(mis_now['fights'], mis['fights']):
    for f in ('id', 'mission', 'room', 'foes'):
        b[f] = a[f]
mis['giver'] = mis_now['giver']
for m in mis_now['fragments']:
    mis['fragments'][m]['item'] = mis_now['fragments'][m]['item']
mis['formula']['item'] = mis_now['formula']['item']
for a, b in zip(mis_now['quests'], mis['quests']):
    b['id'] = a['id']
replace_payload(os.path.join(data, 'story.ts'), 'STORY', load('main'))
replace_payload(os.path.join(data, 'expansion.ts'), 'EXPANSION_STORY', load('expansion'))
replace_payload(os.path.join(data, 'missions.ts'), 'MISSIONS', mis)
replace_payload(os.path.join(data, 'region_frontiers1.ts'), 'REGION_STORY', load('regions'))

# Landmarks: { room: { thing id: lines } } and frontier lines in exit order.
# Frontier lines were extracted in source order of each room's 'never' exits; key them by destination.
gen_rooms = {r['id']: r for f, v in (('expansion.ts', 'EXPANSION_ROOMS'), ('missions.ts', 'MISSION_ROOMS'), ('region_frontiers1.ts', 'REGION_ROOMS')) for r in current(os.path.join(data, f), v)}
things, frontiers = {}, {}
for n in ('things_original', 'things_generated'):
    for room, v in load(n).items():
        things[room] = v.get('things', {})
        if v.get('frontier') and room in gen_rooms:
            dests = [e['to'] for e in gen_rooms[room]['exits'] if e.get('locked') == 'never']
            frontiers[room] = {to: t for to, t in zip(dests, v['frontier']) if t}
open(os.path.join(data, 'landmarkText.ts'), 'w').write(
    '// GENERATED by tools/apply_story.py from tools/story/: landmark examine-text and frontier lines.\n'
    'export const LANDMARK_TEXT: Record<string, Record<string, string[]>> = ' + json.dumps(things, indent=1, ensure_ascii=False) + ';\n'
    'export const FRONTIER_TEXT: Record<string, Record<string, string[]>> = ' + json.dumps(frontiers, indent=1, ensure_ascii=False) + ';\n')

# Boss battle text.
kp = os.path.join(ROOT, 'tools', 'dib_kits.json')
kits = json.load(open(kp))
boss = load('bosskits')
for k in kits['kits']:
    b = boss.get(k['kit']['id'])
    if not b:
        continue
    bt = k['kit']['battle']
    for f in ('check', 'intro', 'idle', 'talk', 'spare_text'):
        if f in b:
            bt[f] = b[f]
    for a, na in zip(bt['acts'], b.get('acts', [])):
        a['text'] = na['text']
json.dump(kits, open(kp, 'w'), indent=1)
subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'gen_creatures.py'), kp, os.path.join(data, 'dibCreatures.ts')], check=True)
print('story applied')
