"""Write src/data/story.ts and src/data/starters.ts from the story/hatchling research output.
usage: gen_story.py <workflow_result.json>"""
import json, sys
d = json.load(open(sys.argv[1]))
story = d['story']
starters = d['starters']['starters']
scenes = {s['id']: s['lines'] for s in story['scenes']}
st = {k: v for k, v in story.items() if k != 'scenes'}
st['scenes'] = scenes
open('src/data/story.ts', 'w').write(
    '// GENERATED by tools/gen_story.py — the kidnapping storyline, key-item texts and village names.\n'
    "import type { StoryData } from './storyTypes';\n\n"
    'export const STORY: StoryData = ' + json.dumps(st, indent=1, ensure_ascii=False) + ';\n')
open('src/data/starters.ts', 'w').write(
    '// GENERATED by tools/gen_story.py — the four Dragon Island Blue starter hatchlings (wiki data).\n'
    "import type { StarterData } from './storyTypes';\n\n"
    'export const STARTERS: StarterData[] = ' + json.dumps(starters, indent=1, ensure_ascii=False) + ';\n')
print(len(scenes), 'scenes;', len(starters), 'starters')
