"""Write src/data/bounties.ts from a workflow result's "bounties" list (appending to any already there).

usage: gen_bounties.py <result.json>
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = json.load(open(sys.argv[1]))
snake = lambda n: n.lower().replace(' ', '_').replace("'", '')
lines = lambda arr: [{'speaker': l.get('speaker', ''), 'portrait': l.get('portrait', 'none') or 'none', 'text': l['text']} for l in arr]
path = os.path.join(ROOT, 'src', 'data', 'bounties.ts')
src = open(path).read()
j = src.index('= ', src.index('export const BOUNTIES')) + 2
have = json.JSONDecoder().raw_decode(src[j:])[0]
ids = {b['id'] for b in have}
for b in d['bounties']:
    if b['id'] in ids:
        continue
    have.append({
        'id': b['id'], 'title': b['title'], 'giver': b['giver'], 'requires': b.get('requires', ''),
        'room': b['room'], 'criminal': b['criminal'],
        'team': [snake(n) for n in b['team']],
        'offer': lines(b['offer']), 'confront': lines(b['confront']), 'between': b['between'],
        'after': lines(b['after']), 'done': lines(b['done']),
        'reward': {'gold': int(b['reward_gold']), 'items': {x['item']: int(x['count']) for x in b['reward_items']}},
        'stages': b['stages'],
    })
open(path, 'w').write('// GENERATED by tools/gen_bounties.py: side quests against criminals and rogue tamers.\n'
                      "import type { Bounty } from './bountyTypes';\n\n"
                      'export const BOUNTIES: Bounty[] = ' + json.dumps(have, indent=1, ensure_ascii=False) + ';\n')
print(len(have), 'bounties')
