"""Turn the world-expansion workflow output into game data.

usage: gen_expansion.py <workflow_result.json>

Writes src/data/expansion.ts, copies the painted rooms into public/assets/bg,
and merges the new creature kits / room assignments into tools/dib_kits.json.
"""
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = json.load(open(sys.argv[1]))
plan = d['plan']
plans = {r['id']: r for r in plan['rooms']}
camel = lambda s: ''.join(w[:1].upper() + w[1:] for w in s.split('_'))


def npc_sheet(role: str) -> str:
    r = role.lower()
    return 'hunter' if any(k in r for k in ('hunt', 'guard', 'scout', 'ranger', 'watch', 'warden')) else 'innkeeper'


def color(hexs: str) -> int:
    try:
        return int(hexs.replace('#', ''), 16)
    except Exception:
        return 0xFFB35A


rooms = []
npc_info = {}
for rd in d['rooms']:
    rid = rd['id']
    p = plans.get(rid, {})
    shutil.copy(rd['image_path'], os.path.join(ROOT, 'public', 'assets', 'bg', rid + '.jpg'))
    npcs = []
    for n in rd.get('npcs', []):
        meta = next((x for x in p.get('npcs', []) if x['id'] == n['id']), {'name': n['id'].title(), 'role': ''})
        sheet = npc_sheet(meta.get('role', '') + ' ' + meta.get('name', ''))
        npcs.append({'id': n['id'], 'at': [round(n['x']), round(n['y'])], 'sprite': sheet + '_idle', 'name': meta['name'], 'portrait': sheet + '_portrait'})
        npc_info[n['id']] = {'name': meta['name'], 'portrait': sheet + '_portrait'}
    exits = []
    for e in rd['exits']:
        ex = {'rect': [round(e['x']), round(e['y']), round(e['w']), round(e['h'])], 'to': e['to'], 'spawn': e['spawn']}
        if e.get('locked_text'):
            ex['locked'] = 'never'  # the frontier: open in a future chapter
            ex['lockedText'] = e['locked_text']
        exits.append(ex)
    room = {
        'id': rid,
        'name': p.get('name', rid),
        'bg': 'bg_' + rid,
        'size': [round(v) for v in rd['size']],
        'walk': [[[round(x), round(y)] for x, y in poly] for poly in rd['walk']],
        'block': [[[round(x), round(y)] for x, y in poly] for poly in rd['block']],
        'spawns': {s['name']: {'at': [round(s['x']), round(s['y'])], 'dir': s['dir']} for s in rd['spawns']},
        'exits': exits,
        'scale': rd['scale'][:2],
        'music': p.get('music', 'forest'),
        'fireflies': 12 if p.get('kind') == 'village' else 30,
        'npcs': npcs,
        'things': [{'id': t['id'], 'at': [round(t['x']), round(t['y'])], 'r': round(t['r']), 'lines': t['lines']} for t in rd['things']],
        'candles': [{'id': rid, 'at': [round(rd['candle'][0]), round(rd['candle'][1])], 'kind': 'candle_tall'}] if rd.get('candle') else [],
        'lights': [{'at': [round(l['x']), round(l['y'])], 'r': round(l['r']), 'color': color(l['color']), 'flicker': bool(l['flicker'])} for l in rd['lights']],
    }
    rooms.append(room)

ws = plan['waystone_exits']
waystone = {
    'topLeft': ws['top_left_to'], 'topRight': ws['top_right_to'],
    'topLeftSpawn': 'fromWaystone', 'topRightSpawn': 'fromWaystone',
}
# Spawns in the Waystone room for walkers coming back from the new regions.
waystone_spawns = {
    'from' + camel(ws['top_left_to']): {'at': [190, 100], 'dir': 'down'},
    'from' + camel(ws['top_right_to']): {'at': [1490, 110], 'dir': 'down'},
}

st = d['story']
lines = lambda arr: [{'speaker': l.get('speaker', ''), 'portrait': l.get('portrait', 'none'), 'text': l['text']} for l in arr]
npc_dialogue = {}
for n in st['npc_dialogue']:
    info = npc_info.get(n['npc'], {'name': n['npc'].title(), 'portrait': 'innkeeper_portrait'})
    first = []
    for l in n['first']:
        por = l.get('portrait', 'none')
        if por == 'none' and l.get('speaker') and l['speaker'] not in ('Kael', ''):
            por = info['portrait']
        first.append({'speaker': l.get('speaker', ''), 'portrait': por, 'text': l['text']})
    npc_dialogue[n['npc']] = {'first': first, 'repeat': n['repeat'], 'name': info['name'], 'portrait': info['portrait']}
story = {
    'after_orochi_peace': lines(st['after_orochi_peace']),
    'after_orochi_won': lines(st['after_orochi_won']),
    'room_entries': {e['room']: lines(e['lines']) for e in st['room_entries']},
    'npc_dialogue': npc_dialogue,
    'frontier_lines': st['frontier_lines'],
    'map_text_addendum': st['map_text_addendum'],
}
sheets = sorted({n['sprite'][:-5] for r in rooms for n in r['npcs']})

ts = ('// GENERATED by tools/gen_expansion.py — the world beyond the Waystone fork.\n'
      "import type { RoomDef } from './rooms';\nimport type { StoryLine } from './storyTypes';\n\n"
      f'export const EXPANSION_ROOMS: RoomDef[] = {json.dumps(rooms, indent=1, ensure_ascii=False)};\n\n'
      f'export const WAYSTONE_EXITS = {json.dumps(waystone)};\n'
      f'export const WAYSTONE_SPAWNS: RoomDef["spawns"] = {json.dumps(waystone_spawns)};\n\n'
      'export const EXPANSION_STORY: {\n  after_orochi_peace: StoryLine[];\n  after_orochi_won: StoryLine[];\n'
      '  room_entries: Record<string, StoryLine[]>;\n  npc_dialogue: Record<string, { first: StoryLine[]; repeat: string[]; name: string; portrait: string }>;\n'
      '  frontier_lines: string[];\n  map_text_addendum: string;\n} = ' + json.dumps(story, indent=1, ensure_ascii=False) + ';\n\n'
      f'export const EXPANSION_NPC_SHEETS: string[] = {json.dumps(sheets)};\n')
open(os.path.join(ROOT, 'src', 'data', 'expansion.ts'), 'w').write(ts)

# Creatures: new kits + room assignments for existing ones.
kp = os.path.join(ROOT, 'tools', 'dib_kits.json')
kits = json.load(open(kp))
by_name = {k['kit']['name']: k for k in kits['kits']}
for k in d['kits']:
    if k['name'] in by_name:
        continue
    k['wiki']['image_url'] = k['wiki']['image_url'].replace('&amp;', '&').split('/revision')[0]
    entry = {'kit': k, 'verdict': {'ok': True, 'issues': []}, 'role': 'encounter', 'rooms': []}
    kits['kits'].append(entry)
    by_name[k['name']] = entry
for r in plan['rooms']:
    if r['id'] not in {x['id'] for x in rooms}:
        continue
    for n in r['encounters']:
        e = by_name.get(n)
        if e and e['role'] == 'encounter' and r['id'] not in e['rooms']:
            e['rooms'].append(r['id'])
json.dump(kits, open(kp, 'w'), indent=1)
print(len(rooms), 'rooms;', len(d['kits']), 'kits;', 'npc sheets', sheets)
