"""Write src/data/dibCreatures.ts from the wiki-verified creature kits.
usage: gen_creatures.py <kits.json> <out.ts>"""
import json, sys
d = json.load(open(sys.argv[1]))
kits = []
for k in d['kits']:
    kit = k['kit']
    kits.append({'role': k['role'], 'rooms': k['rooms'], **kit})
src = ('// GENERATED by tools/gen_creatures.py from Dragon Island Blue wiki data (dragonislandblue.fandom.com).\n'
       '// Creature names, numbers, stars, elements, stats, abilities and TU are the original DIB values.\n'
       '/* eslint-disable */\n'
       'export const DIB_KITS = ' + json.dumps(kits, indent=1, ensure_ascii=False) + ' as const;\n')
open(sys.argv[2], 'w').write(src)
print(len(kits), 'creatures ->', sys.argv[2])
