"""Merge room-audit fixes (<dir>/<room>_fix.json: block, occluders, walk) into src/data/roomFixes.ts.

usage: merge_room_fixes.py <audit dir>
Existing entries are kept; a room's new blocks/occluders are appended and a walk replacement wins.
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
path = os.path.join(ROOT, 'src', 'data', 'roomFixes.ts')
src = open(path).read()
j = src.index('= ', src.index('export const ROOM_FIXES')) + 2
fixes = json.JSONDecoder().raw_decode(src[j:])[0] if src[j:].lstrip().startswith('{') and '"' in src[j:j + 40] else {}
if not fixes:  # first run: the hand-written plaza entry
    fixes = {'plaza': {'occluders': [{'poly': [[598, 520], [606, 470], [650, 425], [700, 402], [760, 393], [820, 404], [862, 440], [884, 500], [880, 535], [822, 580], [700, 588], [620, 566]], 'base': 568}]}}
rnd = lambda pts: [[round(x), round(y)] for x, y in pts]
for f in sorted(glob.glob(os.path.join(sys.argv[1], '*_fix.json'))):
    rid = os.path.basename(f)[:-len('_fix.json')]
    d = json.load(open(f))
    e = fixes.setdefault(rid, {})
    if d.get('block'):
        e['block'] = e.get('block', []) + [rnd(p) for p in d['block']]
    if d.get('occluders'):
        e['occluders'] = e.get('occluders', []) + [{'poly': rnd(o['poly']), 'base': round(o['base'])} for o in d['occluders']]
    if d.get('walk'):
        e['walk'] = [rnd(p) for p in d['walk']]
open(path, 'w').write('// GENERATED by tools/merge_room_fixes.py from the room audits: occluders (tall painted objects the\n'
                      '// player walks behind), extra block polygons and corrected walk areas. Applied by rooms.ts.\n'
                      "import type { Pt } from './rooms';\n\n"
                      'export const ROOM_FIXES: Record<string, { occluders?: { poly: Pt[]; base: number }[]; block?: Pt[][]; walk?: Pt[][] }> = '
                      + json.dumps(fixes, separators=(',', ':')) + ';\n')
print(len(fixes), 'rooms with fixes')
