// GENERATED by tools/gen_bounties.py: side quests against criminals and rogue tamers.
import type { Bounty } from './bountyTypes';

export const BOUNTIES: Bounty[] = [
 {
  "id": "ringfeld_wreck_saw",
  "title": "The Ribs in the Cove",
  "giver": "maren",
  "requires": "met_maren",
  "room": "ringfeld_shore_road",
  "criminal": "Gest",
  "team": [
   "giant_turtle",
   "mer_warrior",
   "assassin"
  ],
  "offer": [
   {
    "speaker": "Maren",
    "portrait": "innkeeper_portrait",
    "text": "Someone has been down at the cove with a saw. They are cutting up the ribs of the broken boat and carrying the timber off along the shore road."
   },
   {
    "speaker": "Maren",
    "portrait": "innkeeper_portrait",
    "text": "Salt-cured oak burns slow. It sells in the dale for more than you would think."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "It is a wreck. Does it matter who takes it?"
   },
   {
    "speaker": "Maren",
    "portrait": "innkeeper_portrait",
    "text": "It matters to me. Send them off the shore road. That is all I ask."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A man is kneeling at the broken boat with a bow-saw, a stack of cut planks beside him. He stands up when he sees Kael."
   },
   {
    "speaker": "Gest",
    "portrait": "none",
    "text": "The sea left it here. Finders keep. The keepers can buy it back from me by the cord."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Put the saw down. Leave it where it lies."
   },
   {
    "speaker": "Gest",
    "portrait": "none",
    "text": "Then come and take it from me."
   }
  ],
  "between": [
   "* Gest whistles. Something heavy comes up out of the shallows. ({N} left)",
   "* \"One more,\" Gest says, and does not sound sure of it. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Gest",
    "portrait": "none",
    "text": "All right. All right. It is only wood."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He leaves the planks and the saw and goes off along the shore without looking back. Kael stacks the cut timber against the hull, above the tide line."
   }
  ],
  "done": [
   {
    "speaker": "Maren",
    "portrait": "innkeeper_portrait",
    "text": "He will not come back. Men like that go where it is easy."
   },
   {
    "speaker": "Maren",
    "portrait": "innkeeper_portrait",
    "text": "Leave the planks where you put them. The sea will have them in its own time. I would rather it did."
   }
  ],
  "reward": {
   "gold": 60,
   "items": {
    "tonic": 2
   }
  },
  "stages": [
   "Maren wants the man cutting up the wreck in the cove driven off the Ringfeld shore road.",
   "The wreck-cutter has gone from the shore road. Maren has been told."
  ]
 },
 {
  "id": "mangal_extremist",
  "title": "Extremist",
  "giver": "brann",
  "requires": "thanked_blood",
  "room": "mangal_crossroads",
  "criminal": "Elvin",
  "team": [
   "sasuke",
   "mutation",
   "drake"
  ],
  "offer": [
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The lodge keeps its board, whatever else happens. There is work on it. I would rather give it to you than stand and look at it."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Elvin. He hunted for the lodge once. A single star, no more. He left us, and now he says he will stop our work at the Giant Mangal."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "He has been seen in the Forest of Mangal, near the crossroads. He knows those paths better than you do. Remember that."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "What work at the Giant Mangal?"
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The stair is open now, and the lodge means to work the tree. He says it will not. Find him and stop him."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Someone drops from the branches over the crossroads and lands lightly in the leaves. A lean man in an old lodge coat, with the badge cut off it."
   },
   {
    "speaker": "Elvin",
    "portrait": "none",
    "text": "The lodge sends boys now. They must be short of hunters."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Brann says you mean to stop their work at the Giant Mangal."
   },
   {
    "speaker": "Elvin",
    "portrait": "none",
    "text": "Their work. Nets and cages up the stair, and whatever lives in the tree comes down in them to be sold."
   },
   {
    "speaker": "Elvin",
    "portrait": "none",
    "text": "The Giant Mangal was never the lodge's to work. I told them so, and they took my star back. Now I tell them another way."
   },
   {
    "speaker": "Elvin",
    "portrait": "none",
    "text": "You will not listen either. Fight."
   }
  ],
  "between": [
   "* Elvin calls another one out of the undergrowth. ({N} left)",
   "* \"The forest is on my side,\" Elvin says. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Elvin",
    "portrait": "none",
    "text": "...You fight like a lodge hunter."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I am not one."
   },
   {
    "speaker": "Elvin",
    "portrait": "none",
    "text": "Then you are wasting yourself on their board. Enough. I am done with the tree. Tell Brann that."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He goes off south through the trees, away from the old west track, and does not look back."
   }
  ],
  "done": [
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Gone, and done with the tree. Good. He was not a bad hunter. He only stopped agreeing with the lodge."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Take the lodge's money. It is honest money, whatever else it is."
   }
  ],
  "reward": {
   "gold": 90,
   "items": {
    "silver_card": 1
   }
  },
  "stages": [
   "Brann has posted Elvin, a former lodge hunter who threatens the lodge's work at the Giant Mangal. He hides near the Mangal crossroads.",
   "Elvin has given up on the tree and gone. Brann has been told."
  ]
 },
 {
  "id": "mangal_protester",
  "title": "Protester",
  "giver": "brann",
  "requires": "thanked_blood",
  "room": "mangal_building_site",
  "criminal": "Iris",
  "team": [
   "giant_wasp",
   "wasp_queen",
   "pincer"
  ],
  "offer": [
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "One more. The guild's building site in the Forest of Mangal. Locals came at it with their creatures and drove the breeders off."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "A woman named Iris leads them. She has beaten a dozen breeders sent to clear the site. Nobody here wants to be the thirteenth."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "What were they building?"
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Ask the guild. The lodge only keeps the board."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A woman sits on the half-built timber frame, a wasp the size of a dog resting on her arm. More of them hum in the scaffolding behind her."
   },
   {
    "speaker": "Iris",
    "portrait": "none",
    "text": "Another one. Tell your guild the frame stays as it is. Unfinished. The forest was here first."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I am not the guild. I only took the bounty."
   },
   {
    "speaker": "Iris",
    "portrait": "none",
    "text": "Then you are the guild. You just have not been told yet."
   }
  ],
  "between": [
   "* The scaffolding hums. Another one comes down. ({N} left)",
   "* Iris does not get up from the frame. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Iris",
    "portrait": "none",
    "text": "A dozen of them, and then you. ...Fine. We will go."
   },
   {
    "speaker": "Iris",
    "portrait": "none",
    "text": "We will come back when you are gone. The guild always leaves in the end. The forest does not."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* She whistles once, and the humming in the scaffolding follows her away through the trees."
   }
  ],
  "done": [
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The site is clear. The guild will be glad of it. I will write it on the board."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "She will be back. They always come back. That is not your trouble."
   }
  ],
  "reward": {
   "gold": 110,
   "items": {
    "silver_card": 1,
    "tonic": 2
   }
  },
  "stages": [
   "Brann has posted Iris, who leads the locals holding the guild's building site in the Forest of Mangal.",
   "Iris and her people have left the building site. Brann has been told."
  ]
 },
 {
  "id": "mangal_scavenger",
  "title": "What the Hunters Left",
  "giver": "edda",
  "requires": "thanked_wind",
  "room": "giant_mangal_f4",
  "criminal": "Hrok",
  "team": [
   "doombat",
   "kemet_king",
   "mutation"
  ],
  "offer": [
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Sit. Eat. Then listen to me."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "The two hunters who went up the tree after the barbarian. Their mothers still set places for them at supper."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "There is a man called Hrok who climbs where others have climbed, and comes down with what they dropped. He was seen going up past the third floor."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "What is theirs goes back to their mothers, not to some market in the dale. Stop him. Bring their things home to me."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "If I find them..."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Then you will know what to do."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A man is crouched over a hunter's pack on the boards, turning out its straps and pockets. A sack beside him is already half full."
   },
   {
    "speaker": "Hrok",
    "portrait": "none",
    "text": "It was lying on the floor. Nobody owns what lies on a floor this high."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "It belongs to the hunters from Dundean. Put it back."
   },
   {
    "speaker": "Hrok",
    "portrait": "none",
    "text": "Then they can come and take it off me. Or you can try."
   }
  ],
  "between": [
   "* Hrok shakes something out of the sack. It unfolds into wings. ({N} left)",
   "* \"Plenty more where that came from,\" Hrok says. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Hrok",
    "portrait": "none",
    "text": "Take it, then. Take the lot. I never found them. Only the pack, lying where it fell."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He empties the sack onto the boards and goes back down the torn stair. Kael puts the hunters' things back in the pack as they were, buckles it shut and shoulders it."
   }
  ],
  "done": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Kael sets the pack down on Edda's table. She looks at it for a long time before she touches the buckle."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "I know that strap. I mended it myself, the winter before they went up."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Their mothers will have this, at least. Here. He would have sold it for less than I am paying you. Now eat, and go and sleep."
   }
  ],
  "reward": {
   "gold": 150,
   "items": {
    "silver_card": 2
   }
  },
  "stages": [
   "Edda wants Hrok, a scavenger, stopped before he strips what the lost Dundean hunters left on the Giant Mangal's upper floors.",
   "Hrok has gone back down the tree empty-handed, and the hunters' pack is home with Edda."
  ]
 },
 {
  "id": "lighthouse_carmin",
  "title": "Defeat Carmin",
  "giver": "osk",
  "requires": "boss_archelon",
  "room": "lighthouse_f2",
  "criminal": "Carmin",
  "team": [
   "beast_knight",
   "gold_lion",
   "white_dolphin"
  ],
  "offer": [
   {
    "speaker": "Osk",
    "portrait": "hunter_portrait",
    "text": "The causeway is open. You did that. Someone used it before the tide had turned twice."
   },
   {
    "speaker": "Osk",
    "portrait": "hunter_portrait",
    "text": "A breeder out of Westguard. She said her guild sent her for the white dolphins at the tower's sea door, and she carried the guild's own creatures to do it."
   },
   {
    "speaker": "Osk",
    "portrait": "hunter_portrait",
    "text": "Westguard sends word along the coast that she has not come back, and it wants its creatures back."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "And you want me to fetch them."
   },
   {
    "speaker": "Osk",
    "portrait": "hunter_portrait",
    "text": "You beat the thing in the water. No one else on this shore could have."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A woman in a Westguard coat stands at the sea door with a net and a coil of rope, the boards wet around her. Oil casks are stacked behind her, untouched."
   },
   {
    "speaker": "Carmin",
    "portrait": "none",
    "text": "The guild supplied me with its most powerful monsters. You think you can stop me?"
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Westguard wants them back."
   },
   {
    "speaker": "Carmin",
    "portrait": "none",
    "text": "Westguard can come and ask. The tide brings dolphins to this door every night, and I am keeping what I catch."
   }
  ],
  "between": [
   "* Carmin hauls on the rope. Something slides in through the sea door. ({N} left)",
   "* \"That one was the guild's,\" Carmin says. \"This one is mine.\" ({N} left)"
  ],
  "after": [
   {
    "speaker": "Carmin",
    "portrait": "none",
    "text": "They supplied you as well, then. A dragon? That is hardly fair."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "It was given to me."
   },
   {
    "speaker": "Carmin",
    "portrait": "none",
    "text": "Mine were given to me too. Fine. I will walk the causeway back while it is open."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* She coils her rope and goes down the stair. The casks behind where she stood are full, their seals unbroken. Above, the stair climbs on to the lamp-room. No light comes down it."
   }
  ],
  "done": [
   {
    "speaker": "Osk",
    "portrait": "hunter_portrait",
    "text": "She came off the causeway at dusk with nothing in her net. I barred the gate behind her."
   },
   {
    "speaker": "Osk",
    "portrait": "hunter_portrait",
    "text": "Westguard's coin. Take it. And do not go higher in that tower than you need to."
   }
  ],
  "reward": {
   "gold": 180,
   "items": {
    "silver_card": 2,
    "tonic": 2
   }
  },
  "stages": [
   "Osk says a Westguard breeder named Carmin crossed the causeway after the white dolphins and kept the guild's creatures. She is in the Lighthouse.",
   "Carmin has walked back over the causeway. Osk has been told."
  ]
 },
 {
  "id": "earlsome_al_rashid",
  "title": "al-Rashid",
  "giver": "thing:longdale_square/guild_board",
  "requires": "",
  "room": "cave_of_earlsome_f1",
  "criminal": "al-Rashid",
  "team": [
   "spark",
   "cockatrice",
   "spark",
   "manticore"
  ],
  "offer": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Kael reads the al-Rashid notice again. Under the print, someone has added in pen: Dealt in caged monsters. Do not open his crates."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Below that, the guild's mark and a sum. The cave north of here is the Cave of Earlsome. The road to it goes out through the north gate."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "The north road. I am going that way."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Crates are stacked inside the cave mouth, roped shut, with air holes cut in their sides. Something in them crackles, and the air smells of struck flint."
   },
   {
    "speaker": "al-Rashid",
    "portrait": "none",
    "text": "Close enough. Whatever Longdale is paying you, I pay more. A spark in a box sells for a year's rent in Wesing."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "You broke out of Dundean's prison to sell caged monsters?"
   },
   {
    "speaker": "al-Rashid",
    "portrait": "none",
    "text": "I broke out because the doors were wood. The rest is trade. No? Then I will open the crates."
   }
  ],
  "between": [
   "* al-Rashid kicks a crate open. Static lifts the hair on Kael's arms. ({N} left)",
   "* \"Another crate,\" al-Rashid says. \"I have plenty.\" ({N} left)"
  ],
  "after": [
   {
    "speaker": "al-Rashid",
    "portrait": "none",
    "text": "Enough. Take me back to your board, then. They will only lose me again."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "A man in ash came up this road, with two children. Did you see them?"
   },
   {
    "speaker": "al-Rashid",
    "portrait": "none",
    "text": "I heard them pass in the dark. The small one was crying. I stayed in the cave. Anyone would have."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Kael cuts the ropes on the crates and leaves the lids open. When he looks round again, the crates are empty, and so is the cave mouth."
   }
  ],
  "done": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The al-Rashid notice has been taken down. In its place, in the same pen: Crates found empty. Paid."
   }
  ],
  "reward": {
   "gold": 200,
   "items": {
    "silver_card": 2
   }
  },
  "stages": [
   "The Longdale guild board posts al-Rashid, a monster trader who escaped Dundean's prison into the Cave of Earlsome, north of the gate.",
   "al-Rashid's crates are empty and he has run again. The Longdale board has marked it paid."
  ]
 },
 {
  "id": "earlsome_body_guard",
  "title": "Body Guard",
  "giver": "thing:longdale_square/guild_board",
  "requires": "bounty_done_earlsome_al_rashid",
  "room": "earlsome_mountain_path",
  "criminal": "Njord",
  "team": [
   "bat_fiend",
   "evil_eye",
   "dream_eater",
   "bat_king"
  ],
  "offer": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A newer notice is pinned over the old ones: \"An unknown breeder is blocking the mountain path north of the cave. Travel past the cave entrance and head north.\""
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Beside it, in pen: Will not speak. Will not move. Turns everyone back."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Then he will have to move for me."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A barricade of cut pine lies across the path, with a lean-to beside it. A big man in a fur hood sits at the fire, and stands as Kael comes up through the snow."
   },
   {
    "speaker": "Njord",
    "portrait": "none",
    "text": "..."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I am going north. Let me by."
   },
   {
    "speaker": "Njord",
    "portrait": "none",
    "text": "..."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He does not answer. He only steps into the middle of the path, and the shadows behind the lean-to begin to move."
   }
  ],
  "between": [
   "* Njord says nothing. Another one comes out of the shadows. ({N} left)",
   "* Still nothing. Only the next one. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Njord",
    "portrait": "none",
    "text": "..."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He looks at Kael for a long time. Then he takes something from inside his coat and holds it out."
   },
   {
    "speaker": "Njord",
    "portrait": "none",
    "text": "Take this with you."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A small leather purse, heavy. Njord shoulders his pack, steps round the barricade and goes down toward the dale. He does not look back."
   }
  ],
  "done": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The mountain path notice has been struck through. Under it, in the guild's pen: Path clear. Paid."
   }
  ],
  "reward": {
   "gold": 280,
   "items": {
    "silver_card": 3,
    "tonic": 2
   }
  },
  "stages": [
   "The Longdale guild board posts an unknown breeder blocking the mountain path north of the Cave of Earlsome.",
   "The breeder on the mountain path has gone down to the dale. The way north is clear."
  ]
 },
 {
  "id": "earlsome_dangerous_cats",
  "title": "Dangerous Cats",
  "giver": "hild",
  "requires": "met_hild",
  "room": "north_earlsome_road",
  "criminal": "Constance",
  "team": [
   "fire_cub",
   "snow_cub"
  ],
  "offer": [
   {
    "speaker": "Hild",
    "portrait": "innkeeper_portrait",
    "text": "You go north in the morning. Then I will ask you something, and you can say no."
   },
   {
    "speaker": "Hild",
    "portrait": "innkeeper_portrait",
    "text": "Constance, from the end of the lane. One winter she picked up cubs half-dead in the snow and raised them by her stove. They grew. They are not small now."
   },
   {
    "speaker": "Hild",
    "portrait": "innkeeper_portrait",
    "text": "The guild told her to turn them in. She would not. She took them out through the north gate and up the frost road, toward the cave."
   },
   {
    "speaker": "Hild",
    "portrait": "innkeeper_portrait",
    "text": "She is no criminal. But the guild has posted her, and someone will go after her. I would rather it was someone who will not hurt her."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A woman in a shawl stands in the middle of the frost road. Two big cats pace round her in the snow, one with fire at its mouth, one as white as the frost."
   },
   {
    "speaker": "Constance",
    "portrait": "none",
    "text": "If the guild wants them, it can come and take them. I raised them from nothing."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Hild sent me. She asked me not to hurt you."
   },
   {
    "speaker": "Constance",
    "portrait": "none",
    "text": "Then do not. Hurt them, if you must. They will not let you near me."
   }
  ],
  "between": [
   "* \"Easy,\" Constance says to the other one, and lets it go. ({N} left)"
  ],
  "after": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The cats come back to Constance and lie down at her feet in the snow, breathing hard. She kneels between them."
   },
   {
    "speaker": "Constance",
    "portrait": "none",
    "text": "They only ever wanted the stove. I will take them up into the hills. Far up, where there is no lane and no guild."
   },
   {
    "speaker": "Constance",
    "portrait": "none",
    "text": "Tell Hild she was right about me. She usually is."
   }
  ],
  "done": [
   {
    "speaker": "Hild",
    "portrait": "innkeeper_portrait",
    "text": "You did not bring her back. Good. I did not think you would."
   },
   {
    "speaker": "Hild",
    "portrait": "innkeeper_portrait",
    "text": "The guild will not pay you for her, so I will. Take it, and eat something before you go."
   }
  ],
  "reward": {
   "gold": 160,
   "items": {
    "tonic": 2,
    "tart": 2
   }
  },
  "stages": [
   "Hild asks Kael to find Constance, who took her grown cubs up the North Earlsome frost road rather than turn them in, before someone harder does.",
   "Constance has taken her cats up into the hills. Hild has been told."
  ]
 },
 {
  "id": "ashfall_ford_toll",
  "title": "The Ford Toll",
  "giver": "runa",
  "requires": "met_runa",
  "room": "azurelake_east_ford",
  "criminal": "Halla",
  "team": [
   "reptilo",
   "kappa",
   "giant_turtle",
   "mer_warrior"
  ],
  "offer": [
   {
    "speaker": "Runa",
    "portrait": "innkeeper_portrait",
    "text": "Iron goes out of Emberfold by one road. Over the Reach, down the slope, and across the grey river at Ashfall Ford."
   },
   {
    "speaker": "Runa",
    "portrait": "innkeeper_portrait",
    "text": "Three loads this season have not come over the ford. The carriers come back on foot with nothing, and say only that she had creatures in the water."
   },
   {
    "speaker": "Runa",
    "portrait": "innkeeper_portrait",
    "text": "I am too old to walk the Reach. You are not. Find her, and stop her."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Someone has been living in the courier post. A woman steps out of its doorway as Kael comes down to the ford, and the grey water behind her stirs."
   },
   {
    "speaker": "Halla",
    "portrait": "none",
    "text": "Toll. Whatever you carry, half of it."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I carry nothing. Runa sent me."
   },
   {
    "speaker": "Halla",
    "portrait": "none",
    "text": "The old smith. She can pay in iron like everyone else. You can pay in bruises."
   }
  ],
  "between": [
   "* The ash on the water parts. Something else comes up out of the ford. ({N} left)",
   "* \"The river is mine,\" Halla says. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Halla",
    "portrait": "none",
    "text": "Enough. Tell her she can have her ford. The iron is under the floor of the post. All of it."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* She wades across the grey river and is gone into the ash banks. Under the floor of the courier post lie three carriers' loads of Emberfold iron, wrapped in sacking."
   }
  ],
  "done": [
   {
    "speaker": "Runa",
    "portrait": "innkeeper_portrait",
    "text": "The iron came up the slope this morning. All three loads. The carriers say you left it stacked and dry."
   },
   {
    "speaker": "Runa",
    "portrait": "innkeeper_portrait",
    "text": "A smith pays her debts. Take this."
   }
  ],
  "reward": {
   "gold": 240,
   "items": {
    "silver_card": 2,
    "orb": 1
   }
  },
  "stages": [
   "Runa wants the toll-taker who robs Emberfold's iron carriers at Ashfall Ford stopped.",
   "The ford is clear, and the stolen iron is back in Emberfold. Runa has been told."
  ]
 },
 {
  "id": "scorched_cairn_breaker",
  "title": "The Cairn-Breaker",
  "giver": "aud",
  "requires": "met_aud",
  "room": "scorched_reach",
  "criminal": "Skeggi",
  "team": [
   "pincer",
   "flame_wing",
   "drake"
  ],
  "offer": [
   {
    "speaker": "Aud",
    "portrait": "innkeeper_portrait",
    "text": "Eat first. Then I will tell you about the cairns."
   },
   {
    "speaker": "Aud",
    "portrait": "innkeeper_portrait",
    "text": "There is one safe line across the Reach. Step off it and the glass takes your boots, then your feet. Emberfold piles cairns along the line for travellers to follow."
   },
   {
    "speaker": "Aud",
    "portrait": "innkeeper_portrait",
    "text": "Someone has been knocking them down. Three travellers walked off the line this month. Two came in burned. One did not come in."
   },
   {
    "speaker": "Aud",
    "portrait": "innkeeper_portrait",
    "text": "Whoever it is goes through what they leave behind. Find them. The mountain is cruel enough without help."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A cairn lies scattered across the glass, its stones rolled off the line. A man in an ash-grey cloak is setting the last of them out of sight behind a fused rock."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "You are the one breaking the cairns."
   },
   {
    "speaker": "Skeggi",
    "portrait": "none",
    "text": "Breaking? I move them. A traveller who walks where I want him to walks out of his boots, and out of his pack."
   },
   {
    "speaker": "Skeggi",
    "portrait": "none",
    "text": "Nobody comes to fetch them out here. Nobody will come to fetch you."
   }
  ],
  "between": [
   "* Skeggi strikes his heel on the glass. Something answers from the heat. ({N} left)",
   "* The air shakes over the glass. Another one comes. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Skeggi",
    "portrait": "none",
    "text": "All right. I am going. Down the Reach, the far way. There are other roads."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He goes the long way, keeping to his own line across the glass. Kael picks the stones up one by one and builds the cairn again where it stood."
   }
  ],
  "done": [
   {
    "speaker": "Aud",
    "portrait": "innkeeper_portrait",
    "text": "The travellers who came up the slope this week followed the cairns all the way. Not one of them burned."
   },
   {
    "speaker": "Aud",
    "portrait": "innkeeper_portrait",
    "text": "You built them again yourself, they say. Sit. Eat. Then take this."
   }
  ],
  "reward": {
   "gold": 260,
   "items": {
    "silver_card": 2,
    "tart": 2
   }
  },
  "stages": [
   "Aud wants whoever is knocking down the cairns on the Scorched Reach found and stopped.",
   "The cairn-breaker has left the Reach, and the cairns stand again. Aud has been told."
  ]
 },
 {
  "id": "volcano_false_guide",
  "title": "The Way Down",
  "giver": "ketil",
  "requires": "met_ketil",
  "room": "volcano_l3",
  "criminal": "Bersi",
  "team": [
   "samurai",
   "flame_wing",
   "bon"
  ],
  "offer": [
   {
    "speaker": "Ketil",
    "portrait": "hunter_portrait",
    "text": "Below this ring, no one comes to fetch you. I say it to everyone who goes down. Most of them listen."
   },
   {
    "speaker": "Ketil",
    "portrait": "hunter_portrait",
    "text": "There is a man called Bersi who sells the way down. He takes their coin at my gate, leads them onto the Empty Ring, and leaves them there in the dark."
   },
   {
    "speaker": "Ketil",
    "portrait": "hunter_portrait",
    "text": "Some find their way back up. Some I find. Some I do not. I keep this gate. I cannot leave it to go after him."
   },
   {
    "speaker": "Ketil",
    "portrait": "hunter_portrait",
    "text": "You are going down anyway. If you meet him on the third ring, stop him."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Among the bricked-up doors of the Empty Ring, a man with a lantern is counting coins into a pouch. When he sees Kael, he smiles and lifts the lantern."
   },
   {
    "speaker": "Bersi",
    "portrait": "none",
    "text": "Lost? I know the way down. All ten rings. For a fair price."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Ketil says you leave people here in the dark."
   },
   {
    "speaker": "Bersi",
    "portrait": "none",
    "text": "Ketil says a great deal, for a man who never leaves his gate. I take them where they pay to go. Pay, or go back up."
   }
  ],
  "between": [
   "* Bersi steps back behind his lantern. Another one comes out of the heat. ({N} left)",
   "* \"There is always another,\" Bersi says. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Bersi",
    "portrait": "none",
    "text": "Fine. Fine. I will go up. Tell Ketil he can have his ring back."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He climbs the stair, his lantern swinging. Kael waits on the Empty Ring until the light is gone, and listens. Nothing. No one is calling."
   }
  ],
  "done": [
   {
    "speaker": "Ketil",
    "portrait": "hunter_portrait",
    "text": "He came up past my gate an hour after you went down. He did not look at me. He will not come down again."
   },
   {
    "speaker": "Ketil",
    "portrait": "hunter_portrait",
    "text": "I do not thank many people who go below. Take this."
   }
  ],
  "reward": {
   "gold": 320,
   "items": {
    "silver_card": 3,
    "tonic": 2
   }
  },
  "stages": [
   "Ketil wants Bersi, a false guide who leaves travellers stranded on the Empty Ring, stopped on the volcano's third level.",
   "Bersi has gone back up past the wardens' gate. Ketil has been told."
  ]
 },
 {
  "id": "volcano_old_anvils",
  "title": "The Old Anvils",
  "giver": "thing:volcano_l2/board",
  "requires": "",
  "room": "volcano_l6",
  "criminal": "Ulfar",
  "team": [
   "legionnaire",
   "samurai",
   "bon",
   "drake"
  ],
  "offer": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The wardens' board is cut from one slab of black stone. Most of the names chalked on it have a line through them."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* One notice is newer than the rest: \"A smith of the lower ring has gone down to the sixth to take the old anvils. The old forges are not ours. Bring him up.\""
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Under it, in another hand: \"Ulfar. He took his creatures with him. They are not small.\""
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "The sixth level. That is a long way down."
   }
  ],
  "confront": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Among the cold anvils of the old forges, a man is working an iron bar under the largest of them. Old hammers lie all round him, rusted to the floor."
   },
   {
    "speaker": "Ulfar",
    "portrait": "none",
    "text": "Do you know how old these are? Older than Emberfold. Nobody up there has ever forged on one. I will be the first."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "The board says they are not yours."
   },
   {
    "speaker": "Ulfar",
    "portrait": "none",
    "text": "They are not anyone's. That is the point. Get out of my forge."
   }
  ],
  "between": [
   "* Ulfar strikes his bar on the anvil. The ring of it brings another out of the heat. ({N} left)",
   "* The old forges answer him. ({N} left)",
   "* \"One more,\" Ulfar says. ({N} left)"
  ],
  "after": [
   {
    "speaker": "Ulfar",
    "portrait": "none",
    "text": "...Enough. I could not have shifted it anyway. Nine days I have been at it."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He drops the bar. The great anvil has not moved the width of a finger on its block."
   },
   {
    "speaker": "Ulfar",
    "portrait": "none",
    "text": "I will go up. Tell the wardens they can cross my name out themselves."
   }
  ],
  "done": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Someone has drawn a line through Ulfar's notice. Beside it, in the wardens' hand: Came up on his own feet. Paid."
   }
  ],
  "reward": {
   "gold": 400,
   "items": {
    "gold_card": 1,
    "silver_card": 2
   }
  },
  "stages": [
   "The wardens' board in Emberfold posts Ulfar, a smith who went down to the volcano's sixth level to take the old anvils.",
   "Ulfar has come back up on his own feet. The wardens' board is marked paid."
  ]
 }
];
