// GENERATED by tools/gen_creatures.py from Dragon Island Blue wiki data (dragonislandblue.fandom.com).
// Creature names, numbers, stars, elements, stats, abilities and TU are the original DIB values.
/* eslint-disable */
export const DIB_KITS = [
 {
  "role": "encounter",
  "rooms": [
   "outskirts",
   "forest"
  ],
  "name": "Bat Fiend",
  "id": "bat_fiend",
  "wiki": {
   "number": "116",
   "stars": 2,
   "element": "Air",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/4/46/Bat_Fiend.png",
   "image_size": [
    105,
    95
   ],
   "lv1": {
    "hp": 28,
    "attack": 5,
    "magic": 8,
    "speed": 19,
    "defense": 6,
    "resist": 13
   },
   "abilities": [
    {
     "name": "Confusion",
     "tu": "250",
     "target": "1 Foe",
     "effect": "Confuses the target for 437 TUs, causing it to sometimes do nothing"
    },
    {
     "name": "Turbulence",
     "tu": "70",
     "target": "1 Foe",
     "effect": "5-6 Magical Damage (Air)"
    }
   ],
   "evolution": "Bat Fiend (1st Form) -> Vampire (evolves at level 22) -> Dark Spirit (evolves at level 34; final form)",
   "obtain": "Captured in No Man's Castle or obtained through a golden egg. Can also be found in Greater Wesing."
  },
  "sprite": {
   "description": "A gaunt, shadowy humanoid bat-demon with a pale lavender-grey skull-like face, two curled horns, and huge tattered violet membrane wings spread wide with hooked claw tips. Its thin dark body and long spindly legs dangle beneath it as it hovers in mid-air.",
   "dominant_color_hex": "#4A3F6B",
   "faces": "front",
   "flier": true
  },
  "battle": {
   "check": "* BAT FIEND - No. 116 - AIR - 2 STARS.\n* Swift on the wing (SPD 19). Knows Turbulence and Confusion.\n* Its eyes hold no light. Something in the dark has hollowed them.",
   "intro": "* A torn shape drops out of the night sky.\n* Bat Fiend circles you without a sound.",
   "idle": [
    "* Bat Fiend hangs in the air. Its wingbeats are slow and uneven.",
    "* The membranes of its wings are split in places. Old tears, never healed.",
    "* A cold draft follows it. It smells of wet stone and the castle dark.",
    "* Bat Fiend keeps turning toward the waystone, as if it hears something there."
   ],
   "talk": [
    "...skree.",
    "The dark\ncalls us\nback.",
    "Too far\nfrom the\ncastle.",
    "Do not\nlook up.",
    "The stone\nhums at\nnight."
   ],
   "spare_text": "* Bat Fiend's wings go still for a moment.\n* Then it lifts away into the night, and does not look back.",
   "lore": "No. 116 - Bat Fiend. Air element, 2 stars. Lv1: HP 28, ATK 5, MAG 8, SPD 19, DEF 6, RES 13. Abilities: Turbulence (70 TU, 1 foe, 5-6 magical Air damage) and Confusion (250 TU, 1 foe, confuses for 437 TUs so it sometimes does nothing). Evolves into Vampire at level 22, then Dark Spirit at level 34. Captured in No Man's Castle, found in Greater Wesing, or hatched from a golden egg. Those that roost near the darkened waystone no longer return to their colonies.",
   "acts": [
    {
     "name": "Keep Still",
     "text": [
      "* You stand perfectly still beneath it.",
      "* Bat Fiend drifts lower, listening to your breathing.",
      "* It no longer circles quite so close."
     ],
     "mercy": 40,
     "once": true,
     "calm": 1
    },
    {
     "name": "Shield Light",
     "text": [
      "* You cup your hands around your lantern and dim it.",
      "* Bat Fiend's frantic wingbeats slow.",
      "* The light was hurting it."
     ],
     "mercy": 35,
     "once": false,
     "calm": 1
    },
    {
     "name": "Hum Low",
     "text": [
      "* You hum a low, steady note, like wind through stone.",
      "* Bat Fiend's head tilts. The sound is something it knows.",
      "* It no longer tries to scatter your thoughts."
     ],
     "mercy": 50,
     "once": true,
     "calm": 2
    }
   ],
   "attacks": [
    {
     "ability": "Turbulence",
     "tu": 70,
     "base_pattern": "tornado_sweep",
     "projectile": "fx_tornado",
     "tint_hex": "#9B8FD1",
     "twist": "none",
     "box": [
      420,
      280
     ],
     "intensity": 0.8,
     "flavor": "* Bat Fiend beats its torn wings. The air turns against you."
    },
    {
     "ability": "Confusion",
     "tu": 250,
     "base_pattern": "spiral",
     "projectile": "fx_sparkle",
     "tint_hex": "#B07CE8",
     "twist": "confuse",
     "box": [
      340,
      300
     ],
     "intensity": 0.7,
     "flavor": "* Bat Fiend's wingbeats fall into a strange rhythm. Your thoughts begin to slip."
    }
   ]
  }
 },
 {
  "role": "encounter",
  "rooms": [
   "outskirts"
  ],
  "name": "Blood Priest",
  "id": "blood_priest",
  "wiki": {
   "number": "149",
   "stars": 2,
   "element": "Fire",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/8/84/Blood_Priest.png",
   "image_size": [
    99,
    112
   ],
   "lv1": {
    "hp": 30,
    "attack": 10,
    "magic": 3,
    "speed": 6,
    "defense": 3,
    "resist": 3
   },
   "abilities": [
    {
     "name": "Fire Storm",
     "tu": "130",
     "target": "All Foes",
     "effect": "1 Magical Damage (Fire)"
    },
    {
     "name": "Flame",
     "tu": "130",
     "target": "1 Foe",
     "effect": "3-4 Magical Damage (Fire)"
    }
   ],
   "evolution": "Blood Priest (1st Form) -> Blood Warrior (evolves at level 17) -> Blood Rogue (evolves at level 37)",
   "obtain": "Location: No Man's Cave in Southern Alvalon."
  },
  "sprite": {
   "description": "A tall standing humanoid priest in heavy layered charcoal-grey robes veined and splattered with blood-red patterns. It wears a tall stovepipe-like hood; its face is hidden under a mass of grey tentacle-like strands with red markings. Its wide bell sleeves hang down; the hand on the viewer's left holds a long staff topped with an ankh-like loop, the other clawed hand is raised. The robe flares into a ragged red-and-black skirt over thin legs. It faces the viewer and stands on the ground (no wings, does not float).",
   "dominant_color_hex": "#352A2A",
   "faces": "front",
   "flier": false
  },
  "battle": {
   "check": "* BLOOD PRIEST - No. 149 - FIRE - 2 STARS.\n* ATK 10, DEF 3. Casts Fire Storm and Flame, 130 TU each.\n* Its robes are stained in patterns no one remembers the meaning of.",
   "intro": "* A robed figure stands in the road ahead.\n* Blood Priest raises its staff. Not in blessing.",
   "idle": [
    "* Blood Priest murmurs a litany. The grass at its feet blackens.",
    "* The tendrils over its face twitch, as if tasting the air.",
    "* Smoke rises from its sleeves, though nothing there is burning.",
    "* Blood Priest's chant falters. For a moment it seems to forget the words."
   ],
   "talk": [
    "Kneel.",
    "The flame\nmust be\nfed.",
    "I tended\na shrine\nonce.",
    "Its light\nwent out.",
    "Now only\nthe fire\nanswers."
   ],
   "spare_text": "* Blood Priest lowers its staff.\n* It turns and walks slowly toward Southern Alvalon, its litany fading.",
   "lore": "No. 149 - Blood Priest. Fire element, 2 stars. Lv1: HP 30, ATK 10, MAG 3, SPD 6, DEF 3, RES 3. Casts Fire Storm (130 TU, all foes, 1 magical Fire damage) and Flame (130 TU, 1 foe, 3-4 magical Fire damage). Evolves into Blood Warrior at level 17, then Blood Rogue at level 37. Found in No Man's Cave in Southern Alvalon. It still keeps its rites, though whatever it once prayed to has long stopped answering.",
   "acts": [
    {
     "name": "Pray",
     "text": [
      "* You bow your head and pray in silence beside it.",
      "* Blood Priest's chant slows to match your breathing."
     ],
     "mercy": 40,
     "once": false,
     "calm": 1
    },
    {
     "name": "Ask Its Faith",
     "text": [
      "* You ask Blood Priest what it once prayed for.",
      "* It is quiet for a long time. The staff trembles in its hand."
     ],
     "mercy": 35,
     "once": true,
     "calm": 1
    },
    {
     "name": "Lay an Offering",
     "text": [
      "* You set a handful of dried herbs at its feet.",
      "* Blood Priest burns them slowly, with care.",
      "* The smoke smells clean, for once."
     ],
     "mercy": 30,
     "once": true,
     "calm": 0
    }
   ],
   "attacks": [
    {
     "ability": "Fire Storm",
     "tu": 130,
     "base_pattern": "diagonal_rain",
     "projectile": "fx_sparkle",
     "tint_hex": "#FF5A1F",
     "twist": "all_foes_wide",
     "box": [
      480,
      260
     ],
     "intensity": 0.8,
     "flavor": "* Blood Priest lifts its staff. Ash and embers fall over everyone."
    },
    {
     "ability": "Flame",
     "tu": 130,
     "base_pattern": "aimed_volley",
     "projectile": "orb_blood",
     "tint_hex": "#FF7A00",
     "twist": "none",
     "box": [
      320,
      280
     ],
     "intensity": 1.1,
     "flavor": "* Blood Priest points its staff at you. A tongue of fire follows."
    }
   ]
  }
 },
 {
  "role": "encounter",
  "rooms": [
   "outskirts",
   "mosswood"
  ],
  "name": "Bones",
  "id": "bones",
  "wiki": {
   "number": "100",
   "stars": 2,
   "element": "Death",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/5/5e/Bones.png",
   "image_size": [
    50,
    95
   ],
   "lv1": {
    "hp": 29,
    "attack": 7,
    "magic": 6,
    "speed": 13,
    "defense": 10,
    "resist": 10
   },
   "abilities": [
    {
     "name": "Plague",
     "tu": "130",
     "target": "1 Foe",
     "effect": "7-8 Magical Damage (Death)"
    },
    {
     "name": "Venom Spray",
     "tu": "130",
     "target": "All Foes",
     "effect": "Poisons: 8-9 Damage (Death) over 500 TUs"
    },
    {
     "name": "Venom Sting",
     "tu": "130",
     "target": "1 Foe",
     "effect": "8-9 Physical Damage (Death), Poisons: 8-9 Death Damage (additional) over 500 TUs."
    }
   ],
   "evolution": "1st Form: Bones (no further evolution). Recipe: Bones + Bitewing = Skull Crow.",
   "obtain": "Found in No Man's Castle in Southern Alvalon. Also found at Safaris and in Greater Wesing."
  },
  "sprite": {
   "description": "A tall, gaunt, hunched skeleton standing on two legs, its dark grey-black bones edged in pale white highlights, wrapped in a wispy violet/purple ghostly aura. Bony skull with faint glowing eyes, long dangling arms with clawed fingers, knees slightly bent mid-shamble. Seen mostly from the front, head turned slightly to the viewer's right.",
   "dominant_color_hex": "#4B4660",
   "faces": "front",
   "flier": false
  },
  "battle": {
   "check": "* BONES - No. 100 - DEATH - 2 STARS.\n* ATK 7, DEF 10. Knows Plague, Venom Spray and Venom Sting.\n* A first form with no evolution. It has nothing left to become.",
   "intro": "* Bones shambles out of the dark.\n* A violet haze clings to it like a shroud.",
   "idle": [
    "* Bones stands crooked, its joints grinding softly.",
    "* Violet mist seeps out from between its ribs.",
    "* Its eye sockets glow faintly. There is no one behind them. Almost no one.",
    "* It smells of a sealed cellar and old venom."
   ],
   "talk": [
    "...",
    "cold.\nalways\ncold.",
    "i had a\nname once.",
    "the mist\nholds me\ntogether.",
    "let me\nrest."
   ],
   "spare_text": "* Bones lowers its clawed hands.\n* It turns and shambles back into the mist, slower now, as if tired.",
   "lore": "No. 100 - Bones. Death element, 2 stars. Lv1: HP 29, ATK 7, MAG 6, SPD 13, DEF 10, RES 10. Knows Plague (7-8 magical Death damage to 1 foe), Venom Spray (poisons all foes for 8-9 Death damage over 500 TUs) and Venom Sting (8-9 physical Death damage plus 8-9 more over 500 TUs); each costs 130 TU. A 1st-form monster with no further evolution; Bones combined with Bitewing makes a Skull Crow. Found in No Man's Castle in Southern Alvalon, at the Safaris, and in Greater Wesing. Nothing holds it together but the mist and an old, stubborn will.",
   "acts": [
    {
     "name": "Stand Vigil",
     "text": [
      "* You stand beside Bones without speaking.",
      "* After a while, the grinding of its joints quiets.",
      "* It seems less alone."
     ],
     "mercy": 40,
     "once": true,
     "calm": 20
    },
    {
     "name": "Clear the Mist",
     "text": [
      "* You wave the violet haze away from its joints.",
      "* For a moment Bones stands a little straighter."
     ],
     "mercy": 35,
     "once": false,
     "calm": 30
    },
    {
     "name": "Speak of Crows",
     "text": [
      "* You tell Bones about the Bitewing you saw circling overhead.",
      "* Its skull turns slowly upward.",
      "* Something stirs in its empty sockets. Not quite hope."
     ],
     "mercy": 45,
     "once": true,
     "calm": 15
    }
   ],
   "attacks": [
    {
     "ability": "Plague",
     "tu": 130,
     "base_pattern": "homing",
     "projectile": "orb_blood",
     "tint_hex": "#7A4FA8",
     "twist": "none",
     "box": [
      340,
      260
     ],
     "intensity": 0.8,
     "flavor": "* Bones uses Plague. Sickly motes drift toward you."
    },
    {
     "ability": "Venom Spray",
     "tu": 130,
     "base_pattern": "sparkle_rain",
     "projectile": "orb_moss",
     "tint_hex": "#6BCB3A",
     "twist": "poison",
     "box": [
      460,
      280
     ],
     "intensity": 0.85,
     "flavor": "* Bones uses Venom Spray. A green mist settles over the field."
    },
    {
     "ability": "Venom Sting",
     "tu": 130,
     "base_pattern": "aimed_volley",
     "projectile": "orb_moss",
     "tint_hex": "#4FA82E",
     "twist": "poison",
     "box": [
      320,
      260
     ],
     "intensity": 0.9,
     "flavor": "* Bones uses Venom Sting. A bony claw lashes out, slick with venom."
    }
   ]
  }
 },
 {
  "role": "encounter",
  "rooms": [
   "forest"
  ],
  "name": "Dark Priest",
  "id": "dark_priest",
  "wiki": {
   "number": "150",
   "stars": 2,
   "element": "Fire",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/8/88/Dark_Priest.png",
   "image_size": [
    73,
    105
   ],
   "lv1": {
    "hp": 29,
    "attack": 3,
    "magic": 10,
    "speed": 10,
    "defense": 3,
    "resist": 3
   },
   "abilities": [
    {
     "name": "Flame",
     "tu": "130",
     "target": "1 Foe",
     "effect": "11-14 Magical Damage (Fire)"
    },
    {
     "name": "Ignite",
     "tu": "70",
     "target": "1 Foe",
     "effect": "6-7 Magical Damage (Fire)"
    }
   ],
   "evolution": "Dark Priest (1st Form) -> Dark Mage (2nd Form), evolves at level 22",
   "obtain": "Monster page: \"IN Western Gracia(?)\". Location pages: Greater Wesing - Southwest of Wesing (with Bat Fiend, Blood Priest, Bones, Cult Priest) and Southeast Forest (with Cockatrice, Devil Worm, Evil Eye, Scale Knight); also in the Western Gracia field monster list."
  },
  "sprite": {
   "description": "A tall humanoid figure in a black wide-brimmed hat and a long black greatcoat that flares out to the right at the hem. The face is completely hidden in shadow under the hat brim. A long white stole/scarf hangs in two strips down the front of a dark suit. Pale gloved hands hang at its sides. Almost entirely black and charcoal grey with white accents. Stands on the ground, body angled slightly but essentially facing the viewer.",
   "dominant_color_hex": "#202020",
   "faces": "front",
   "flier": false
  },
  "battle": {
   "check": "* DARK PRIEST - No. 150 - FIRE - 2 STARS.\n* MAG 10. Casts Flame and Ignite. Evolves into Dark Mage at LV 22.\n* No one has seen the face beneath its hat.",
   "intro": "* A tall figure steps out from between the trees.\n* Dark Priest stands motionless, face lost in shadow.",
   "idle": [
    "* Dark Priest's coat stirs, though there is no wind.",
    "* Candle smoke drifts through the forest. There are no candles.",
    "* Its white stole is the only pale thing in the clearing.",
    "* Dark Priest whispers names. No one answers to them."
   ],
   "talk": [
    "Turn\nback.",
    "The fire\nis all\nthat's left.",
    "I had a\nflock\nonce.",
    "The stone\ntook them.",
    "Do not\nlook under\nthe brim."
   ],
   "spare_text": "* Dark Priest closes its gloved hand. The fire at its fingertips dies.\n* It steps back between the trees and is gone.",
   "lore": "No. 150 - Dark Priest. Fire element, 2 stars, humanoid. Lv1: HP 29, ATK 3, MAG 10, SPD 10, DEF 3, RES 3. Casts Flame (130 TU, 11-14 magical Fire damage to 1 foe) and Ignite (70 TU, 6-7 magical Fire damage to 1 foe). Evolves into Dark Mage at level 22. Found southwest of Wesing and in the Southeast Forest of Greater Wesing, alongside Bat Fiends, Bones, Blood Priests and Cult Priests; also reported in Western Gracia. Its face has never been seen, and those who tried to look did not speak of it.",
   "acts": [
    {
     "name": "Avert Eyes",
     "text": [
      "* You lower your gaze and do not look beneath its hat.",
      "* Dark Priest's shoulders loosen. It did not want to be seen."
     ],
     "mercy": 30,
     "once": true,
     "calm": 1
    },
    {
     "name": "Listen",
     "text": [
      "* You sit on a stump and let Dark Priest speak.",
      "* It tells you of a congregation that stopped coming. Then of the night they disappeared."
     ],
     "mercy": 40,
     "once": false,
     "calm": 1
    },
    {
     "name": "Say the Names",
     "text": [
      "* You repeat the names it whispered, slowly and clearly.",
      "* Dark Priest goes still. The flames at its fingertips gutter low."
     ],
     "mercy": 35,
     "once": false,
     "calm": 1
    }
   ],
   "attacks": [
    {
     "ability": "Flame",
     "tu": 130,
     "base_pattern": "homing",
     "projectile": "fx_sparkle",
     "tint_hex": "#FF6A1A",
     "twist": "none",
     "box": [
      400,
      300
     ],
     "intensity": 1.1,
     "flavor": "* Dark Priest raises a pale hand. Fire gathers in its palm."
    },
    {
     "ability": "Ignite",
     "tu": 70,
     "base_pattern": "rift_bursts",
     "projectile": "fx_sparkle",
     "tint_hex": "#FFB02E",
     "twist": "none",
     "box": [
      360,
      280
     ],
     "intensity": 0.8,
     "flavor": "* Dark Priest snaps its fingers. The ground beneath you catches."
    }
   ]
  }
 },
 {
  "role": "encounter",
  "rooms": [
   "forest",
   "mosswood"
  ],
  "name": "Scale Knight",
  "id": "scale_knight",
  "wiki": {
   "number": "156",
   "stars": 2.5,
   "element": "Earth",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/7/7f/Scale_Knight.png",
   "image_size": [
    75,
    115
   ],
   "lv1": {
    "hp": 30,
    "attack": 7,
    "magic": 7,
    "speed": 14,
    "defense": 11,
    "resist": 11
   },
   "abilities": [
    {
     "name": "Venom Spray",
     "tu": "130",
     "target": "all foes",
     "effect": "8-9 damage over 500 duration"
    },
    {
     "name": "Venom Sting",
     "tu": "130",
     "target": "1",
     "effect": "8-9 physical damage (earth), 8-9 earth damage over 500 duration"
    }
   ],
   "evolution": "Scale Knight (1st form) -> Serpent Mage (evolves at level 25) -> Snake God (evolves at level 53)",
   "obtain": "From an egg; from Ringfeld; from the Lighthouse; can be found in some spots in Greater Wesing; can be found in some spots in Safaris"
  },
  "sprite": {
   "description": "A grey, pale-scaled naga warrior: humanoid upper torso with a long serpent tail coiled beneath it, the tail's underside dotted with dark diamond-shaped scale markings and ending in a thin black tip. Its head is hooded with tall pointed ear/crest shapes and a shadowed face. It holds a long thin sword raised over its shoulder, blade angled up and across to the right. Monochrome palette of greys, charcoal and off-white.",
   "dominant_color_hex": "#6B6B6B",
   "faces": "left",
   "flier": false
  },
  "battle": {
   "check": "* SCALE KNIGHT - No. 156 - EARTH - 2.5 STARS.\n* DEF 11. Venom Spray and Venom Sting.\n* Evolves into Serpent Mage at LV 25. It still keeps an oath to no one.",
   "intro": "* Scale Knight rises from the ferns, blade raised.\n* It does not hiss. It only watches.",
   "idle": [
    "* Scale Knight's grip on its sword never loosens.",
    "* Its coils tighten, slowly, then hold.",
    "* The air smells of venom and wet moss.",
    "* Its tongue flicks out. It has not stopped tasting the air for a long time."
   ],
   "talk": [
    "Halt.",
    "I guard\nthis path.",
    "For whom,\nI cannot\nrecall.",
    "Sssomething\nin the\nstone...",
    "...lower\nyour\nhands."
   ],
   "spare_text": "* Scale Knight sheathes its blade and bows its head.\n* It coils away into the ferns, still on guard against something.",
   "lore": "No. 156 - Scale Knight. Earth element, 2.5 stars. Lv1: HP 30, ATK 7, MAG 7, SPD 14, DEF 11, RES 11. Venom Spray (130 TU) deals 8-9 damage over 500 duration to all foes; Venom Sting (130 TU) deals 8-9 physical (earth) damage plus 8-9 earth damage over 500 duration to one foe. Evolves into Serpent Mage at level 25, then Snake God at level 53. Obtainable from an egg, from Ringfeld and the Lighthouse, and found in some spots in Greater Wesing and the Safaris. It keeps a vigil whose purpose it has long since forgotten.",
   "acts": [
    {
     "name": "Salute",
     "text": [
      "* You raise your hand in a knight's salute.",
      "* Scale Knight answers it, slowly, from long habit."
     ],
     "mercy": 35,
     "once": false,
     "calm": 1
    },
    {
     "name": "Lay Down Arms",
     "text": [
      "* You set your weapon on the ground between you.",
      "* Scale Knight stares at it for a long moment.",
      "* Its blade dips."
     ],
     "mercy": 40,
     "once": true,
     "calm": 1
    },
    {
     "name": "Ask Its Oath",
     "text": [
      "* You ask Scale Knight who it swore to protect.",
      "* It opens its mouth to answer. Nothing comes.",
      "* Its coils loosen. It looks lost."
     ],
     "mercy": 45,
     "once": true,
     "calm": 2
    }
   ],
   "attacks": [
    {
     "ability": "Venom Spray",
     "tu": 130,
     "base_pattern": "diagonal_rain",
     "projectile": "orb_moss",
     "tint_hex": "#7FD13B",
     "twist": "poison",
     "box": [
      460,
      280
     ],
     "intensity": 0.9,
     "flavor": "* Scale Knight exhales. A thin green mist rolls across the field."
    },
    {
     "ability": "Venom Sting",
     "tu": 130,
     "base_pattern": "aimed_volley",
     "projectile": "orb_moss",
     "tint_hex": "#5E8C2A",
     "twist": "poison",
     "box": [
      340,
      280
     ],
     "intensity": 1,
     "flavor": "* Scale Knight lunges. Its blade is slick with venom."
    }
   ]
  }
 },
 {
  "role": "encounter",
  "rooms": [
   "forest",
   "mosswood"
  ],
  "name": "Devil Worm",
  "id": "devil_worm",
  "wiki": {
   "number": "98",
   "stars": 2.5,
   "element": "Earth",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/1/16/Devil_Worm.png",
   "image_size": [
    104,
    120
   ],
   "lv1": {
    "hp": 30,
    "attack": 9,
    "magic": 9,
    "speed": 14,
    "defense": 9,
    "resist": 9
   },
   "abilities": [
    {
     "name": "Clasp",
     "tu": "130",
     "target": "1 Foe",
     "effect": "9-12 Physical Damage (Earth)"
    },
    {
     "name": "Reincarnate",
     "tu": "200",
     "target": "-",
     "effect": "Adds a Random Monster to Your Team"
    }
   ],
   "evolution": "1st Form: Devil Worm (no further evolutions)",
   "obtain": "Found in the Lighthouse in Ringfeld. Devil Worm can also be found in multiple spots in Safaris and Greater Wesing."
  },
  "sprite": {
   "description": "A thick, coiled worm made of rounded, bumpy dark maroon-brown segments, piled in a spiral on the ground. Its head rears up out of the coil and opens into a wide, fanged maw with tendril-like whiskers and a cluster of small glowing red eyes. Grim, slimy, and very much a ground dweller.",
   "dominant_color_hex": "#5A3A3A",
   "faces": "front",
   "flier": false
  },
  "battle": {
   "check": "* DEVIL WORM - No. 98 - EARTH - 2.5 STARS.\n* Clasp crushes a foe. Reincarnate adds a random monster to its team.\n* Its many eyes never close.",
   "intro": "* The moss splits open.\n* Devil Worm rears up out of the earth.",
   "idle": [
    "* Devil Worm's segments grind against each other like wet gravel.",
    "* A cluster of red eyes follows your every step.",
    "* The soil around it has gone grey and sour.",
    "* Something beneath the ground shifts in answer to it."
   ],
   "talk": [
    "skrrrch.",
    "the soil\nis sick.",
    "MANY EYES.\nNO SLEEP.",
    "it came\nup from\nbelow.",
    "...hungry."
   ],
   "spare_text": "* Devil Worm loosens its coil.\n* It sinks back into the soil, and the ground closes over it.",
   "lore": "No. 98 - Devil Worm. Earth element, 2.5 stars. Lv1: HP 30, ATK 9, MAG 9, SPD 14, DEF 9, RES 9. Abilities: Clasp (130 TU, 9-12 physical Earth damage to 1 foe) and Reincarnate (200 TU, adds a random monster to its team). A 1st-form monster with no evolutions. Lives in the Lighthouse in Ringfeld, and in several spots in the Safaris and Greater Wesing. Where it surfaces, the earth stays cold for days.",
   "acts": [
    {
     "name": "Meet Its Eyes",
     "text": [
      "* You hold the gaze of each red eye in turn.",
      "* Devil Worm stops swaying. It is not used to being looked at."
     ],
     "mercy": 40,
     "once": true,
     "calm": 1
    },
    {
     "name": "Offer Soil",
     "text": [
      "* You scoop up clean loam from beneath the roots and hold it out.",
      "* Devil Worm draws in the scent of it. Its coil eases."
     ],
     "mercy": 35,
     "once": false,
     "calm": 1
    },
    {
     "name": "Kneel Low",
     "text": [
      "* You kneel and press your palm to the cold ground.",
      "* Devil Worm lowers its head toward yours. The grinding of its segments slows."
     ],
     "mercy": 30,
     "once": false,
     "calm": 2
    }
   ],
   "attacks": [
    {
     "ability": "Clasp",
     "tu": 130,
     "base_pattern": "orbit_ring",
     "projectile": "orb_blood",
     "tint_hex": "#7A3B32",
     "twist": "none",
     "box": [
      340,
      280
     ],
     "intensity": 0.9,
     "flavor": "* Devil Worm uses Clasp. Its coils close in around you."
    },
    {
     "ability": "Reincarnate",
     "tu": 200,
     "base_pattern": "rift_bursts",
     "projectile": "fx_sparkle",
     "tint_hex": "#B8865A",
     "twist": "none",
     "box": [
      380,
      300
     ],
     "intensity": 0.8,
     "flavor": "* Devil Worm uses Reincarnate. Something claws its way up out of the earth."
    }
   ]
  }
 },
 {
  "role": "miniboss",
  "rooms": [
   "mosswood"
  ],
  "name": "Lich",
  "id": "lich",
  "wiki": {
   "number": "159",
   "stars": 3,
   "element": "Death",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/8/86/Lich.png",
   "image_size": [
    76,
    110
   ],
   "lv1": {
    "hp": 294,
    "attack": 25,
    "magic": 99,
    "speed": 74,
    "defense": 74,
    "resist": 173
   },
   "abilities": [
    {
     "name": "Awaken",
     "tu": "100",
     "target": "All Allies",
     "effect": "Removes Sleep"
    },
    {
     "name": "Dark Matter",
     "tu": "160",
     "target": "1 foe",
     "effect": "118-145 Damage"
    },
    {
     "name": "Disaster",
     "tu": "100",
     "target": "2 foes",
     "effect": "46-57 Damage"
    },
    {
     "name": "Enlighten",
     "tu": "200",
     "target": "All Allies",
     "effect": "Increase magic by 16"
    }
   ],
   "evolution": "None listed on the wiki",
   "obtain": "No Man's Castle. Liches can also be found in a single spot in Greater Wesing occasionally (Lich here will be levels 13 to 16). The spot is the leftmost spot in the forest section and first one that can be accessed. NOTE: the wiki's Level 1 stat column is empty; the stats stored under 'lv1' are the wiki's Level 23 column (HP 294, ATK 25, MAG 99, SPD 74, DEF 74, RES 173). The wiki says the ability values are shown as if the monster were level 1."
  },
  "sprite": {
   "description": "A tall, gaunt sorcerer in layered crimson and deep-wine robes, with a tall, bent pointed hood and a high flared collar. The face inside the hood is a dark, shadowed void with no visible features. A grey lock or drape hangs down the left side of the hood. An ornate silver and purple chest piece sits on the front of the robe. On the viewer's right it holds a tall silver-lavender staff with a spiral, curled head that rises above the hood. The sleeves and hem are wide and ragged, and the robe spreads out to the ground. No feet are visible, so it seems to hover. It stands mostly front-on.",
   "dominant_color_hex": "#7A1632",
   "faces": "front",
   "flier": true
  },
  "battle": {
   "check": "* LICH - No. 159 - DEATH - 3 STARS.\n* (Wiki Lv23 stats) MAG 99, RES 173, ATK 25.\n* It does not touch what it destroys.",
   "intro": "* The moss goes cold. A crimson robe drifts out between the trees.\n* LICH blocks the way.",
   "idle": [
    "* Lich hovers above the trail. The moss beneath it withers.",
    "* Lich murmurs an incantation in a language older than Wesing.",
    "* The smell of tallow and crumbling pages.",
    "* The void beneath its hood turns toward the waystone, then back to you."
   ],
   "talk": [
    "Mortal.\nTurn back.",
    "Dark Matter\nwill find\nyou.",
    "I kept\nthe old\nbooks.",
    "The stone\nhas begun\nto speak.",
    "I can no\nlonger\nrefuse it."
   ],
   "spare_text": "* Lich lowers its staff.\n* It drifts back into the mosswood, its incantation falling silent.\n* Lich was spared.",
   "lore": "LICH (#159) - Death element, 3 stars. Found in No Man's Castle, and occasionally at one spot in Greater Wesing (the leftmost spot in the forest section, Lv13-16). Abilities: Awaken (100 TU, removes Sleep from all allies), Dark Matter (160 TU, 118-145 damage to 1 foe), Disaster (100 TU, 46-57 damage to 2 foes), Enlighten (200 TU, raises all allies' magic by 16). Wiki stats (Lv23 column; the Lv1 column is blank): HP 294, ATK 25, MAG 99, SPD 74, DEF 74, RES 173. No evolution listed. Once a keeper of forbidden learning, it now answers to a voice from the darkened waystone.",
   "acts": [
    {
     "name": "Bow",
     "text": [
      "* You bow before Lich as one would before an elder.",
      "* The void beneath its hood regards you for a long while.",
      "* Its hostility wanes."
     ],
     "mercy": 35,
     "once": true,
     "calm": 1
    },
    {
     "name": "Ask of the Books",
     "text": [
      "* You ask Lich what was written in the books it kept.",
      "* It begins to answer. The words come slowly, half-forgotten.",
      "* For a moment, it remembers itself."
     ],
     "mercy": 30,
     "once": false,
     "calm": 1
    },
    {
     "name": "Resist Sleep",
     "text": [
      "* The cold makes your eyes heavy. You force them open.",
      "* Lich watches you fight it. It knows what Awaken is for.",
      "* It seems to respect the effort."
     ],
     "mercy": 25,
     "once": false,
     "calm": 0
    }
   ],
   "attacks": [
    {
     "ability": "Dark Matter",
     "tu": 160,
     "base_pattern": "rift_bursts",
     "projectile": "orb_blood",
     "tint_hex": "#4B1460",
     "twist": "none",
     "box": [
      340,
      280
     ],
     "intensity": 1.4,
     "flavor": "* Lich draws the light out of the air. DARK MATTER gathers. (160 TU)"
    },
    {
     "ability": "Disaster",
     "tu": 100,
     "base_pattern": "diagonal_rain",
     "projectile": "orb_blood",
     "tint_hex": "#A3203F",
     "twist": "none",
     "box": [
      420,
      260
     ],
     "intensity": 1.1,
     "flavor": "* Lich calls down DISASTER on two foes. (100 TU)"
    },
    {
     "ability": "Enlighten",
     "tu": 200,
     "base_pattern": "sparkle_rain",
     "projectile": "fx_sparkle",
     "tint_hex": "#C9B6FF",
     "twist": "none",
     "box": [
      320,
      260
     ],
     "intensity": 0.7,
     "flavor": "* Lich casts ENLIGHTEN. Its allies' MAGIC rises by 16. (200 TU)"
    },
    {
     "ability": "Awaken",
     "tu": 100,
     "base_pattern": "orbit_ring",
     "projectile": "fx_silverring",
     "tint_hex": "#D8D0E8",
     "twist": "none",
     "box": [
      300,
      240
     ],
     "intensity": 0.6,
     "flavor": "* Lich casts AWAKEN. Sleep is lifted from all its allies. (100 TU)"
    }
   ]
  }
 },
 {
  "role": "boss",
  "rooms": [
   "waystone"
  ],
  "name": "Orochi",
  "id": "orochi",
  "wiki": {
   "number": "080",
   "stars": 8.5,
   "element": "Fire",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/1/12/Orochi.png",
   "image_size": [
    143,
    140
   ],
   "lv1": {
    "hp": 62,
    "attack": 40,
    "magic": 40,
    "speed": 34,
    "defense": 55,
    "resist": 55
   },
   "abilities": [
    {
     "name": "Dragon Rage",
     "tu": "250",
     "target": "All Foes",
     "effect": "31-38 Physical Damage (Fire)"
    },
    {
     "name": "Flame",
     "tu": "130",
     "target": "One Foe",
     "effect": "45-55 Magical Damage (Fire)"
    },
    {
     "name": "Inferno",
     "tu": "200",
     "target": "All Foes",
     "effect": "26-31 Magical Damage (Fire)"
    },
    {
     "name": "Wiggle",
     "tu": "130",
     "target": "One Foe",
     "effect": "45-55 Physical Damage (Fire)"
    }
   ],
   "evolution": "Noko -> Orochi (Noko evolves at level 34). Orochi is the 2nd and final form.",
   "obtain": "Evolve from Noko at level 34; Saintspring (forest, rare)"
  },
  "sprite": {
   "description": "A hulking, grounded hydra: a squat mound of dark slate-gray scaly coils with a short tail curling out at the lower right, from which a writhing crown of many serpent necks rises. Each head is olive/sage green with pale yellow-green jaws, several gaping open, splayed outward in all directions around a dark hollow at the center. Viewed from the front.",
   "dominant_color_hex": "#4A4E46",
   "faces": "front",
   "flier": false
  },
  "battle": {
   "check": "* OROCHI - No. 080 - FIRE - 8.5 STARS.\n* The Overlord of Norwoods. An eight-headed serpent, evolved from Noko.\n* Eight heads. Each one is in pain.",
   "intro": "* Orochi is coiled around the great darkened waystone.\n* One head turns toward you. Then all eight.",
   "idle": [
    "* Orochi's heads hiss over one another. None of them sound like their own.",
    "* Black veins pulse along its coils, in time with the waystone.",
    "* Smoke and the smell of scorched scales hang in the air.",
    "* Embers drift up between the heads and die in the dark."
   ],
   "talk": [
    "We are\nOrochi.",
    "Overlord\nof the\nNorwoods.",
    "The stone\nspeaks\nthrough us.",
    "It burns.\nIt always\nburns.",
    "Once we\nwere only\nNoko."
   ],
   "spare_text": "* The heads fall silent, one by one.\n* Orochi uncoils from the waystone and lowers itself to the ground.\n* The black veins along its scales begin to fade.",
   "lore": "#080 Orochi - Fire element, 8.5 stars. The Overlord of Norwoods. The second and final form of Noko (evolves at level 34); also found rarely in the Saintspring forest. Lv1: HP 62, ATK 40, MAG 40, SPD 34, DEF 55, RES 55. Abilities: Dragon Rage (250 TU, 31-38 physical Fire damage to all foes), Flame (130 TU, 45-55 magical Fire damage to one foe), Inferno (200 TU, 26-31 magical Fire damage to all foes), Wiggle (130 TU, 45-55 physical Fire damage to one foe). Named after Yamata no Orochi, the eight-headed, eight-tailed serpent of Japanese myth; it is a serpent, not a dragon. Bound to the darkened waystone, it guards the corruption it was meant to keep out.",
   "acts": [
    {
     "name": "Name the Heads",
     "text": [
      "* You speak to each head in turn, slowly, one at a time.",
      "* ...five, six, seven, eight.",
      "* The hissing thins. Each head was waiting to be heard."
     ],
     "mercy": 22,
     "once": false,
     "calm": 15
    },
    {
     "name": "Stand Unarmed",
     "text": [
      "* You lower your hands and stand within reach of its jaws.",
      "* Eight heads hover over you. None of them strike.",
      "* The fire in its throats burns lower."
     ],
     "mercy": 28,
     "once": false,
     "calm": 20
    },
    {
     "name": "Recall Noko",
     "text": [
      "* You tell Orochi of Noko, the small serpent it once was.",
      "* All eight heads go still at once.",
      "* Somewhere in those coils, something remembers being small."
     ],
     "mercy": 35,
     "once": true,
     "calm": 30
    }
   ],
   "attacks": [
    {
     "ability": "Dragon Rage",
     "tu": 250,
     "base_pattern": "column_drop",
     "projectile": "orb_blood",
     "tint_hex": "#E0401C",
     "twist": "all_foes_wide",
     "box": [
      500,
      300
     ],
     "intensity": 1.5,
     "flavor": "* Every head screams at once. Orochi uses Dragon Rage."
    },
    {
     "ability": "Flame",
     "tu": 130,
     "base_pattern": "aimed_volley",
     "projectile": "fx_sparkle",
     "tint_hex": "#FF8A1E",
     "twist": "burn",
     "box": [
      340,
      280
     ],
     "intensity": 1.1,
     "flavor": "* One head draws back and takes aim. Orochi uses Flame."
    },
    {
     "ability": "Inferno",
     "tu": 200,
     "base_pattern": "radial_burst",
     "projectile": "fx_sparkle",
     "tint_hex": "#FF5A12",
     "twist": "all_foes_wide",
     "box": [
      480,
      320
     ],
     "intensity": 1.3,
     "flavor": "* The heads fan out and exhale together. Orochi uses Inferno."
    },
    {
     "ability": "Wiggle",
     "tu": 130,
     "base_pattern": "swoop",
     "projectile": "orb_blood",
     "tint_hex": "#C8501E",
     "twist": "multi_hit",
     "box": [
      360,
      260
     ],
     "intensity": 1,
     "flavor": "* Orochi's coils convulse and lash outward. Orochi uses Wiggle."
    }
   ]
  }
 },
 {
  "role": "ending",
  "rooms": [
   "waystone"
  ],
  "name": "Divine",
  "id": "divine",
  "wiki": {
   "number": "202",
   "stars": 9,
   "element": "Life",
   "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/f/f9/Divine.png",
   "image_size": [
    196,
    128
   ],
   "lv1": {
    "hp": 1835,
    "attack": 1304,
    "magic": 1304,
    "speed": 1641,
    "defense": 1641,
    "resist": 1641
   },
   "abilities": [
    {
     "name": "Holy",
     "tu": "160",
     "target": "1 Foe",
     "effect": "1758-2149 Magical Damage"
    },
    {
     "name": "Immunity",
     "tu": "-",
     "target": "Self",
     "effect": "Immune from all negative status effects"
    },
    {
     "name": "Judgement",
     "tu": "250",
     "target": "All Foes",
     "effect": "1024-1251 Magical Damage"
    },
    {
     "name": "Justice",
     "tu": "100",
     "target": "1 Foe",
     "effect": "1056-1291 Physical Damage, +100% Damage vs. Demonic"
    },
    {
     "name": "Neutralize",
     "tu": "130",
     "target": "All Foes",
     "effect": "Removes all effects, good or bad, from targets"
    }
   ],
   "evolution": "None (Divine is a Spirit, Type: Spirit; the wiki lists no evolutions)",
   "obtain": "Located in the Sanctuary in Applefield, 18th Floor."
  },
  "sprite": {
   "description": "A pale, glowing white humanoid spirit with a radiant light burst around its head, standing upright with arms at its sides, framed by two huge spread pairs of dark charcoal-gray feathered wings that fan out wide on both sides.",
   "dominant_color_hex": "#55555E",
   "faces": "front",
   "flier": true
  },
  "battle": {
   "check": "* DIVINE - No. 202 - LIFE - 9 STARS.\n* A Spirit of the Sanctuary. Immune to all negative status effects.\n* It does not regard you as a foe.",
   "intro": "* Light pours down from above.\n* Divine descends.",
   "idle": [
    "* Divine hovers in perfect silence. Its wings do not move.",
    "* The light around its head is steady and warm.",
    "* The waystone's shadow draws back from it.",
    "* The air is still and clean, like the Sanctuary at dawn."
   ],
   "talk": [
    "...",
    "THE STONE\nREMEMBERS\nTHE SUN.",
    "MERCY IS\nALSO A\nLIGHT.",
    "BE STILL."
   ],
   "spare_text": "* Divine lowers its wings.\n* The waystone drinks its light and burns bright again.",
   "lore": "No. 202 - Divine. Life element, 9 stars, Type: Spirit. Found in the Sanctuary in Applefield, 18th Floor. Abilities: Holy, Immunity, Judgement, Justice, Neutralize (Justice deals +100% damage vs. Demonic). Has no evolutions. Its wings are dark, but nothing it touches stays that way.",
   "acts": [
    {
     "name": "Pray",
     "text": [
      "* You fold your hands and pray.",
      "* Divine's glow softens."
     ],
     "mercy": 25,
     "once": false,
     "calm": 20
    },
    {
     "name": "Bow",
     "text": [
      "* You bow low before the winged spirit.",
      "* Divine inclines its head."
     ],
     "mercy": 20,
     "once": false,
     "calm": 15
    },
    {
     "name": "Show Mercy",
     "text": [
      "* You tell Divine you spared the one at the waystone.",
      "* For a moment, the light feels warm instead of blinding."
     ],
     "mercy": 40,
     "once": true,
     "calm": 30
    }
   ],
   "attacks": [
    {
     "ability": "Holy",
     "tu": 160,
     "base_pattern": "aimed_volley",
     "projectile": "fx_sparkle",
     "tint_hex": "#FFF6D0",
     "twist": "none",
     "box": [
      340,
      260
     ],
     "intensity": 1.2,
     "flavor": "* Divine uses Holy. A spear of white light descends."
    },
    {
     "ability": "Judgement",
     "tu": 250,
     "base_pattern": "sparkle_rain",
     "projectile": "fx_sparkle",
     "tint_hex": "#FFE27A",
     "twist": "all_foes_wide",
     "box": [
      520,
      320
     ],
     "intensity": 1.5,
     "flavor": "* Divine uses Judgement. The whole sky grows bright and silent."
    },
    {
     "ability": "Justice",
     "tu": 100,
     "base_pattern": "column_drop",
     "projectile": "fx_silverring",
     "tint_hex": "#E8E8F0",
     "twist": "none",
     "box": [
      360,
      280
     ],
     "intensity": 1.1,
     "flavor": "* Divine uses Justice. The light seeks out what is Demonic."
    },
    {
     "ability": "Neutralize",
     "tu": 130,
     "base_pattern": "orbit_ring",
     "projectile": "fx_waterring",
     "tint_hex": "#BFE8FF",
     "twist": "neutralize",
     "box": [
      420,
      300
     ],
     "intensity": 0.9,
     "flavor": "* Divine uses Neutralize. Every effect, good or bad, washes away."
    }
   ]
  }
 }
] as const;
