// GENERATED by tools/gen_expansion.py — the world beyond the Waystone fork.
import type { RoomDef } from './rooms';
import type { StoryLine } from './storyTypes';

export const EXPANSION_ROOMS: RoomDef[] = [
 {
  "id": "norwoods_scorched_road",
  "name": "Norwoods — Scorched Road",
  "bg": "bg_norwoods_scorched_road",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     640,
     944
    ],
    [
     660,
     840
    ],
    [
     700,
     740
    ],
    [
     740,
     640
    ],
    [
     770,
     540
    ],
    [
     760,
     460
    ],
    [
     690,
     405
    ],
    [
     580,
     360
    ],
    [
     470,
     315
    ],
    [
     380,
     272
    ],
    [
     310,
     222
    ],
    [
     250,
     165
    ],
    [
     200,
     112
    ],
    [
     150,
     62
    ],
    [
     125,
     0
    ],
    [
     245,
     0
    ],
    [
     262,
     40
    ],
    [
     295,
     92
    ],
    [
     345,
     142
    ],
    [
     425,
     197
    ],
    [
     525,
     247
    ],
    [
     640,
     296
    ],
    [
     740,
     338
    ],
    [
     790,
     375
    ],
    [
     900,
     385
    ],
    [
     990,
     355
    ],
    [
     1080,
     300
    ],
    [
     1160,
     240
    ],
    [
     1240,
     180
    ],
    [
     1310,
     120
    ],
    [
     1380,
     70
    ],
    [
     1425,
     0
    ],
    [
     1540,
     0
    ],
    [
     1490,
     60
    ],
    [
     1420,
     110
    ],
    [
     1360,
     170
    ],
    [
     1300,
     230
    ],
    [
     1220,
     290
    ],
    [
     1130,
     350
    ],
    [
     1040,
     400
    ],
    [
     950,
     450
    ],
    [
     910,
     500
    ],
    [
     920,
     620
    ],
    [
     970,
     720
    ],
    [
     1020,
     820
    ],
    [
     1040,
     944
    ]
   ]
  ],
  "block": [],
  "spawns": {
   "fromWaystone": {
    "at": [
     810,
     890
    ],
    "dir": "up"
   },
   "fromNorwoodsSerpentHollow": {
    "at": [
     190,
     50
    ],
    "dir": "down"
   },
   "fromNorwoodsMangalRoots": {
    "at": [
     1475,
     45
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     600,
     932,
     460,
     12
    ],
    "to": "waystone",
    "spawn": "fromNorwoodsScorchedRoad"
   },
   {
    "rect": [
     120,
     0,
     130,
     12
    ],
    "to": "norwoods_serpent_hollow",
    "spawn": "fromNorwoodsScorchedRoad"
   },
   {
    "rect": [
     1420,
     0,
     125,
     12
    ],
    "to": "norwoods_mangal_roots",
    "spawn": "fromNorwoodsScorchedRoad"
   }
  ],
  "scale": [
   0.28,
   0.5
  ],
  "music": "forest",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "furrows",
    "at": [
     840,
     700
    ],
    "r": 80,
    "lines": [
     "* Eight furrows, burned into the road side by side.",
     "* They come from the north. Whatever made them was dragged south, not walking."
    ]
   },
   {
    "id": "fork_lantern",
    "at": [
     808,
     372
    ],
    "r": 45,
    "lines": [
     "* A trail lantern. Someone refilled it, not long ago.",
     "* The oil smells of the Azurelake guild stores."
    ]
   },
   {
    "id": "signpost",
    "at": [
     882,
     378
    ],
    "r": 45,
    "lines": [
     "* The signpost has been scorched blank.",
     "* The left arm points along the furrows. The right one points toward a dark shape rising over the trees."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     808,
     298
    ],
    "r": 190,
    "color": 16756816,
    "flicker": true
   }
  ]
 },
 {
  "id": "norwoods_serpent_hollow",
  "name": "Norwoods — Serpent's Hollow",
  "bg": "bg_norwoods_serpent_hollow",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     1420,
     944
    ],
    [
     1400,
     890
    ],
    [
     1360,
     830
    ],
    [
     1310,
     790
    ],
    [
     1240,
     755
    ],
    [
     1170,
     735
    ],
    [
     1050,
     728
    ],
    [
     900,
     722
    ],
    [
     700,
     712
    ],
    [
     520,
     700
    ],
    [
     390,
     670
    ],
    [
     300,
     625
    ],
    [
     250,
     560
    ],
    [
     230,
     480
    ],
    [
     245,
     400
    ],
    [
     290,
     330
    ],
    [
     360,
     285
    ],
    [
     410,
     255
    ],
    [
     440,
     232
    ],
    [
     520,
     248
    ],
    [
     600,
     232
    ],
    [
     700,
     225
    ],
    [
     850,
     222
    ],
    [
     1000,
     225
    ],
    [
     1150,
     232
    ],
    [
     1260,
     260
    ],
    [
     1320,
     300
    ],
    [
     1345,
     370
    ],
    [
     1345,
     460
    ],
    [
     1330,
     560
    ],
    [
     1300,
     640
    ],
    [
     1300,
     690
    ],
    [
     1340,
     730
    ],
    [
     1400,
     770
    ],
    [
     1450,
     810
    ],
    [
     1490,
     860
    ],
    [
     1515,
     900
    ],
    [
     1535,
     944
    ]
   ]
  ],
  "block": [
   [
    [
     430,
     260
    ],
    [
     455,
     240
    ],
    [
     505,
     240
    ],
    [
     540,
     260
    ],
    [
     540,
     290
    ],
    [
     505,
     305
    ],
    [
     455,
     305
    ],
    [
     430,
     290
    ]
   ]
  ],
  "spawns": {
   "fromNorwoodsScorchedRoad": {
    "at": [
     1475,
     880
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     1420,
     930,
     115,
     14
    ],
    "to": "norwoods_scorched_road",
    "spawn": "fromNorwoodsSerpentHollow"
   }
  ],
  "scale": [
   0.36,
   0.5
  ],
  "music": "forest",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "serpent_bed",
    "at": [
     820,
     480
    ],
    "r": 120,
    "lines": [
     "* A great coil pressed into the earth, still warm under the ash.",
     "* Orochi slept here, long before anyone woke it."
    ]
   },
   {
    "id": "cold_camp",
    "at": [
     490,
     285
    ],
    "r": 70,
    "lines": [
     "* A cold fire ring. One bedroll, and two small blankets folded beside it.",
     "* The ashes are grey all through. Whoever camped here left days ago."
    ]
   },
   {
    "id": "split_tree",
    "at": [
     360,
     250
    ],
    "r": 60,
    "lines": [
     "* The trunk is split from crown to root. The wood inside is burned black, as if lightning had come from below."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     1418,
     660
    ],
    "r": 230,
    "color": 16752704,
    "flicker": true
   },
   {
    "at": [
     820,
     480
    ],
    "r": 260,
    "color": 7317759,
    "flicker": false
   }
  ]
 },
 {
  "id": "norwoods_mangal_roots",
  "name": "Norwoods — Roots of the Giant Mangal",
  "bg": "bg_norwoods_mangal_roots",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     0,
     944
    ],
    [
     340,
     944
    ],
    [
     380,
     900
    ],
    [
     470,
     850
    ],
    [
     560,
     780
    ],
    [
     640,
     720
    ],
    [
     740,
     670
    ],
    [
     860,
     640
    ],
    [
     1000,
     600
    ],
    [
     1150,
     575
    ],
    [
     1300,
     545
    ],
    [
     1420,
     520
    ],
    [
     1520,
     475
    ],
    [
     1600,
     440
    ],
    [
     1670,
     435
    ],
    [
     1670,
     362
    ],
    [
     1600,
     372
    ],
    [
     1500,
     410
    ],
    [
     1420,
     450
    ],
    [
     1300,
     488
    ],
    [
     1150,
     500
    ],
    [
     1010,
     512
    ],
    [
     960,
     545
    ],
    [
     880,
     585
    ],
    [
     840,
     580
    ],
    [
     860,
     545
    ],
    [
     880,
     480
    ],
    [
     830,
     440
    ],
    [
     815,
     410
    ],
    [
     800,
     330
    ],
    [
     795,
     220
    ],
    [
     790,
     120
    ],
    [
     795,
     10
    ],
    [
     695,
     10
    ],
    [
     705,
     120
    ],
    [
     708,
     220
    ],
    [
     710,
     320
    ],
    [
     730,
     420
    ],
    [
     760,
     470
    ],
    [
     775,
     560
    ],
    [
     740,
     600
    ],
    [
     640,
     640
    ],
    [
     540,
     670
    ],
    [
     420,
     720
    ],
    [
     300,
     770
    ],
    [
     180,
     820
    ],
    [
     60,
     870
    ],
    [
     0,
     880
    ]
   ]
  ],
  "block": [
   [
    [
     835,
     585
    ],
    [
     850,
     560
    ],
    [
     1000,
     505
    ],
    [
     1005,
     525
    ],
    [
     860,
     600
    ]
   ]
  ],
  "spawns": {
   "fromNorwoodsScorchedRoad": {
    "at": [
     170,
     895
    ],
    "dir": "up"
   },
   "fromGiantMangalF1": {
    "at": [
     748,
     70
    ],
    "dir": "down"
   },
   "fromSafarisRiverbank": {
    "at": [
     1610,
     405
    ],
    "dir": "left"
   },
   "candle": {
    "at": [
     815,
     590
    ],
    "dir": "left"
   }
  },
  "exits": [
   {
    "rect": [
     0,
     930,
     340,
     14
    ],
    "to": "norwoods_scorched_road",
    "spawn": "fromNorwoodsMangalRoots"
   },
   {
    "rect": [
     695,
     10,
     105,
     12
    ],
    "to": "giant_mangal_f1",
    "spawn": "fromNorwoodsMangalRoots"
   },
   {
    "rect": [
     1656,
     362,
     14,
     73
    ],
    "to": "safaris_riverbank",
    "spawn": "fromNorwoodsMangalRoots"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "forest",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "mangal_trunk",
    "at": [
     880,
     250
    ],
    "r": 90,
    "lines": [
     "* The Giant Mangal. Its crown is lost somewhere above the night.",
     "* Floor upon floor of hollowed wood. Hunters say it goes up eight."
    ]
   },
   {
    "id": "hunters_board",
    "at": [
     915,
     420
    ],
    "r": 75,
    "lines": [
     "* A notice from the Dundean hunters: \"Barbarian sighted again in the Giant Mangal. Do not climb alone.\"",
     "* Beneath it, fresh charcoal: \"Nor the Ashen one. He went east.\""
    ]
   },
   {
    "id": "barricade",
    "at": [
     925,
     550
    ],
    "r": 65,
    "lines": [
     "* The hunters' barricade has been shoved aside. One plank is split clean through."
    ]
   }
  ],
  "candles": [
   {
    "id": "norwoods_mangal_roots",
    "at": [
     785,
     560
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     650,
     85
    ],
    "r": 110,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     830,
     95
    ],
    "r": 110,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     663,
     440
    ],
    "r": 150,
    "color": 16769162,
    "flicker": true
   },
   {
    "at": [
     1530,
     150
    ],
    "r": 220,
    "color": 10471679,
    "flicker": false
   },
   {
    "at": [
     760,
     640
    ],
    "r": 240,
    "color": 16751178,
    "flicker": false
   }
  ]
 },
 {
  "id": "giant_mangal_f1",
  "name": "Giant Mangal — First Floor",
  "bg": "bg_giant_mangal_f1",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     790,
     225
    ],
    [
     930,
     225
    ],
    [
     950,
     280
    ],
    [
     985,
     330
    ],
    [
     1040,
     370
    ],
    [
     1075,
     410
    ],
    [
     1060,
     460
    ],
    [
     1000,
     500
    ],
    [
     930,
     530
    ],
    [
     890,
     570
    ],
    [
     880,
     620
    ],
    [
     905,
     670
    ],
    [
     945,
     720
    ],
    [
     950,
     770
    ],
    [
     935,
     815
    ],
    [
     925,
     860
    ],
    [
     925,
     944
    ],
    [
     775,
     944
    ],
    [
     775,
     860
    ],
    [
     770,
     815
    ],
    [
     790,
     780
    ],
    [
     760,
     730
    ],
    [
     720,
     690
    ],
    [
     640,
     665
    ],
    [
     530,
     655
    ],
    [
     500,
     625
    ],
    [
     560,
     600
    ],
    [
     680,
     560
    ],
    [
     740,
     520
    ],
    [
     810,
     490
    ],
    [
     900,
     470
    ],
    [
     960,
     440
    ],
    [
     970,
     410
    ],
    [
     920,
     370
    ],
    [
     860,
     330
    ],
    [
     820,
     290
    ]
   ]
  ],
  "block": [
   [
    [
     450,
     420
    ],
    [
     640,
     400
    ],
    [
     700,
     500
    ],
    [
     690,
     540
    ],
    [
     600,
     580
    ],
    [
     520,
     590
    ],
    [
     450,
     540
    ]
   ]
  ],
  "spawns": {
   "fromNorwoodsMangalRoots": {
    "at": [
     850,
     790
    ],
    "dir": "up"
   },
   "fromGiantMangalF2": {
    "at": [
     860,
     255
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     775,
     930,
     150,
     14
    ],
    "to": "norwoods_mangal_roots",
    "spawn": "fromGiantMangalF1"
   },
   {
    "rect": [
     790,
     0,
     140,
     232
    ],
    "to": "giant_mangal_f2",
    "spawn": "fromGiantMangalF1",
    "locked": "never",
    "lockedText": [
     "* The stair up is lashed shut with rope and timber.",
     "* Carved in the wood: \"Closed by order of the Dundean hunters. Ask at the lodge.\""
    ]
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "waystone",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "stair_barricade",
    "at": [
     853,
     190
    ],
    "r": 60,
    "lines": [
     "* The stair up is lashed shut with rope and timber.",
     "* Carved in the wood: \"Closed by order of the Dundean hunters. Ask at the lodge.\""
    ]
   },
   {
    "id": "dropped_spear",
    "at": [
     620,
     580
    ],
    "r": 60,
    "lines": [
     "* A hunter's spear, its haft snapped. There is no blood on it.",
     "* Whoever dropped it ran, and did not come back for it."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     180,
     250
    ],
    "r": 140,
    "color": 16756832,
    "flicker": true
   },
   {
    "at": [
     1415,
     220
    ],
    "r": 140,
    "color": 16756832,
    "flicker": true
   },
   {
    "at": [
     853,
     160
    ],
    "r": 160,
    "color": 16756832,
    "flicker": true
   },
   {
    "at": [
     850,
     880
    ],
    "r": 200,
    "color": 10471679,
    "flicker": false
   }
  ]
 },
 {
  "id": "mangal_east_road",
  "name": "Forest of Mangal — Eastern Road",
  "bg": "bg_mangal_east_road",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     760,
     944
    ],
    [
     770,
     860
    ],
    [
     790,
     760
    ],
    [
     790,
     680
    ],
    [
     775,
     640
    ],
    [
     745,
     560
    ],
    [
     745,
     540
    ],
    [
     785,
     500
    ],
    [
     805,
     450
    ],
    [
     845,
     400
    ],
    [
     895,
     350
    ],
    [
     925,
     300
    ],
    [
     890,
     230
    ],
    [
     895,
     180
    ],
    [
     905,
     120
    ],
    [
     960,
     50
    ],
    [
     995,
     0
    ],
    [
     1060,
     0
    ],
    [
     1040,
     50
    ],
    [
     1000,
     110
    ],
    [
     978,
     160
    ],
    [
     1000,
     210
    ],
    [
     1030,
     280
    ],
    [
     1030,
     310
    ],
    [
     1010,
     350
    ],
    [
     965,
     400
    ],
    [
     930,
     450
    ],
    [
     890,
     500
    ],
    [
     860,
     545
    ],
    [
     890,
     610
    ],
    [
     895,
     640
    ],
    [
     890,
     700
    ],
    [
     930,
     780
    ],
    [
     975,
     860
    ],
    [
     1000,
     944
    ]
   ]
  ],
  "block": [],
  "spawns": {
   "fromWaystone": {
    "at": [
     860,
     890
    ],
    "dir": "up"
   },
   "fromMangalCrossroads": {
    "at": [
     1025,
     40
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     760,
     932,
     240,
     12
    ],
    "to": "waystone",
    "spawn": "fromMangalEastRoad"
   },
   {
    "rect": [
     995,
     0,
     65,
     12
    ],
    "to": "mangal_crossroads",
    "spawn": "fromMangalEastRoad"
   }
  ],
  "scale": [
   0.28,
   0.5
  ],
  "music": "forest",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "milestone",
    "at": [
     715,
     790
    ],
    "r": 95,
    "lines": [
     "* A milestone. Under the moss, the old carving reads one word: MANGAL.",
     "* The other side has been scraped smooth."
    ]
   },
   {
    "id": "causeway",
    "at": [
     820,
     590
    ],
    "r": 60,
    "lines": [
     "* The planks are new. The posts under them are very old.",
     "* Something large moves beneath the water, then goes still."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     712,
     465
    ],
    "r": 140,
    "color": 16756832,
    "flicker": true
   },
   {
    "at": [
     985,
     142
    ],
    "r": 130,
    "color": 16756832,
    "flicker": true
   },
   {
    "at": [
     1170,
     400
    ],
    "r": 160,
    "color": 10471679,
    "flicker": false
   },
   {
    "at": [
     860,
     840
    ],
    "r": 220,
    "color": 16751178,
    "flicker": false
   }
  ]
 },
 {
  "id": "mangal_crossroads",
  "name": "Forest of Mangal — Crossroads",
  "bg": "bg_mangal_crossroads",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     235,
     0
    ],
    [
     335,
     0
    ],
    [
     390,
     90
    ],
    [
     450,
     180
    ],
    [
     515,
     250
    ],
    [
     590,
     305
    ],
    [
     700,
     325
    ],
    [
     860,
     330
    ],
    [
     950,
     315
    ],
    [
     995,
     250
    ],
    [
     1000,
     175
    ],
    [
     1115,
     175
    ],
    [
     1105,
     250
    ],
    [
     1090,
     320
    ],
    [
     1095,
     400
    ],
    [
     1140,
     480
    ],
    [
     1300,
     495
    ],
    [
     1450,
     505
    ],
    [
     1670,
     515
    ],
    [
     1670,
     592
    ],
    [
     1450,
     598
    ],
    [
     1300,
     585
    ],
    [
     1150,
     578
    ],
    [
     1000,
     600
    ],
    [
     920,
     618
    ],
    [
     850,
     645
    ],
    [
     795,
     700
    ],
    [
     760,
     800
    ],
    [
     722,
     944
    ],
    [
     572,
     944
    ],
    [
     585,
     800
    ],
    [
     565,
     690
    ],
    [
     520,
     615
    ],
    [
     400,
     575
    ],
    [
     320,
     545
    ],
    [
     345,
     500
    ],
    [
     450,
     480
    ],
    [
     475,
     420
    ],
    [
     445,
     360
    ],
    [
     405,
     290
    ],
    [
     350,
     200
    ],
    [
     290,
     100
    ]
   ]
  ],
  "block": [
   [
    [
     738,
     445
    ],
    [
     832,
     445
    ],
    [
     835,
     515
    ],
    [
     735,
     515
    ]
   ],
   [
    [
     852,
     470
    ],
    [
     880,
     470
    ],
    [
     880,
     492
    ],
    [
     852,
     492
    ]
   ],
   [
    [
     958,
     445
    ],
    [
     1000,
     445
    ],
    [
     1000,
     475
    ],
    [
     958,
     475
    ]
   ]
  ],
  "spawns": {
   "fromMangalEastRoad": {
    "at": [
     648,
     890
    ],
    "dir": "up"
   },
   "fromMangalBuildingSite": {
    "at": [
     295,
     55
    ],
    "dir": "down"
   },
   "fromRingfeldLowerRoad": {
    "at": [
     1055,
     215
    ],
    "dir": "down"
   },
   "fromSafarisGrassland": {
    "at": [
     1610,
     553
    ],
    "dir": "left"
   },
   "candle": {
    "at": [
     700,
     560
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     575,
     930,
     145,
     14
    ],
    "to": "mangal_east_road",
    "spawn": "fromMangalCrossroads"
   },
   {
    "rect": [
     238,
     0,
     95,
     12
    ],
    "to": "mangal_building_site",
    "spawn": "fromMangalCrossroads"
   },
   {
    "rect": [
     1002,
     175,
     110,
     14
    ],
    "to": "ringfeld_lower_road",
    "spawn": "fromMangalCrossroads",
    "locked": "never",
    "lockedText": [
     "* A fallen mangal trunk lies across the north road. Beyond it, the ground has slid into the ravine.",
     "* The road to Ringfeld is closed. For now."
    ]
   },
   {
    "rect": [
     1656,
     518,
     14,
     72
    ],
    "to": "safaris_grassland",
    "spawn": "fromMangalCrossroads"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "forest",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "signpost4",
    "at": [
     868,
     470
    ],
    "r": 55,
    "lines": [
     "* South: the Waystone. East: the Safaris, and Dundean. North: Ringfeld.",
     "* The fourth arm has been snapped off and left in the mud."
    ]
   },
   {
    "id": "fallen_trunk",
    "at": [
     1057,
     190
    ],
    "r": 70,
    "lines": [
     "* A mangal trunk has come down across the north road, and the ground beyond it has slid into the ravine.",
     "* A hunter's mark is cut into the bark: \"Ringfeld road. Clearing by spring.\""
    ]
   },
   {
    "id": "shrine",
    "at": [
     785,
     515
    ],
    "r": 65,
    "lines": [
     "* A low stone shrine. Travellers have left coins, dried flowers, a child's carved bird."
    ]
   }
  ],
  "candles": [
   {
    "id": "mangal_crossroads",
    "at": [
     700,
     525
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     943,
     378
    ],
    "r": 150,
    "color": 16757594,
    "flicker": true
   },
   {
    "at": [
     790,
     465
    ],
    "r": 110,
    "color": 16765066,
    "flicker": true
   },
   {
    "at": [
     800,
     540
    ],
    "r": 260,
    "color": 16751178,
    "flicker": false
   },
   {
    "at": [
     1520,
     620
    ],
    "r": 260,
    "color": 10475775,
    "flicker": false
   }
  ]
 },
 {
  "id": "mangal_building_site",
  "name": "Forest of Mangal — Abandoned Site",
  "bg": "bg_mangal_building_site",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     1140,
     944
    ],
    [
     1115,
     850
    ],
    [
     1080,
     760
    ],
    [
     1040,
     720
    ],
    [
     990,
     690
    ],
    [
     900,
     730
    ],
    [
     760,
     720
    ],
    [
     640,
     690
    ],
    [
     520,
     640
    ],
    [
     430,
     570
    ],
    [
     340,
     510
    ],
    [
     280,
     480
    ],
    [
     300,
     465
    ],
    [
     420,
     465
    ],
    [
     520,
     445
    ],
    [
     600,
     420
    ],
    [
     640,
     360
    ],
    [
     700,
     345
    ],
    [
     780,
     345
    ],
    [
     790,
     300
    ],
    [
     860,
     250
    ],
    [
     950,
     260
    ],
    [
     960,
     310
    ],
    [
     1010,
     350
    ],
    [
     1070,
     410
    ],
    [
     1150,
     425
    ],
    [
     1240,
     440
    ],
    [
     1250,
     520
    ],
    [
     1200,
     560
    ],
    [
     1180,
     620
    ],
    [
     1240,
     700
    ],
    [
     1330,
     800
    ],
    [
     1400,
     880
    ],
    [
     1440,
     944
    ]
   ]
  ],
  "block": [
   [
    [
     525,
     470
    ],
    [
     600,
     435
    ],
    [
     730,
     450
    ],
    [
     755,
     520
    ],
    [
     700,
     555
    ],
    [
     560,
     530
    ]
   ],
   [
    [
     780,
     465
    ],
    [
     845,
     460
    ],
    [
     845,
     505
    ],
    [
     785,
     505
    ]
   ],
   [
    [
     855,
     570
    ],
    [
     915,
     568
    ],
    [
     915,
     612
    ],
    [
     858,
     612
    ]
   ],
   [
    [
     520,
     650
    ],
    [
     578,
     648
    ],
    [
     578,
     700
    ],
    [
     522,
     700
    ]
   ],
   [
    [
     635,
     370
    ],
    [
     685,
     368
    ],
    [
     685,
     410
    ],
    [
     637,
     410
    ]
   ],
   [
    [
     851,
     245
    ],
    [
     874,
     245
    ],
    [
     876,
     348
    ],
    [
     845,
     348
    ]
   ],
   [
    [
     800,
     335
    ],
    [
     840,
     335
    ],
    [
     840,
     365
    ],
    [
     800,
     365
    ]
   ]
  ],
  "spawns": {
   "fromMangalCrossroads": {
    "at": [
     1290,
     870
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     1140,
     930,
     300,
     14
    ],
    "to": "mangal_crossroads",
    "spawn": "fromMangalBuildingSite"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "forest",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "timber_frame",
    "at": [
     905,
     290
    ],
    "r": 70,
    "lines": [
     "* A building frame, half raised. The ropes were cut, not frayed."
    ]
   },
   {
    "id": "torn_notice",
    "at": [
     885,
     600
    ],
    "r": 55,
    "lines": [
     "* A notice: \"This site was attacked by locals. Work halted. Breeders sent to clear the area have not returned.\"",
     "* Someone has scratched a name into the corner: Iris."
    ]
   },
   {
    "id": "cart",
    "at": [
     640,
     510
    ],
    "r": 90,
    "lines": [
     "* An overturned cart. The crates were broken open and emptied. Whatever was inside, someone wanted it."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     828,
     145
    ],
    "r": 200,
    "color": 16757594,
    "flicker": true
   },
   {
    "at": [
     860,
     300
    ],
    "r": 160,
    "color": 16751178,
    "flicker": false
   }
  ]
 },
 {
  "id": "safaris_grassland",
  "name": "Safaris — Western Grassland",
  "bg": "bg_safaris_grassland",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     0,
     408
    ],
    [
     200,
     410
    ],
    [
     400,
     414
    ],
    [
     600,
     418
    ],
    [
     700,
     424
    ],
    [
     800,
     438
    ],
    [
     1000,
     440
    ],
    [
     1200,
     438
    ],
    [
     1400,
     434
    ],
    [
     1670,
     430
    ],
    [
     1670,
     474
    ],
    [
     1400,
     484
    ],
    [
     1200,
     488
    ],
    [
     1000,
     490
    ],
    [
     820,
     490
    ],
    [
     800,
     520
    ],
    [
     780,
     600
    ],
    [
     755,
     700
    ],
    [
     730,
     800
    ],
    [
     712,
     880
    ],
    [
     710,
     944
    ],
    [
     596,
     944
    ],
    [
     600,
     880
    ],
    [
     620,
     800
    ],
    [
     650,
     700
    ],
    [
     690,
     600
    ],
    [
     740,
     520
    ],
    [
     745,
     496
    ],
    [
     700,
     470
    ],
    [
     600,
     460
    ],
    [
     400,
     456
    ],
    [
     200,
     454
    ],
    [
     0,
     452
    ]
   ]
  ],
  "block": [
   [
    [
     706,
     474
    ],
    [
     734,
     474
    ],
    [
     734,
     496
    ],
    [
     706,
     496
    ]
   ]
  ],
  "spawns": {
   "fromMangalCrossroads": {
    "at": [
     40,
     432
    ],
    "dir": "right"
   },
   "fromDundeanSquare": {
    "at": [
     1620,
     454
    ],
    "dir": "left"
   },
   "fromSafarisRiverbank": {
    "at": [
     655,
     890
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     0,
     412,
     12,
     40
    ],
    "to": "mangal_crossroads",
    "spawn": "fromSafarisGrassland"
   },
   {
    "rect": [
     1658,
     434,
     12,
     38
    ],
    "to": "dundean_square",
    "spawn": "fromSafarisGrassland"
   },
   {
    "rect": [
     598,
     930,
     112,
     14
    ],
    "to": "safaris_riverbank",
    "spawn": "fromSafarisGrassland"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "field",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "waymarker",
    "at": [
     728,
     445
    ],
    "r": 60,
    "lines": [
     "* A waymarker. East: Dundean. South: the river.",
     "* Its lantern is kept full. Someone in the village still cares who walks this road."
    ]
   },
   {
    "id": "hunters_blind",
    "at": [
     1105,
     400
    ],
    "r": 70,
    "lines": [
     "* A hunter's blind of woven reeds. Inside, a tally carved into a post: three marks, then a line struck through all of them."
    ]
   },
   {
    "id": "west_grove",
    "at": [
     1300,
     525
    ],
    "r": 80,
    "lines": [
     "* A small, twisted grove. The ground under it glints like wet iron.",
     "* Hunters keep their distance. Something heavy and slow lives here."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     744,
     415
    ],
    "r": 110,
    "color": 16756810,
    "flicker": true
   },
   {
    "at": [
     1520,
     95
    ],
    "r": 150,
    "color": 16760944,
    "flicker": false
   }
  ]
 },
 {
  "id": "safaris_riverbank",
  "name": "Safaris — River House",
  "bg": "bg_safaris_riverbank",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     640,
     0
    ],
    [
     712,
     0
    ],
    [
     745,
     50
    ],
    [
     800,
     100
    ],
    [
     815,
     150
    ],
    [
     805,
     185
    ],
    [
     780,
     215
    ],
    [
     772,
     250
    ],
    [
     778,
     300
    ],
    [
     772,
     350
    ],
    [
     775,
     392
    ],
    [
     700,
     410
    ],
    [
     640,
     380
    ],
    [
     680,
     340
    ],
    [
     712,
     300
    ],
    [
     712,
     250
    ],
    [
     722,
     205
    ],
    [
     745,
     165
    ],
    [
     735,
     120
    ],
    [
     700,
     80
    ],
    [
     652,
     40
    ]
   ],
   [
    [
     0,
     440
    ],
    [
     100,
     428
    ],
    [
     200,
     415
    ],
    [
     300,
     398
    ],
    [
     345,
     388
    ],
    [
     420,
     382
    ],
    [
     505,
     385
    ],
    [
     600,
     368
    ],
    [
     680,
     360
    ],
    [
     720,
     380
    ],
    [
     720,
     420
    ],
    [
     620,
     422
    ],
    [
     505,
     428
    ],
    [
     420,
     432
    ],
    [
     345,
     435
    ],
    [
     300,
     442
    ],
    [
     200,
     452
    ],
    [
     100,
     466
    ],
    [
     0,
     478
    ]
   ],
   [
    [
     680,
     385
    ],
    [
     760,
     395
    ],
    [
     850,
     425
    ],
    [
     920,
     450
    ],
    [
     980,
     470
    ],
    [
     1010,
     505
    ],
    [
     1060,
     535
    ],
    [
     1150,
     592
    ],
    [
     1152,
     612
    ],
    [
     1105,
     640
    ],
    [
     1080,
     622
    ],
    [
     1000,
     560
    ],
    [
     950,
     522
    ],
    [
     900,
     505
    ],
    [
     820,
     470
    ],
    [
     740,
     438
    ],
    [
     690,
     420
    ]
   ],
   [
    [
     970,
     470
    ],
    [
     1040,
     450
    ],
    [
     1075,
     438
    ],
    [
     1100,
     455
    ],
    [
     1060,
     480
    ],
    [
     1010,
     500
    ]
   ]
  ],
  "block": [],
  "spawns": {
   "fromSafarisGrassland": {
    "at": [
     676,
     45
    ],
    "dir": "down"
   },
   "fromNorwoodsMangalRoots": {
    "at": [
     40,
     456
    ],
    "dir": "right"
   }
  },
  "exits": [
   {
    "rect": [
     640,
     0,
     72,
     12
    ],
    "to": "safaris_grassland",
    "spawn": "fromSafarisRiverbank"
   },
   {
    "rect": [
     0,
     440,
     12,
     38
    ],
    "to": "norwoods_mangal_roots",
    "spawn": "fromSafarisRiverbank"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "field",
  "fireflies": 30,
  "npcs": [],
  "things": [
   {
    "id": "river_house",
    "at": [
     1065,
     430
    ],
    "r": 75,
    "lines": [
     "* A small house by the lake. The window is lit, but the door is barred from inside.",
     "* A voice through the boards: \"Go on to Dundean. I don't open after dark. Not this year.\""
    ]
   },
   {
    "id": "jetty",
    "at": [
     1085,
     595
    ],
    "r": 70,
    "lines": [
     "* A rowboat, tied fast. Its oars are gone.",
     "* Pale shapes turn slowly under the jetty, then sink away."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     1055,
     375
    ],
    "r": 140,
    "color": 16757322,
    "flicker": false
   },
   {
    "at": [
     1102,
     522
    ],
    "r": 130,
    "color": 16760928,
    "flicker": true
   },
   {
    "at": [
     1400,
     735
    ],
    "r": 160,
    "color": 12572927,
    "flicker": false
   }
  ]
 },
 {
  "id": "dundean_square",
  "name": "Dundean — Well Square",
  "bg": "bg_dundean_square",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     0,
     458
    ],
    [
     90,
     456
    ],
    [
     200,
     450
    ],
    [
     300,
     444
    ],
    [
     400,
     428
    ],
    [
     470,
     410
    ],
    [
     540,
     406
    ],
    [
     700,
     404
    ],
    [
     790,
     395
    ],
    [
     815,
     360
    ],
    [
     860,
     322
    ],
    [
     960,
     322
    ],
    [
     985,
     360
    ],
    [
     990,
     400
    ],
    [
     1010,
     418
    ],
    [
     1140,
     422
    ],
    [
     1200,
     428
    ],
    [
     1260,
     448
    ],
    [
     1350,
     458
    ],
    [
     1440,
     482
    ],
    [
     1520,
     496
    ],
    [
     1670,
     494
    ],
    [
     1670,
     562
    ],
    [
     1500,
     562
    ],
    [
     1400,
     552
    ],
    [
     1300,
     548
    ],
    [
     1230,
     556
    ],
    [
     1180,
     585
    ],
    [
     1140,
     620
    ],
    [
     1100,
     660
    ],
    [
     1050,
     688
    ],
    [
     950,
     694
    ],
    [
     820,
     692
    ],
    [
     720,
     690
    ],
    [
     650,
     684
    ],
    [
     560,
     686
    ],
    [
     520,
     668
    ],
    [
     505,
     630
    ],
    [
     480,
     575
    ],
    [
     470,
     545
    ],
    [
     400,
     530
    ],
    [
     300,
     530
    ],
    [
     300,
     512
    ],
    [
     292,
     503
    ],
    [
     228,
     503
    ],
    [
     218,
     527
    ],
    [
     200,
     527
    ],
    [
     90,
     526
    ],
    [
     0,
     526
    ]
   ]
  ],
  "block": [
   [
    [
     688,
     492
    ],
    [
     735,
     455
    ],
    [
     865,
     455
    ],
    [
     908,
     490
    ],
    [
     880,
     530
    ],
    [
     720,
     532
    ]
   ],
   [
    [
     918,
     582
    ],
    [
     940,
     548
    ],
    [
     1035,
     548
    ],
    [
     1062,
     585
    ],
    [
     1030,
     608
    ],
    [
     935,
     608
    ]
   ],
   [
    [
     480,
     585
    ],
    [
     500,
     585
    ],
    [
     500,
     606
    ],
    [
     480,
     606
    ]
   ],
   [
    [
     1126,
     628
    ],
    [
     1146,
     628
    ],
    [
     1146,
     650
    ],
    [
     1126,
     650
    ]
   ]
  ],
  "spawns": {
   "fromSafarisGrassland": {
    "at": [
     40,
     492
    ],
    "dir": "right"
   },
   "fromDundeanEastGate": {
    "at": [
     1625,
     528
    ],
    "dir": "left"
   },
   "candle": {
    "at": [
     950,
     650
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     0,
     458,
     12,
     68
    ],
    "to": "safaris_grassland",
    "spawn": "fromDundeanSquare"
   },
   {
    "rect": [
     1658,
     494,
     12,
     68
    ],
    "to": "dundean_east_gate",
    "spawn": "fromDundeanSquare"
   }
  ],
  "scale": [
   0.4,
   0.5
  ],
  "music": "town",
  "fireflies": 12,
  "npcs": [
   {
    "id": "edda",
    "at": [
     620,
     432
    ],
    "sprite": "innkeeper_idle",
    "name": "Old Edda",
    "portrait": "innkeeper_portrait"
   },
   {
    "id": "brann",
    "at": [
     1470,
     522
    ],
    "sprite": "hunter_idle",
    "name": "Brann",
    "portrait": "hunter_portrait"
   }
  ],
  "things": [
   {
    "id": "well",
    "at": [
     800,
     480
    ],
    "r": 85,
    "lines": [
     "* The Dundean well. The rope is new; the stones are worn hollow by hands.",
     "* The water is cold and clean."
    ]
   },
   {
    "id": "inn",
    "at": [
     640,
     415
    ],
    "r": 90,
    "lines": [
     "* The inn's door stands open. Smoke, bread, and low voices.",
     "* A few hunters drink in silence. Nobody laughs."
    ]
   },
   {
    "id": "lodge",
    "at": [
     1165,
     425
    ],
    "r": 75,
    "lines": [
     "* The hunters' lodge. A board by the door lists names. Several are crossed out in fresh ink.",
     "* At the top, a notice: \"Barbarian sighted again in the Giant Mangal.\""
    ]
   }
  ],
  "candles": [
   {
    "id": "dundean_square",
    "at": [
     1000,
     645
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     117,
     395
    ],
    "r": 120,
    "color": 16762992,
    "flicker": true
   },
   {
    "at": [
     1555,
     435
    ],
    "r": 120,
    "color": 16762992,
    "flicker": true
   },
   {
    "at": [
     520,
     545
    ],
    "r": 130,
    "color": 16762992,
    "flicker": true
   },
   {
    "at": [
     1112,
     595
    ],
    "r": 130,
    "color": 16762992,
    "flicker": true
   },
   {
    "at": [
     780,
     295
    ],
    "r": 110,
    "color": 16762992,
    "flicker": true
   },
   {
    "at": [
     493,
     342
    ],
    "r": 110,
    "color": 16762992,
    "flicker": true
   },
   {
    "at": [
     1113,
     340
    ],
    "r": 100,
    "color": 16762992,
    "flicker": true
   },
   {
    "at": [
     985,
     540
    ],
    "r": 90,
    "color": 16769162,
    "flicker": true
   }
  ]
 },
 {
  "id": "dundean_east_gate",
  "name": "Dundean — Valley Gate",
  "bg": "bg_dundean_east_gate",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     0,
     385
    ],
    [
     120,
     392
    ],
    [
     220,
     405
    ],
    [
     330,
     435
    ],
    [
     480,
     452
    ],
    [
     620,
     458
    ],
    [
     760,
     455
    ],
    [
     910,
     462
    ],
    [
     1100,
     482
    ],
    [
     1200,
     488
    ],
    [
     1400,
     492
    ],
    [
     1560,
     496
    ],
    [
     1670,
     500
    ],
    [
     1670,
     585
    ],
    [
     1500,
     582
    ],
    [
     1300,
     578
    ],
    [
     1100,
     565
    ],
    [
     900,
     550
    ],
    [
     700,
     545
    ],
    [
     500,
     530
    ],
    [
     300,
     515
    ],
    [
     150,
     495
    ],
    [
     0,
     478
    ]
   ]
  ],
  "block": [],
  "spawns": {
   "fromDundeanSquare": {
    "at": [
     45,
     435
    ],
    "dir": "right"
   },
   "fromSouthEarlsomeValley": {
    "at": [
     1620,
     542
    ],
    "dir": "left"
   }
  },
  "exits": [
   {
    "rect": [
     0,
     390,
     12,
     85
    ],
    "to": "dundean_square",
    "spawn": "fromDundeanEastGate"
   },
   {
    "rect": [
     1658,
     500,
     12,
     85
    ],
    "to": "south_earlsome_valley",
    "spawn": "fromDundeanEastGate",
    "locked": "never",
    "lockedText": [
     "* The valley gate is barred with a beam as thick as a man.",
     "* Chalked on it: \"Longdale road closed. A dragon guards the pass.\""
    ]
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "town",
  "fireflies": 12,
  "npcs": [],
  "things": [
   {
    "id": "barred_gate",
    "at": [
     1000,
     475
    ],
    "r": 60,
    "lines": [
     "* The valley gate is barred with a beam as thick as a man.",
     "* Chalked on it: \"Longdale road closed. A dragon guards the pass.\""
    ]
   },
   {
    "id": "watchtower",
    "at": [
     1200,
     490
    ],
    "r": 50,
    "lines": [
     "* The brazier on the tower burns all night. Down the valley, a red glow answers it from the cliffs."
    ]
   },
   {
    "id": "trough",
    "at": [
     655,
     460
    ],
    "r": 45,
    "lines": [
     "* Fresh hoofprints in the mud, heading east, from before the gate was barred.",
     "* Beside them, two sets of small boots."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     1120,
     78
    ],
    "r": 170,
    "color": 16747056,
    "flicker": true
   },
   {
    "at": [
     742,
     342
    ],
    "r": 110,
    "color": 16756816,
    "flicker": true
   },
   {
    "at": [
     118,
     240
    ],
    "r": 60,
    "color": 16756816,
    "flicker": false
   },
   {
    "at": [
     288,
     160
    ],
    "r": 45,
    "color": 16756816,
    "flicker": false
   }
  ]
 }
];

export const WAYSTONE_EXITS = {"topLeft": "norwoods_scorched_road", "topRight": "mangal_east_road", "topLeftSpawn": "fromWaystone", "topRightSpawn": "fromWaystone"};
export const WAYSTONE_SPAWNS: RoomDef["spawns"] = {"fromNorwoodsScorchedRoad": {"at": [190, 100], "dir": "down"}, "fromMangalEastRoad": {"at": [1490, 110], "dir": "down"}};

export const EXPANSION_STORY: {
  after_orochi_peace: StoryLine[];
  after_orochi_won: StoryLine[];
  room_entries: Record<string, StoryLine[]>;
  npc_dialogue: Record<string, { first: StoryLine[]; repeat: string[]; name: string; portrait: string }>;
  frontier_lines: string[];
  map_text_addendum: string;
} = {
 "after_orochi_peace": [
  {
   "speaker": "",
   "portrait": "none",
   "text": "Orochi lowers its eight heads and sinks back into the roots. The ash fades from the Waystone, and its old carvings glow again, faint and gold."
  },
  {
   "speaker": "",
   "portrait": "none",
   "text": "A pale light comes down through the trees. A celestial form, calm and silent, hangs above the fork."
  },
  {
   "speaker": "Divine",
   "portrait": "mon_divine",
   "text": "You showed mercy where you had every reason to show none. That is rarer than strength."
  },
  {
   "speaker": "Divine",
   "portrait": "mon_divine",
   "text": "The one you hunt did not break the Overlord's sleep by force. He bargained with it. Remember that. He makes bargains."
  },
  {
   "speaker": "Divine",
   "portrait": "mon_divine",
   "text": "Your sister and brother live. He took them up the high roads. Both roads meet again in the Safaris. Look for them there, near Dundean."
  },
  {
   "speaker": "",
   "portrait": "none",
   "text": "At the foot of the Waystone lies a small blue ribbon. Lira's. It is tied in a careful knot, like a signal."
  },
  {
   "speaker": "Kael",
   "portrait": "hero_portrait",
   "text": "She left this for me. She knew I would come."
  },
  {
   "speaker": "Divine",
   "portrait": "mon_divine",
   "text": "Then do not keep her waiting. This is only the first of many roads, and he does not rest."
  },
  {
   "speaker": "",
   "portrait": "none",
   "text": "The light fades. Beyond the Waystone, the two roads leading up and away are clear now. The forest lets him pass."
  }
 ],
 "after_orochi_won": [
  {
   "speaker": "",
   "portrait": "none",
   "text": "Orochi falls, and the forest goes silent. The Waystone stays dark, the ash handprint still burned into its face."
  },
  {
   "speaker": "",
   "portrait": "none",
   "text": "In the ash at its foot lies a small blue ribbon. Lira's. It is tied in a careful knot and points up the high roads."
  },
  {
   "speaker": "Kael",
   "portrait": "hero_portrait",
   "text": "She left this for me. She is still alive. They both are."
  },
  {
   "speaker": "",
   "portrait": "none",
   "text": "With the serpent gone, the two roads above the fork lie open. Far off, a thin line of grey smoke drifts toward the Safaris."
  },
  {
   "speaker": "Kael",
   "portrait": "hero_portrait",
   "text": "I am coming. However far you take them."
  }
 ],
 "room_entries": {
  "norwoods_scorched_road": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The road is scorched in long black furrows, as if something hot was dragged along it. The trail lantern at the fork has burned out."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "In the soft earth at the edge of the burn, Kael finds two sets of small footprints. They walk close together."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "They were walking, not carried. He made them walk all this way."
   }
  ],
  "norwoods_serpent_hollow": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The ground sinks into a great coiled hollow where Orochi slept. Above it, under a split tree, the remains of a camp. The fire was put out with ash, not water."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Two small hollows have been pressed into the moss beside the cold fire. Lira and Tobin slept here, or tried to."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "He waited here while it woke. He wanted to watch it come for whoever followed."
   }
  ],
  "norwoods_mangal_roots": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The Giant Mangal rises above the canopy, older than any tree Kael has seen. Its roots are as thick as houses."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "A notice from the Dundean hunters is nailed to the board: GIANT MANGAL CLOSED. BARBARIAN SIGHTED ON THE UPPER FLOORS. BY ORDER OF THE LODGE."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "The barricade at the root door has been pushed aside, just far enough for a man to pass. The edges of the planks are grey with ash."
   }
  ],
  "mangal_crossroads": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "At the shrine, every candle has gone out. The wax is still soft. Someone pinched them out one by one."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "A fallen mangal trunk lies across the north road. Beyond it, the earth has slid away into a ravine."
   }
  ],
  "safaris_riverbank": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The small house by the river stands empty. On the jetty, half under a plank, lies a little carved wooden dragon."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Tobin's. I carved this for him last winter. He never lets it out of his hand."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Kael puts it in his coat, beside the ribbon. The river runs on, quiet and cold."
   }
  ],
  "dundean_square": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "Dundean is quiet. Shutters are closed in daylight, and the hunters at the lodge door watch the road with their hands on their weapons."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Halvard said to ask here first. Someone must have seen them."
   }
  ]
 },
 "npc_dialogue": {
  "edda": {
   "first": [
    {
     "speaker": "Old Edda",
     "portrait": "innkeeper_portrait",
     "text": "Dun ar, open road. You came in from the Norwoods? On foot, at your age? Sit down before you fall down."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "I am looking for a man covered in grey ash. He has two children with him. A girl and a boy. My sister and brother."
    },
    {
     "speaker": "Old Edda",
     "portrait": "innkeeper_portrait",
     "text": "...Then you have had a worse night than any of us. Brann at the valley gate saw something at first light. Talk to him. He will not lie to you."
    },
    {
     "speaker": "Old Edda",
     "portrait": "innkeeper_portrait",
     "text": "The lodge has barred the Giant Mangal stair and the east valley gate. Only the hunters can lift those bars, and they do not do it lightly."
    },
    {
     "speaker": "Old Edda",
     "portrait": "innkeeper_portrait",
     "text": "There is a bed here if you need it. No questions, no coin. Whatever you are walking into, you will not do it well half asleep."
    }
   ],
   "repeat": [
    "The grass hears. Keep your voice low on the roads, boy. The Safaris are not as empty as they look.",
    "The hunters lift the barricades when they judge it safe. Not before. Arguing with the lodge has never moved a bar in this town.",
    "Eat something. I have buried hunters braver than you who forgot to."
   ],
   "name": "Old Edda",
   "portrait": "innkeeper_portrait"
  },
  "brann": {
   "first": [
    {
     "speaker": "Brann",
     "portrait": "hunter_portrait",
     "text": "Dun ar. Stay back from the gate. ...You have the look of someone chasing something."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "A man in grey ash, with two children. Did he come through here?"
    },
    {
     "speaker": "Brann",
     "portrait": "hunter_portrait",
     "text": "At first light, across the Safaris. Grey, like a burnt-out fire walking. A girl at his side, and a small boy who kept looking back."
    },
    {
     "speaker": "Brann",
     "portrait": "hunter_portrait",
     "text": "He took the valley road east, toward Longdale. Past it, there is a dragon guarding the passway. That is why I barred the gate behind him."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "The boy kept looking back. He was looking for me."
    },
    {
     "speaker": "Brann",
     "portrait": "hunter_portrait",
     "text": "I am sorry. I had three hunters with me and none of us moved. That gate stays shut until the lodge says otherwise. I will not send a boy to die."
    }
   ],
   "repeat": [
    "The valley road runs east to Longdale. Past that, the dragon on the passway. Nobody walks it alone.",
    "He did not hurry. That frightened me most. He walked like he knew nothing in the Safaris could stop him.",
    "Show the lodge you can survive out there, and maybe they will lift the bar. Until then, I keep this gate."
   ],
   "name": "Brann",
   "portrait": "hunter_portrait"
  }
 },
 "frontier_lines": [
  "The stair to the second floor of the Giant Mangal is barred with lashed spears. A lodge mark is cut into the wood: BARBARIAN ALERT. NO PASSAGE ABOVE THE FIRST FLOOR.",
  "Seven more floors rise above this one, and something on the upper floors has made the Dundean hunters afraid. The way up will have to wait for now.",
  "The north road to Ringfeld is buried under a fallen mangal trunk. Beyond it, the earth has slid into a ravine. No one is getting through this way yet.",
  "Past the ravine, the road goes on toward Ringfeld and the sea. It will be cleared one day. Not today.",
  "The valley gate is barred from the inside. Brann's mark is on the bar. The road beyond runs east toward Longdale, and the dragon that guards the passway.",
  "He took them this way. Kael presses his hand to the cold wood. Not yet. But soon."
 ],
 "map_text_addendum": "Beyond the Waystone fork, two high roads climb out of the hollow. The left road crosses the scorched part of the Norwoods, past Serpent's Hollow where Orochi slept, to the roots of the Giant Mangal. The dungeon rises eight floors, but the Dundean hunters have barred it above the first. The right road winds into the Forest of Mangal, past an abandoned building site, to a crossroads whose north road to Ringfeld is blocked by a fallen trunk. The two roads meet again in the Safaris, open grassland cut by a river, with a small house on its bank. Dundean stands at the heart of the Safaris. From its valley gate, a road runs east toward Longdale in South Earlsome. The hunters say a dragon guards the passway there. The map does not end here. It has only been drawn this far."
};

export const EXPANSION_NPC_SHEETS: string[] = ["hunter", "innkeeper"];
