// GENERATED by tools/gen_missions.py: the Dundean missions (graveyard blood rite, wind priests' cult).
import type { RoomDef } from './rooms';
import type { MissionData } from './missionTypes';

export const MISSION_ROOMS: RoomDef[] = [
 {
  "id": "east_valley_road",
  "name": "East Valley — Longdale Road",
  "bg": "bg_east_valley_road",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     0,
     450
    ],
    [
     300,
     452
    ],
    [
     600,
     446
    ],
    [
     800,
     436
    ],
    [
     900,
     428
    ],
    [
     1000,
     414
    ],
    [
     1100,
     396
    ],
    [
     1150,
     372
    ],
    [
     1200,
     334
    ],
    [
     1250,
     310
    ],
    [
     1285,
     284
    ],
    [
     1300,
     266
    ],
    [
     1440,
     266
    ],
    [
     1425,
     295
    ],
    [
     1400,
     322
    ],
    [
     1350,
     350
    ],
    [
     1300,
     378
    ],
    [
     1250,
     394
    ],
    [
     1200,
     410
    ],
    [
     1150,
     436
    ],
    [
     1100,
     450
    ],
    [
     1050,
     462
    ],
    [
     1000,
     470
    ],
    [
     950,
     480
    ],
    [
     920,
     490
    ],
    [
     880,
     498
    ],
    [
     800,
     504
    ],
    [
     600,
     510
    ],
    [
     300,
     512
    ],
    [
     0,
     506
    ]
   ],
   [
    [
     858,
     486
    ],
    [
     922,
     486
    ],
    [
     935,
     560
    ],
    [
     940,
     620
    ],
    [
     928,
     680
    ],
    [
     905,
     740
    ],
    [
     900,
     820
    ],
    [
     898,
     880
    ],
    [
     890,
     944
    ],
    [
     805,
     944
    ],
    [
     810,
     850
    ],
    [
     830,
     800
    ],
    [
     838,
     740
    ],
    [
     866,
     680
    ],
    [
     870,
     620
    ],
    [
     862,
     560
    ]
   ]
  ],
  "block": [
   [
    [
     810,
     462
    ],
    [
     832,
     462
    ],
    [
     832,
     506
    ],
    [
     810,
     506
    ]
   ]
  ],
  "spawns": {
   "fromDundeanEastGate": {
    "at": [
     45,
     472
    ],
    "dir": "right"
   },
   "fromGraveyardGate": {
    "at": [
     846,
     895
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     0,
     440,
     12,
     65
    ],
    "to": "dundean_east_gate",
    "spawn": "fromEastValleyRoad"
   },
   {
    "rect": [
     805,
     932,
     85,
     12
    ],
    "to": "graveyard_gate",
    "spawn": "fromEastValleyRoad"
   },
   {
    "rect": [
     1300,
     262,
     150,
     14
    ],
    "to": "south_earlsome_valley",
    "spawn": "fromEastValleyRoad",
    "locked": "never",
    "lockedText": [
     "* A pine lies across the valley road. Felled, not fallen. Brann's mark is cut into the trunk.",
     "* Beyond it the road climbs toward the red glow in the cliffs. The hunters closed it. Not tonight."
    ]
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "field",
  "fireflies": 18,
  "npcs": [],
  "things": [
   {
    "id": "waymarker",
    "at": [
     825,
     500
    ],
    "r": 45,
    "lines": [
     "* A waymarker. The east arm is carved LONGDALE. The south arm has been cut away.",
     "* Someone has scratched a circle into the stump of it, and filled the circle in with something dark."
    ]
   },
   {
    "id": "felled_pine",
    "at": [
     1375,
     282
    ],
    "r": 60,
    "lines": [
     "* A pine lies across the valley road. Felled, not fallen. Brann's mark is cut into the trunk.",
     "* Beyond it the road climbs toward the red glow in the cliffs. The hunters closed it. Not tonight."
    ]
   },
   {
    "id": "boot_prints",
    "at": [
     895,
     690
    ],
    "r": 70,
    "lines": [
     "* Many feet have gone down the south track. Bare feet, and boots, and something dragged.",
     "* None of the tracks come back up."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     845,
     492
    ],
    "r": 190,
    "color": 16756816,
    "flicker": true
   }
  ],
  "triggers": []
 },
 {
  "id": "graveyard_gate",
  "name": "Old Graveyard — Lichgate",
  "bg": "bg_graveyard_gate",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     800,
     0
    ],
    [
     910,
     0
    ],
    [
     905,
     70
    ],
    [
     905,
     150
    ],
    [
     905,
     268
    ],
    [
     960,
     272
    ],
    [
     992,
     290
    ],
    [
     1000,
     340
    ],
    [
     1010,
     400
    ],
    [
     1100,
     410
    ],
    [
     1300,
     416
    ],
    [
     1500,
     424
    ],
    [
     1670,
     430
    ],
    [
     1670,
     515
    ],
    [
     1500,
     510
    ],
    [
     1300,
     505
    ],
    [
     1150,
     500
    ],
    [
     1000,
     505
    ],
    [
     880,
     510
    ],
    [
     810,
     508
    ],
    [
     848,
     590
    ],
    [
     845,
     700
    ],
    [
     760,
     728
    ],
    [
     620,
     728
    ],
    [
     500,
     712
    ],
    [
     455,
     690
    ],
    [
     452,
     640
    ],
    [
     520,
     612
    ],
    [
     640,
     600
    ],
    [
     690,
     540
    ],
    [
     705,
     500
    ],
    [
     700,
     450
    ],
    [
     742,
     400
    ],
    [
     752,
     300
    ],
    [
     765,
     275
    ],
    [
     830,
     268
    ],
    [
     830,
     150
    ],
    [
     830,
     70
    ]
   ]
  ],
  "block": [
   [
    [
     703,
     238
    ],
    [
     733,
     238
    ],
    [
     733,
     292
    ],
    [
     703,
     292
    ]
   ],
   [
    [
     982,
     238
    ],
    [
     1012,
     238
    ],
    [
     1012,
     292
    ],
    [
     982,
     292
    ]
   ],
   [
    [
     682,
     562
    ],
    [
     738,
     562
    ],
    [
     738,
     622
    ],
    [
     682,
     622
    ]
   ]
  ],
  "spawns": {
   "fromEastValleyRoad": {
    "at": [
     855,
     40
    ],
    "dir": "down"
   },
   "fromGraveyardRows": {
    "at": [
     1625,
     470
    ],
    "dir": "left"
   }
  },
  "exits": [
   {
    "rect": [
     795,
     0,
     120,
     12
    ],
    "to": "east_valley_road",
    "spawn": "fromGraveyardGate"
   },
   {
    "rect": [
     1658,
     428,
     12,
     88
    ],
    "to": "graveyard_rows",
    "spawn": "fromGraveyardGate"
   }
  ],
  "scale": [
   0.32,
   0.5
  ],
  "music": "forest",
  "fireflies": 18,
  "npcs": [],
  "things": [
   {
    "id": "lichgate",
    "at": [
     867,
     235
    ],
    "r": 60,
    "lines": [
     "* The lichgate's chain has been cut. A cloth is tied to the post, stiff and brown.",
     "* The braziers inside are new. Someone keeps them fed."
    ]
   },
   {
    "id": "sealed_crypt",
    "at": [
     480,
     670
    ],
    "r": 75,
    "lines": [
     "* An old family crypt. The names on the lintel have been chiselled off.",
     "* Fresh mortar seals the door. From inside, nothing at all."
    ]
   },
   {
    "id": "headstones",
    "at": [
     1330,
     520
    ],
    "r": 60,
    "lines": [
     "* Dundean names. Generations of hunters, laid in rows.",
     "* Several graves have been opened, and filled again badly."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     718,
     250
    ],
    "r": 150,
    "color": 16734762,
    "flicker": true
   },
   {
    "at": [
     997,
     250
    ],
    "r": 150,
    "color": 16734762,
    "flicker": true
   }
  ],
  "triggers": [
   {
    "id": "m:blood_rite_lichgate",
    "rect": [
     700,
     290,
     320,
     220
    ],
    "once": "fight_blood_rite_lichgate",
    "requires": "quest_blood"
   }
  ]
 },
 {
  "id": "graveyard_rows",
  "name": "Old Graveyard — Crypt Rows",
  "bg": "bg_graveyard_rows",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     0,
     555
    ],
    [
     100,
     558
    ],
    [
     150,
     585
    ],
    [
     250,
     605
    ],
    [
     330,
     640
    ],
    [
     400,
     648
    ],
    [
     470,
     650
    ],
    [
     545,
     640
    ],
    [
     548,
     565
    ],
    [
     610,
     560
    ],
    [
     650,
     585
    ],
    [
     700,
     600
    ],
    [
     740,
     570
    ],
    [
     800,
     560
    ],
    [
     900,
     575
    ],
    [
     1030,
     600
    ],
    [
     1080,
     615
    ],
    [
     1150,
     610
    ],
    [
     1200,
     600
    ],
    [
     1250,
     565
    ],
    [
     1300,
     520
    ],
    [
     1305,
     430
    ],
    [
     1315,
     330
    ],
    [
     1318,
     200
    ],
    [
     1325,
     80
    ],
    [
     1330,
     0
    ],
    [
     1405,
     0
    ],
    [
     1410,
     80
    ],
    [
     1418,
     200
    ],
    [
     1425,
     330
    ],
    [
     1440,
     430
    ],
    [
     1450,
     500
    ],
    [
     1410,
     550
    ],
    [
     1350,
     600
    ],
    [
     1300,
     615
    ],
    [
     1240,
     645
    ],
    [
     1200,
     680
    ],
    [
     1100,
     705
    ],
    [
     1050,
     715
    ],
    [
     965,
     720
    ],
    [
     940,
     760
    ],
    [
     880,
     790
    ],
    [
     760,
     795
    ],
    [
     600,
     780
    ],
    [
     500,
     750
    ],
    [
     455,
     740
    ],
    [
     400,
     745
    ],
    [
     330,
     705
    ],
    [
     250,
     700
    ],
    [
     160,
     690
    ],
    [
     90,
     655
    ],
    [
     0,
     648
    ]
   ]
  ],
  "block": [
   [
    [
     495,
     640
    ],
    [
     600,
     645
    ],
    [
     612,
     700
    ],
    [
     585,
     725
    ],
    [
     520,
     722
    ],
    [
     495,
     690
    ]
   ],
   [
    [
     405,
     575
    ],
    [
     460,
     575
    ],
    [
     460,
     600
    ],
    [
     405,
     600
    ]
   ],
   [
    [
     500,
     592
    ],
    [
     542,
     592
    ],
    [
     542,
     618
    ],
    [
     500,
     618
    ]
   ],
   [
    [
     880,
     585
    ],
    [
     1030,
     585
    ],
    [
     1030,
     645
    ],
    [
     880,
     645
    ]
   ],
   [
    [
     965,
     690
    ],
    [
     1035,
     690
    ],
    [
     1035,
     722
    ],
    [
     965,
     722
    ]
   ],
   [
    [
     1025,
     570
    ],
    [
     1080,
     570
    ],
    [
     1080,
     610
    ],
    [
     1025,
     610
    ]
   ],
   [
    [
     865,
     625
    ],
    [
     902,
     625
    ],
    [
     902,
     652
    ],
    [
     865,
     652
    ]
   ],
   [
    [
     1352,
     605
    ],
    [
     1398,
     605
    ],
    [
     1398,
     642
    ],
    [
     1352,
     642
    ]
   ]
  ],
  "spawns": {
   "fromGraveyardGate": {
    "at": [
     40,
     600
    ],
    "dir": "right"
   },
   "fromGraveyardRitualCircle": {
    "at": [
     1365,
     60
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     0,
     560,
     12,
     80
    ],
    "to": "graveyard_gate",
    "spawn": "fromGraveyardRows"
   },
   {
    "rect": [
     1320,
     0,
     100,
     12
    ],
    "to": "graveyard_ritual_circle",
    "spawn": "fromGraveyardRows"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "forest",
  "fireflies": 18,
  "npcs": [],
  "things": [
   {
    "id": "open_crypt",
    "at": [
     578,
     585
    ],
    "r": 45,
    "lines": [
     "* The crypt is empty. The stone shelves have been swept clean of bones.",
     "* On the floor, a circle drawn in something that has dried black."
    ]
   },
   {
    "id": "red_cloths",
    "at": [
     705,
     625
    ],
    "r": 45,
    "lines": [
     "* Strips of red cloth tied to every branch. Dozens. Each has a knot for a name.",
     "* The wind moves them. The sound is like breathing."
    ]
   },
   {
    "id": "steps",
    "at": [
     1365,
     470
    ],
    "r": 50,
    "lines": [
     "* Chanting comes down the steps, low and steady. More than a dozen voices.",
     "* The red light above does not flicker like fire should."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     1250,
     95
    ],
    "r": 120,
    "color": 16734778,
    "flicker": true
   },
   {
    "at": [
     1440,
     95
    ],
    "r": 120,
    "color": 16734778,
    "flicker": true
   },
   {
    "at": [
     1270,
     218
    ],
    "r": 120,
    "color": 16734778,
    "flicker": true
   },
   {
    "at": [
     1445,
     218
    ],
    "r": 120,
    "color": 16734778,
    "flicker": true
   },
   {
    "at": [
     1318,
     350
    ],
    "r": 120,
    "color": 16734778,
    "flicker": true
   },
   {
    "at": [
     1448,
     330
    ],
    "r": 120,
    "color": 16734778,
    "flicker": true
   }
  ],
  "triggers": [
   {
    "id": "m:blood_rite_rows",
    "rect": [
     460,
     470,
     340,
     340
    ],
    "once": "fight_blood_rite_rows",
    "requires": "quest_blood"
   }
  ]
 },
 {
  "id": "graveyard_ritual_circle",
  "name": "Old Graveyard — The Blood Circle",
  "bg": "bg_graveyard_ritual_circle",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     885,
     944
    ],
    [
     872,
     745
    ],
    [
     880,
     700
    ],
    [
     820,
     650
    ],
    [
     780,
     600
    ],
    [
     760,
     560
    ],
    [
     740,
     545
    ],
    [
     705,
     420
    ],
    [
     640,
     440
    ],
    [
     565,
     455
    ],
    [
     555,
     395
    ],
    [
     470,
     375
    ],
    [
     420,
     305
    ],
    [
     520,
     285
    ],
    [
     580,
     300
    ],
    [
     600,
     230
    ],
    [
     690,
     210
    ],
    [
     712,
     195
    ],
    [
     715,
     150
    ],
    [
     950,
     150
    ],
    [
     960,
     200
    ],
    [
     1040,
     215
    ],
    [
     1040,
     295
    ],
    [
     1120,
     300
    ],
    [
     1215,
     330
    ],
    [
     1210,
     385
    ],
    [
     1120,
     395
    ],
    [
     1110,
     470
    ],
    [
     1040,
     460
    ],
    [
     1030,
     425
    ],
    [
     955,
     430
    ],
    [
     950,
     555
    ],
    [
     990,
     585
    ],
    [
     1005,
     650
    ],
    [
     1010,
     700
    ],
    [
     1065,
     745
    ],
    [
     1095,
     944
    ]
   ]
  ],
  "block": [
   [
    [
     720,
     55
    ],
    [
     945,
     55
    ],
    [
     940,
     140
    ],
    [
     725,
     140
    ]
   ],
   [
    [
     800,
     595
    ],
    [
     890,
     595
    ],
    [
     895,
     635
    ],
    [
     790,
     635
    ]
   ],
   [
    [
     605,
     265
    ],
    [
     645,
     265
    ],
    [
     640,
     295
    ],
    [
     610,
     295
    ]
   ],
   [
    [
     1005,
     265
    ],
    [
     1045,
     265
    ],
    [
     1040,
     295
    ],
    [
     1010,
     295
    ]
   ],
   [
    [
     1170,
     335
    ],
    [
     1210,
     335
    ],
    [
     1205,
     365
    ],
    [
     1175,
     365
    ]
   ],
   [
    [
     1070,
     485
    ],
    [
     1110,
     485
    ],
    [
     1105,
     515
    ],
    [
     1075,
     515
    ]
   ],
   [
    [
     728,
     515
    ],
    [
     772,
     515
    ],
    [
     770,
     545
    ],
    [
     735,
     545
    ]
   ],
   [
    [
     425,
     340
    ],
    [
     465,
     340
    ],
    [
     462,
     370
    ],
    [
     430,
     370
    ]
   ]
  ],
  "spawns": {
   "fromGraveyardRows": {
    "at": [
     1000,
     900
    ],
    "dir": "up"
   },
   "candle": {
    "at": [
     830,
     268
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     900,
     932,
     200,
     12
    ],
    "to": "graveyard_rows",
    "spawn": "fromGraveyardRitualCircle"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "waystone",
  "fireflies": 18,
  "npcs": [],
  "things": [
   {
    "id": "standing_stones",
    "at": [
     835,
     390
    ],
    "r": 110,
    "lines": [
     "* The stones are older than Dundean. Older than the graves around them.",
     "* Fresh handprints in red climb every one of them, all facing the altar."
    ]
   },
   {
    "id": "altar",
    "at": [
     832,
     150
    ],
    "r": 70,
    "lines": [
     "* The altar is stained to the depth of a finger. This rite has been fed for a long time.",
     "* Under the slab, wrapped in oilcloth: a torn page of a formula, written in a careful hand.",
     "* FORMULA FRAGMENT (BLOOD) obtained. Half of a combination: Blood Rogue, and something of the wind. The rest is missing."
    ]
   },
   {
    "id": "rest_stone",
    "at": [
     845,
     615
    ],
    "r": 60,
    "lines": [
     "* A flat stone at the foot of the ring, worn smooth by those who knelt here before going up.",
     "* Beyond it, the braziers. Someone is chanting inside the circle."
    ]
   }
  ],
  "candles": [
   {
    "id": "graveyard_ritual_circle",
    "at": [
     870,
     250
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     705,
     75
    ],
    "r": 120,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     960,
     75
    ],
    "r": 120,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     625,
     265
    ],
    "r": 100,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     1025,
     265
    ],
    "r": 100,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     445,
     340
    ],
    "r": 100,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     1190,
     335
    ],
    "r": 100,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     575,
     485
    ],
    "r": 100,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     1090,
     485
    ],
    "r": 100,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     750,
     515
    ],
    "r": 100,
    "color": 16730666,
    "flicker": true
   },
   {
    "at": [
     140,
     125
    ],
    "r": 160,
    "color": 10467552,
    "flicker": false
   }
  ],
  "triggers": [
   {
    "id": "m:blood_rite_circle",
    "rect": [
     650,
     430,
     370,
     200
    ],
    "once": "fight_blood_rite_circle",
    "requires": "quest_blood"
   },
   {
    "id": "m:blood_rite_altar",
    "rect": [
     705,
     130,
     260,
     90
    ],
    "once": "fight_blood_rite_altar",
    "requires": "quest_blood"
   }
  ]
 },
 {
  "id": "safaris_far_shore",
  "name": "Safaris — Far Shore",
  "bg": "bg_safaris_far_shore",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     427,
     944
    ],
    [
     427,
     700
    ],
    [
     430,
     680
    ],
    [
     520,
     665
    ],
    [
     565,
     625
    ],
    [
     600,
     560
    ],
    [
     650,
     500
    ],
    [
     710,
     450
    ],
    [
     780,
     400
    ],
    [
     860,
     350
    ],
    [
     940,
     300
    ],
    [
     1010,
     250
    ],
    [
     1060,
     200
    ],
    [
     1090,
     150
    ],
    [
     1095,
     90
    ],
    [
     1085,
     40
    ],
    [
     1090,
     0
    ],
    [
     1165,
     0
    ],
    [
     1165,
     50
    ],
    [
     1190,
     100
    ],
    [
     1195,
     160
    ],
    [
     1205,
     215
    ],
    [
     1185,
     255
    ],
    [
     1120,
     300
    ],
    [
     1010,
     360
    ],
    [
     940,
     410
    ],
    [
     850,
     460
    ],
    [
     790,
     510
    ],
    [
     740,
     570
    ],
    [
     690,
     630
    ],
    [
     640,
     680
    ],
    [
     560,
     700
    ],
    [
     500,
     705
    ],
    [
     500,
     944
    ]
   ]
  ],
  "block": [
   [
    [
     560,
     598
    ],
    [
     592,
     598
    ],
    [
     592,
     622
    ],
    [
     560,
     622
    ]
   ],
   [
    [
     650,
     474
    ],
    [
     672,
     474
    ],
    [
     672,
     494
    ],
    [
     650,
     494
    ]
   ],
   [
    [
     806,
     374
    ],
    [
     828,
     374
    ],
    [
     828,
     394
    ],
    [
     806,
     394
    ]
   ],
   [
    [
     1058,
     260
    ],
    [
     1082,
     260
    ],
    [
     1082,
     280
    ],
    [
     1058,
     280
    ]
   ],
   [
    [
     1150,
     182
    ],
    [
     1172,
     182
    ],
    [
     1172,
     200
    ],
    [
     1150,
     200
    ]
   ]
  ],
  "spawns": {
   "fromSafarisRiverbank": {
    "at": [
     462,
     890
    ],
    "dir": "up"
   },
   "fromWindCultTerraces": {
    "at": [
     1125,
     45
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     420,
     932,
     85,
     12
    ],
    "to": "safaris_riverbank",
    "spawn": "fromSafarisFarShore"
   },
   {
    "rect": [
     1095,
     0,
     70,
     12
    ],
    "to": "wind_cult_terraces",
    "spawn": "fromSafarisFarShore"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "field",
  "fireflies": 18,
  "npcs": [],
  "things": [
   {
    "id": "banner_poles",
    "at": [
     730,
     440
    ],
    "r": 75,
    "lines": [
     "* Prayer banners, faded to the colour of bone. The words on them have been worn off by the wind.",
     "* They all point the same way. Uphill."
    ]
   },
   {
    "id": "landing",
    "at": [
     462,
     760
    ],
    "r": 60,
    "lines": [
     "* The far jetty is newer than the near one. Someone has been crossing often."
    ]
   },
   {
    "id": "cracked_lantern",
    "at": [
     585,
     600
    ],
    "r": 50,
    "lines": [
     "* The lantern's glass is cracked and its wick cut short. They want no light on this shore."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     603,
     545
    ],
    "r": 150,
    "color": 16757575,
    "flicker": true
   }
  ],
  "triggers": [
   {
    "id": "m:wind_cult_landing",
    "rect": [
     600,
     440,
     320,
     200
    ],
    "once": "fight_wind_cult_landing",
    "requires": "quest_wind"
   }
  ]
 },
 {
  "id": "wind_cult_terraces",
  "name": "Wind Hill — Terraces",
  "bg": "bg_wind_cult_terraces",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     565,
     944
    ],
    [
     785,
     944
    ],
    [
     795,
     860
    ],
    [
     810,
     790
    ],
    [
     840,
     720
    ],
    [
     875,
     680
    ],
    [
     905,
     640
    ],
    [
     915,
     600
    ],
    [
     915,
     545
    ],
    [
     790,
     545
    ],
    [
     785,
     600
    ],
    [
     750,
     660
    ],
    [
     700,
     720
    ],
    [
     660,
     790
    ],
    [
     610,
     860
    ]
   ],
   [
    [
     700,
     530
    ],
    [
     790,
     550
    ],
    [
     915,
     550
    ],
    [
     1060,
     560
    ],
    [
     1080,
     500
    ],
    [
     1060,
     470
    ],
    [
     1000,
     430
    ],
    [
     960,
     420
    ],
    [
     790,
     410
    ],
    [
     740,
     420
    ],
    [
     680,
     450
    ],
    [
     640,
     500
    ]
   ],
   [
    [
     790,
     415
    ],
    [
     960,
     415
    ],
    [
     965,
     370
    ],
    [
     955,
     320
    ],
    [
     990,
     310
    ],
    [
     992,
     270
    ],
    [
     985,
     230
    ],
    [
     1000,
     200
    ],
    [
     1000,
     150
    ],
    [
     990,
     110
    ],
    [
     972,
     90
    ],
    [
     968,
     0
    ],
    [
     925,
     0
    ],
    [
     928,
     90
    ],
    [
     915,
     120
    ],
    [
     905,
     180
    ],
    [
     885,
     230
    ],
    [
     865,
     270
    ],
    [
     840,
     300
    ],
    [
     805,
     320
    ],
    [
     795,
     360
    ]
   ]
  ],
  "block": [
   [
    [
     878,
     425
    ],
    [
     972,
     425
    ],
    [
     972,
     520
    ],
    [
     878,
     520
    ]
   ],
   [
    [
     955,
     365
    ],
    [
     1068,
     365
    ],
    [
     1068,
     470
    ],
    [
     1010,
     470
    ],
    [
     972,
     425
    ],
    [
     955,
     425
    ]
   ],
   [
    [
     580,
     375
    ],
    [
     760,
     375
    ],
    [
     760,
     500
    ],
    [
     690,
     500
    ],
    [
     640,
     470
    ],
    [
     580,
     470
    ]
   ]
  ],
  "spawns": {
   "fromSafarisFarShore": {
    "at": [
     675,
     900
    ],
    "dir": "up"
   },
   "fromWindCultShrine": {
    "at": [
     946,
     50
    ],
    "dir": "down"
   },
   "candle": {
    "at": [
     940,
     335
    ],
    "dir": "right"
   }
  },
  "exits": [
   {
    "rect": [
     570,
     932,
     210,
     12
    ],
    "to": "safaris_far_shore",
    "spawn": "fromWindCultTerraces"
   },
   {
    "rect": [
     912,
     0,
     70,
     12
    ],
    "to": "wind_cult_shrine",
    "spawn": "fromWindCultTerraces"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "field",
  "fireflies": 18,
  "npcs": [],
  "things": [
   {
    "id": "wind_chimes",
    "at": [
     925,
     480
    ],
    "r": 70,
    "lines": [
     "* Flat stones on cords, knocking together in the wind. Each one is carved with a single mark: a wheel.",
     "* Some of the stones are new. Someone is still carving them."
    ]
   },
   {
    "id": "ruined_hut",
    "at": [
     885,
     262
    ],
    "r": 55,
    "lines": [
     "* A shepherd's hut, roof fallen in. Inside, a bedroll, a hunting knife, Dundean boots.",
     "* Edda said three of the young ones went up the hill. One of them did not go far."
    ]
   },
   {
    "id": "niche",
    "at": [
     1000,
     255
    ],
    "r": 50,
    "lines": [
     "* A niche in the wall, out of the wind. A candle burns here, steady, the only still flame on the hill.",
     "* Above, the chimes have stopped. Someone up there is waiting."
    ]
   }
  ],
  "candles": [
   {
    "id": "wind_cult_terraces",
    "at": [
     985,
     305
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     1048,
     290
    ],
    "r": 70,
    "color": 16764040,
    "flicker": true
   },
   {
    "at": [
     1515,
     38
    ],
    "r": 120,
    "color": 13623551,
    "flicker": false
   }
  ],
  "triggers": [
   {
    "id": "m:wind_cult_terraces",
    "rect": [
     640,
     535,
     440,
     65
    ],
    "once": "fight_wind_cult_terraces",
    "requires": "quest_wind"
   }
  ]
 },
 {
  "id": "wind_cult_shrine",
  "name": "Wind Hill — The Shrine",
  "bg": "bg_wind_cult_shrine",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     440,
     335
    ],
    [
     600,
     300
    ],
    [
     720,
     318
    ],
    [
     960,
     318
    ],
    [
     1150,
     312
    ],
    [
     1205,
     360
    ],
    [
     1200,
     450
    ],
    [
     1110,
     505
    ],
    [
     975,
     520
    ],
    [
     965,
     600
    ],
    [
     1010,
     690
    ],
    [
     1055,
     720
    ],
    [
     1065,
     800
    ],
    [
     1072,
     944
    ],
    [
     905,
     944
    ],
    [
     895,
     800
    ],
    [
     875,
     720
    ],
    [
     855,
     690
    ],
    [
     815,
     600
    ],
    [
     800,
     520
    ],
    [
     640,
     505
    ],
    [
     500,
     480
    ],
    [
     420,
     420
    ]
   ]
  ],
  "block": [
   [
    [
     485,
     320
    ],
    [
     515,
     320
    ],
    [
     515,
     335
    ],
    [
     485,
     335
    ]
   ],
   [
    [
     1160,
     385
    ],
    [
     1200,
     385
    ],
    [
     1200,
     400
    ],
    [
     1160,
     400
    ]
   ]
  ],
  "spawns": {
   "fromWindCultTerraces": {
    "at": [
     990,
     900
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     900,
     932,
     175,
     12
    ],
    "to": "wind_cult_terraces",
    "spawn": "fromWindCultShrine"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "waystone",
  "fireflies": 18,
  "npcs": [],
  "things": [
   {
    "id": "wind_shrine",
    "at": [
     845,
     330
    ],
    "r": 70,
    "lines": [
     "* The wind-wheel is cut deep and old. The banners around it are new, and hung by many hands.",
     "* Inside the shrine, pinned under a stone: the torn half of a page, the same careful hand as before.",
     "* FORMULA FRAGMENT (WIND) obtained. Half of a combination: Cult Rogue, and something of blood."
    ]
   },
   {
    "id": "feather_basin",
    "at": [
     800,
     330
    ],
    "r": 45,
    "lines": [
     "* A basin of pale feathers. The wind should scatter them. It does not."
    ]
   },
   {
    "id": "far_lamps",
    "at": [
     445,
     400
    ],
    "r": 50,
    "lines": [
     "* Far below, a few lamps across the water. From here the cult could watch every light in the Safaris go out, one by one."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     832,
     272
    ],
    "r": 110,
    "color": 11060448,
    "flicker": false
   },
   {
    "at": [
     1183,
     40
    ],
    "r": 90,
    "color": 13623536,
    "flicker": false
   }
  ],
  "triggers": [
   {
    "id": "m:wind_cult_platform",
    "rect": [
     780,
     540,
     210,
     80
    ],
    "once": "fight_wind_cult_platform",
    "requires": "quest_wind"
   },
   {
    "id": "m:wind_cult_leader",
    "rect": [
     720,
     300,
     240,
     100
    ],
    "once": "fight_wind_cult_leader",
    "requires": "quest_wind"
   }
  ]
 }
];

export const MISSION_ENTRANCES: { room: string; exit: RoomDef['exits'][number]; spawnName: string; spawn: { at: [number, number]; dir: 'up' | 'down' | 'left' | 'right' }; replaces?: string }[] = [
 {
  "room": "dundean_east_gate",
  "exit": {
   "rect": [
    1658,
    500,
    12,
    85
   ],
   "to": "east_valley_road",
   "spawn": "fromDundeanEastGate",
   "locked": "quest_blood",
   "lockedText": [
    "* The valley gate is barred with a beam as thick as a man.",
    "* Chalked on it: \"Longdale road closed. A dragon guards the pass.\" Brann would know why the bar is still down."
   ]
  },
  "spawnName": "fromEastValleyRoad",
  "spawn": {
   "at": [
    1620,
    542
   ],
   "dir": "left"
  },
  "replaces": "south_earlsome_valley"
 },
 {
  "room": "safaris_riverbank",
  "exit": {
   "rect": [
    1100,
    585,
    52,
    50
   ],
   "to": "safaris_far_shore",
   "spawn": "fromSafarisRiverbank",
   "locked": "quest_wind",
   "lockedText": [
    "* A rowboat, tied fast. Its oars are gone.",
    "* Across the dark water, pale banners move on a hill. Edda would know who keeps oars in Dundean."
   ]
  },
  "spawnName": "fromSafarisFarShore",
  "spawn": {
   "at": [
    1070,
    568
   ],
   "dir": "left"
  }
 }
];

export const MISSIONS: MissionData | null = {
 "fights": [
  {
   "id": "blood_rite_lichgate",
   "mission": "blood",
   "room": "graveyard_gate",
   "foes": [
    "blood_priest",
    "blood_priest",
    "blood_priest",
    "blood_priest"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Between the two red braziers, four figures in dark red robes stand in a line across the path. Their heads are bowed. They chant the same low word, over and over."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Blood Priests. A line of fresh red has been drawn across the flagstones at their feet. Kael's boot is already on it."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Under the hems of their robes, their feet are bare on the cold stone."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "You are guarding the gate. Then whatever you are guarding is further in."
    }
   ],
   "between": [
    "* Another Blood Priest steps over the red line. Remaining: {N}.",
    "* The chant does not stop. A Blood Priest takes the fallen one's place. Remaining: {N}.",
    "* The braziers flare. Another priest comes forward. Remaining: {N}."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The last priest sinks against the fence. The braziers burn lower, but they do not go out."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Further in, among the headstones, the chant goes on. More voices than before."
    }
   ]
  },
  {
   "id": "blood_rite_rows",
   "mission": "blood",
   "room": "graveyard_rows",
   "foes": [
    "blood_priest",
    "blood_priest",
    "blood_priest",
    "blood_priest",
    "blood_priest"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Five Blood Priests kneel among the headstones before the open crypt, each with a hand pressed flat against a grave. The earth beneath their palms is dark and wet."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Each kneels at a different stone, as if each had chosen one. One kneels at a stone with a fresh name, and keeps its hand there longest."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* They rise together, without a signal. None of them looks at Kael. They look at the steps behind him, as if he were in the way of something."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "These are Dundean's dead. Get your hands off them."
    }
   ],
   "between": [
    "* A Blood Priest rises from between the graves. Remaining: {N}.",
    "* Red cloth hangs still on the bare tree. Another priest comes on. Remaining: {N}.",
    "* Another Blood Priest leaves its grave and steps into the path. Remaining: {N}."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The rows fall quiet. The dark stains on the graves have stopped spreading."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Above, at the top of the cracked steps, red light pulses against the low clouds. The chant is louder there. Heavier."
    }
   ]
  },
  {
   "id": "blood_rite_circle",
   "mission": "blood",
   "room": "graveyard_ritual_circle",
   "foes": [
    "blood_priest",
    "blood_priest",
    "blood_priest",
    "blood_priest",
    "blood_priest",
    "blood_warrior",
    "blood_warrior",
    "blood_warrior"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The path runs straight through a ring of standing stones. Inside it, five Blood Priests stand at the points of a drawn star, chanting toward the dais."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Three larger shapes stand between them, armoured and still. Blood Warriors. They were priests once. The rite has made them into something that does not kneel."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* At the edge of the ring, grey ash has been laid in a careful line, just beyond the reach of the rest candle's light. Someone stood here, and watched, and left."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "He was here. He set you to this, and he walked away. Then I will break what he started."
    }
   ],
   "between": [
    "* The star is broken at one point. Another figure closes the gap. Remaining: {N}.",
    "* The stones hum. Another shape steps out of the ring's shadow. Remaining: {N}.",
    "* The chant falters, then rises again. Another foe comes forward. Remaining: {N}.",
    "* Fewer voices now. The ones left chant harder. Remaining: {N}."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The last of them goes down on one knee inside the ring and does not rise. The drawn star is smeared and broken."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The chant has stopped. In the silence, Kael hears something breathing on the dais. Slow. Patient. Not afraid."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Fourteen priests, and three warriors. And still it waited. The heart of the rite is up there."
    }
   ]
  },
  {
   "id": "blood_rite_altar",
   "mission": "blood",
   "room": "graveyard_ritual_circle",
   "foes": [
    "blood_rogue"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* A tall figure in red rises from the steps before the stained altar. It does not chant. It has no need to. The rite was always for it."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* A Blood Rogue. The last shape of the line that begins with the Blood Priest. The air around it is hot, as if the stones themselves were bleeding fire."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* On the hand it rests on the altar, a ring of carved horn."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* It turns its hood down the steps, toward the lichgate, toward one small grave beside a larger stone, and then back to Kael."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Whatever he promised you, it ends here."
    }
   ],
   "between": [
    "* The Blood Rogue stands alone before the altar, one hand still on the stone."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The Blood Rogue is gone from the dais steps. The red light drains out of the standing stones, one by one, until only the candle on the rest stone is left burning."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The graveyard is cold again. Somewhere below, a crow calls once and goes quiet."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* On the altar, half buried in grey ash, something pale catches the candlelight."
    }
   ]
  },
  {
   "id": "wind_cult_landing",
   "mission": "wind",
   "room": "safaris_far_shore",
   "foes": [
    "cult_priest",
    "cult_priest",
    "cult_priest",
    "cult_priest"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The wind comes down the slope all at once, cold and steady. The banners on the poles snap and twist. Four figures in pale robes walk out from between them."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Cult Priests. Their faces are hidden under hoods sewn with feathers. They walk barefoot over the stones, spreading out along the slope above the landing."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "You have been waiting for someone to cross. I am not the one you expected."
    }
   ],
   "between": [
    "* The banners crack in the wind. Another Cult Priest steps out. Remaining: {N}.",
    "* A Cult Priest comes down the slope against the wind. Remaining: {N}.",
    "* The grass bends flat. Another priest comes forward. Remaining: {N}."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The last priest goes down among the poles. Its torn banner keeps flying, though no hand holds the pole anymore."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Higher up the hill, the stone chimes are ringing. Slow, low notes, passed from terrace to terrace like word sent ahead."
    }
   ]
  },
  {
   "id": "wind_cult_terraces",
   "mission": "wind",
   "room": "wind_cult_terraces",
   "foes": [
    "cult_priest",
    "cult_priest",
    "cult_priest",
    "cult_warrior"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* On the middle terrace, three Cult Priests stand before the stone wind-chime frames, striking them in turn. Each note hangs in the air longer than it should."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Behind them, a broader figure waits with folded arms. A Cult Warrior. It watches Kael climb the last steps and makes no sound."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Ring them all you want. I am still coming up."
    }
   ],
   "between": [
    "* A chime sounds. Another figure steps from the terrace wall. Remaining: {N}.",
    "* The notes deepen. Another foe comes down the terrace. Remaining: {N}.",
    "* Another foe comes out of the wind. Remaining: {N}."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The chimes fall silent one by one as their ringers fall away. The last note fades over the valley."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* From the shrine above, there is no answering sound. Whoever waits there already knows he is coming."
    }
   ]
  },
  {
   "id": "wind_cult_platform",
   "mission": "wind",
   "room": "wind_cult_shrine",
   "foes": [
    "cult_priest",
    "cult_priest",
    "cult_warrior",
    "cult_warrior"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* On the round stone platform before the shrine, two Cult Priests and two Cult Warriors stand in a ring among the banner posts, facing outward."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Pressed into the dust on the platform stone is a single mark that does not belong to the cult: a handprint, in grey ash. The ring stands around it, as if guarding it."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "He stood here. He left his mark on your holy place, and you let him."
    }
   ],
   "between": [
    "* The ring closes. Another figure steps into the gap. Remaining: {N}.",
    "* Another of the ring turns to face Kael. Remaining: {N}.",
    "* The banners strain at their posts. Another foe comes on. Remaining: {N}."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The ring is broken. The wind takes the ash handprint off the stone and scatters it over the edge of the hill."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Only the shrine is left, and the one who stands alone before it."
    }
   ]
  },
  {
   "id": "wind_cult_leader",
   "mission": "wind",
   "room": "wind_cult_shrine",
   "foes": [
    "cult_rogue"
   ],
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Before the open shrine, beside the stone basin of feathers, a lone figure kneels toward the place where the handprint was. Then it rises and turns to face the path."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* A Cult Rogue. Taller than the priests. Lighter on its feet than the warriors. The wind bends around it, and the feathers in the basin lift and settle with every breath."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Your cult is gone. Whatever the grey man promised you, he is not here to keep it."
    }
   ],
   "between": [
    "* The Cult Rogue stands alone before the shrine."
   ],
   "after": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The Cult Rogue is gone from the shrine, and the wind dies with it. For the first time, Wind Hill is completely still."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Down the hill, the last few priests drop their banners and go over the far side of the slope. They do not look back."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* In the shrine, behind the wind-wheel relief, something has been pressed into a crack in the stone."
    }
   ]
  }
 ],
 "giver": {
  "blood": "brann",
  "wind": "edda"
 },
 "offer": {
  "blood": [
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "One more thing, before you go back to Edda's fire. The lodge has decided something. I do not like it, and I will do it anyway."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Past the east gate, where the valley road forks, there is the old graveyard. Dundean buried its dead there before the lodge was built. My father lies there."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Three nights now there have been red fires among the stones. Blood Priests, a whole circle of them, chanting over our graves. Warriors with them. And something worse."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Blood Priests do not gather like that on their own."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "No. One of my hunters went close on the first night. He says the ground by the lichgate was grey with ash. The same grey as your man."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The lodge will not send hunters into a rite. There are enough names crossed out on the board this season. But you walked here from the Norwoods. You came past the Waystone, and what was coiled at it."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "And you? You are a hunter. It is your father's grave."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "...I cannot go in there. Do not ask me again."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Break the rite. Put out the circle. I will open the gate, but only as far as the graveyard fork. Longdale stays closed until the lodge says otherwise."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "He went that way. If he stopped at the graveyard, I want to know why. I will go."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Then the bar comes up. Dun ar, open road. Come back the same way you leave."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Brann walks to the east gate and lifts the beam from its brackets. He does not look down the side track. The gate swings out onto the valley road."
   }
  ],
  "wind": [
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "And there is something else. I would rather not send you into it, but you will walk into everything anyway. I can see that much."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Across the river from the little house by the jetty, there is a hill the grass will not grow on. We call it Wind Hill. The old shrine sits at the top."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Cult Priests keep it. Wind priests, the old people called them. They hang banners on the slope and ring their stone chimes until the whole valley hums."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "They were few and quiet for years. Then, a few days ago, they grew bold. They took a fishing boat at the riverbank. They have warriors with them now."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Three of our young ones went up after them. They have not come down."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "A few days ago. When he came through the Safaris."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "The grass hears, and so do I. A trader saw a grey man on the far shore, speaking with the one who leads them. He did not stay long. He never seems to."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Break them up, Kael. Drive them off Wind Hill. The house by the river has a rowboat, but no oars. Take these. They were my husband's."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Old Edda sets a pair of worn oars against the table. The wood is dark with years of river water, and dry now. A small wheel is burned into each blade, worn almost smooth."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "They have not been in the water for four years. They will still hold."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I will bring them back, Edda. And I will find out what he wanted with that hill."
   }
  ]
 },
 "waiting": {
  "blood": [
   "The graveyard is down the side track at the fork. Follow the red fires. You will not miss them.",
   "The road to Longdale is still closed. The hunters felled a pine across it. The graveyard, and no further.",
   "Blood Priests feed the rite, but the circle needs a heart. Whatever stands at the altar, that is what holds it together.",
   "If you see my father's stone, near the lichgate, the one with the hunting horn cut in it... no. Just break the rite.",
   "I keep this gate. That is what I am for. Go on."
  ],
  "wind": [
   "The jetty by the river house. Fit the oars, row across, and follow the banners up the hill.",
   "Wind priests do not fight like hunters. They wait on high ground and let you come to them. Do not climb that hill tired.",
   "Whoever leads them will be at the shrine. Break that one, and the others will scatter like chaff.",
   "Eat before you row. The river is colder than it looks.",
   "The oars know the way across. Let them."
  ]
 },
 "done": {
  "blood": [
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The fires went out last night. We saw it from the wall. Every one of them, at once."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "The circle is broken. Fourteen priests, three warriors, and a Blood Rogue at the altar. None of them will chant over your dead again."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "It wore a ring. Carved horn, like the stone by the lichgate."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Brann is quiet for a long moment. He does not ask what became of it."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "...Fourteen. And you are standing here. The lodge will hear of this, and they will believe it."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "This was on the altar, in the ash. Half a page. Someone tore it on purpose."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "I am a hunter, not a scholar. But that is not priest-writing. It is too careful. Someone made that page, and someone gave it to them to guard."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Keep it close. A thing that was guarded that well will be missed. My father's stone is still standing. Thank you, Kael."
   }
  ],
  "wind": [
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "The chimes stopped at noon. I have not heard the valley this quiet in years. You did that."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "The priests are scattered. Their leader, a Cult Rogue, stood at the shrine. It will not ring those chimes again."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Edda nods once. She does not ask what became of it."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "It kept this in the shrine, behind the wind-wheel. A torn page. Half of something."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Let me see. ...That hand is old, and steady. That was written by someone who knew exactly what they were doing. Not by a wind priest."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "I cannot tell you what it is for. But I know this much: a thing worth tearing in two is a thing someone was afraid of."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Keep it with your sister's ribbon. And keep the oars."
   }
  ]
 },
 "fragments": {
  "blood": {
   "item": "fragment_blood",
   "item_name": "Torn Page (Blood Rite)",
   "desc": "Half of an old page, torn down the middle, found on the altar of the Blood Circle, half buried in grey ash. Careful brown ink. The edge is stained red.",
   "found": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Half buried in the ash on the altar lies half a page of thick, old paper. It has been torn cleanly down the middle. One corner is stained red where it lay against the stone."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The writing is careful and even, in brown ink. The first word is a name Kael knows: the name of the thing that stood at this altar."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* One edge is not torn but cut, straight and clean, as if with a blade along a rule."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "This was not left by priests. Someone wrote this, tore it in two, and gave half to the rite. The other half is somewhere else."
    }
   ],
   "page": "BLOOD ROGUE - of the Fire. The last of its line: Blood Priest, then Blood Warrior, then Blood Rogue.\n\nBLOOD ROGUE  +  ...\n\nCareful brown ink. The rest of the page is torn away. Along the tear, a few strokes of a second word remain. They cannot be read."
  },
  "wind": {
   "item": "fragment_wind",
   "item_name": "Torn Page (Cult)",
   "desc": "Half of an old page, found in a crack behind the Wind Hill wind-wheel. Careful brown ink. A small feather is caught in the fold.",
   "found": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Pressed deep into a crack behind the wind-wheel relief is a folded half-page of thick, old paper. A small grey feather is caught in the fold."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* It is torn cleanly down the middle. The writing is careful and even, in brown ink. The last word is a name Kael knows: the name of the thing that stood before this shrine."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Its outer edge is trimmed square and smooth, the way the pages of a bound book are trimmed. This leaf belonged to a book once."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "The cult did not write this. Someone gave it to them to keep, and told them to keep it from people like me. The other half is somewhere else."
    }
   ],
   "page": "...  +  CULT ROGUE - of the Air. The last of its line: Cult Priest, then Cult Warrior, then Cult Rogue.\n\nCareful brown ink. The first part of the page is torn away. Below the name, a small round scorch, grey at the edges, has eaten through the ink. Before the name, only the edge of a plus sign and the tail of another word remain."
  }
 },
 "formula": {
  "item": "rogue_formula",
  "item_name": "Rogue Formula",
  "desc": "Two halves of one leaf, fitted along their tear, in the same brown ink as the last page of Kael's Manual: Blood Rogue + Cult Rogue = Bloodgale.",
  "joined": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Kael lays the new half-page beside the one he already carries. The torn edges meet. Every tooth of the tear fits the other, as if it had been ripped a moment ago."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Fire and Air. The rite in the graveyard and the cult on the hill. Each kept one half, a day's walk apart, across a river."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The cut edge is familiar. Kael opens the Manual to its last page. The same brown ink. The same steady hand. The inner edge of the leaf fits the cut stub in the spine."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Halvard wrote this. He cut it out of my own book before he gave it to me. He knew they would be waiting."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "A formula. Blood Rogue and Cult Rogue, together. And where it says what they make..."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Below the two names, where the result should be, the ink has been burned away. A small round scorch, grey at the edges. Deliberate."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Grey at the edges. Like his ash. He burned the one part that mattered."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* But the heat pressed the letters into the paper before it took the ink. Held to the light, the scorch still shows them: BLOODGALE."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Bloodgale. A Blood Rogue and a Cult Rogue, made one. If I can catch them both..."
   }
  ],
  "page": "BLOOD ROGUE  +  CULT ROGUE  =  BLOODGALE\n\nOf the Fire and of the Air. Each the last of its line.\n\nIn brown ink, in Master Halvard's hand, on a leaf cut from the Manual. The name was burned out on purpose, but the heat pressed the letters into the paper. Capture a Blood Rogue and a Cult Rogue, then perform the formula from the Satchel."
 },
 "quests": [
  {
   "id": "blood",
   "title": "The Blood Rite",
   "stages": [
    "Brann says a Blood Priest rite has taken the old Dundean graveyard past the east gate. He has opened the gate as far as the graveyard fork. Break the rite.",
    "Kael has entered the old graveyard. The rite's chant leads deeper in, toward the Blood Circle at the top of the steps.",
    "The Blood Circle is broken: fourteen priests, three warriors, and the Blood Rogue is gone from the altar. Kael found half a torn page in the ash. Tell Brann."
   ]
  },
  {
   "id": "wind",
   "title": "The Cult on Wind Hill",
   "stages": [
    "Old Edda says Cult Priests hold Wind Hill, across the river from the house by the jetty. She gave Kael her husband's oars for the rowboat. Break up the cult.",
    "Kael has crossed to the far shore. The cult's chimes ring from the terraces above. Their leader waits at the shrine.",
    "The cult on Wind Hill is broken and its Cult Rogue is gone from the shrine. Kael found half of a torn page behind the wind-wheel. Tell Old Edda."
   ]
  },
  {
   "id": "formula",
   "title": "The Torn Formula",
   "stages": [
    "Kael found half of a torn page in a careful, old hand, in brown ink. The other half must be somewhere else.",
    "The halves fit: Blood Rogue + Cult Rogue = Bloodgale, in Halvard's hand, cut from Kael's Manual. Capture both Rogues, then use the formula.",
    "Bloodgale was made from the Rogue Formula."
   ]
  }
 ],
 "room_entries": {
  "east_valley_road": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The valley road climbs east between dark pines. At the fork, a waymarker leans with its paint worn off. The side track drops toward a low iron fence and a lichgate."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Up the main road, a great pine has been felled across the way. Brann's lodge mark is cut into the trunk. Longdale is still closed."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* In the mud of the side track, among the hunters' boot prints, are bare footprints. Many of them, all walking toward the graveyard. None of them come back up."
   }
  ],
  "graveyard_gate": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The lichgate sags on its posts. Beyond it, two braziers burn red on either side of the path. No one in Dundean has said who lit them."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The ground under the gate is dusted grey. Ash, fine as flour, trodden into the earth by many bare feet."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "His ash. He came this way before the rite began. Or he is the reason it began."
   }
  ],
  "graveyard_rows": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The headstones run in crooked rows toward an old crypt. Its iron door hangs open. The air inside smells of cold stone and something like rust."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Strips of red cloth have been tied to every branch of a bare tree, each one knotted with care. They barely move, though the wind is blowing."
   }
  ],
  "graveyard_ritual_circle": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* At the top of the steps, a ring of standing stones stands around a drawn star of dark red. Beyond it, on a raised dais, a slab altar glistens wet in the firelight."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Between the ring and the dais sits a flat rest stone with a single candle, its wick freshly trimmed. It is the only light here that is not red."
   }
  ],
  "safaris_far_shore": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The rowboat bumps against the far jetty. Kael ties it off. The rope slides into a groove worn deep in the mooring post, as if one boat had tied up here for years."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Tattered prayer banners hang from poles all along the path. Each one is painted with the same sign: a wheel of feathers turning in the wind."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* At the lantern post on the slope, someone has hung a fishing net, cut to pieces. The boat Edda spoke of lies overturned in the reeds."
   }
  ],
  "wind_cult_terraces": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The hill is cut into stone terraces. On each one stands a frame of hanging stone chimes. They ring low and slow, though no one seems to touch them."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The hut on the left terrace has lost its roof. Inside, a bedroll, a cold fire, and a single grey footprint on the hearthstone."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* By the door stands a pair of Dundean boots, laced, set side by side, as if someone meant to come back for them."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "He slept here. One night, maybe less. Then he moved on, and they rang their chimes for him."
   }
  ],
  "wind_cult_shrine": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The top of Wind Hill is a round stone platform among banner posts. Beyond it, an open shrine with a great wind-wheel carved into its back wall."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Before the shrine, a stone basin is heaped with feathers. They stir and settle, stir and settle, like something breathing."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* From here the whole valley lies open: the river, the roofs of Dundean, and far to the east, the dark line of the Longdale road."
   }
  ]
 }
};
