// GENERATED by tools/gen_regions.py: the regions through the old frontiers.
import type { RoomDef } from './rooms';
import type { RegionStory } from './regionTypes';

export const REGION_ROOMS: RoomDef[] = [
 {
  "id": "giant_mangal_f2",
  "name": "Giant Mangal — Second Floor",
  "bg": "bg_giant_mangal_f2",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     945,
     0
    ],
    [
     1010,
     0
    ],
    [
     1070,
     50
    ],
    [
     1100,
     100
    ],
    [
     1105,
     150
    ],
    [
     1095,
     200
    ],
    [
     1080,
     250
    ],
    [
     1110,
     290
    ],
    [
     1250,
     300
    ],
    [
     1400,
     330
    ],
    [
     1420,
     420
    ],
    [
     1350,
     480
    ],
    [
     1330,
     560
    ],
    [
     1400,
     640
    ],
    [
     1320,
     720
    ],
    [
     1150,
     770
    ],
    [
     960,
     795
    ],
    [
     935,
     835
    ],
    [
     935,
     944
    ],
    [
     775,
     944
    ],
    [
     775,
     835
    ],
    [
     700,
     795
    ],
    [
     560,
     770
    ],
    [
     450,
     730
    ],
    [
     330,
     700
    ],
    [
     280,
     600
    ],
    [
     370,
     540
    ],
    [
     420,
     460
    ],
    [
     440,
     380
    ],
    [
     480,
     320
    ],
    [
     600,
     300
    ],
    [
     780,
     285
    ],
    [
     900,
     275
    ],
    [
     960,
     270
    ],
    [
     975,
     250
    ],
    [
     1000,
     200
    ],
    [
     1030,
     150
    ],
    [
     1035,
     100
    ],
    [
     1000,
     50
    ]
   ]
  ],
  "block": [
   [
    [
     290,
     590
    ],
    [
     540,
     590
    ],
    [
     555,
     625
    ],
    [
     480,
     640
    ],
    [
     440,
     680
    ],
    [
     320,
     680
    ],
    [
     290,
     630
    ]
   ],
   [
    [
     600,
     615
    ],
    [
     690,
     610
    ],
    [
     700,
     650
    ],
    [
     650,
     670
    ],
    [
     600,
     660
    ]
   ],
   [
    [
     490,
     745
    ],
    [
     630,
     740
    ],
    [
     645,
     775
    ],
    [
     600,
     800
    ],
    [
     500,
     795
    ]
   ],
   [
    [
     1185,
     340
    ],
    [
     1320,
     345
    ],
    [
     1325,
     395
    ],
    [
     1190,
     400
    ]
   ],
   [
    [
     1205,
     600
    ],
    [
     1390,
     605
    ],
    [
     1400,
     665
    ],
    [
     1330,
     700
    ],
    [
     1210,
     690
    ]
   ],
   [
    [
     1010,
     670
    ],
    [
     1100,
     665
    ],
    [
     1170,
     700
    ],
    [
     1180,
     735
    ],
    [
     1100,
     745
    ],
    [
     1020,
     735
    ]
   ],
   [
    [
     485,
     380
    ],
    [
     560,
     340
    ],
    [
     620,
     320
    ],
    [
     650,
     345
    ],
    [
     700,
     430
    ],
    [
     720,
     480
    ],
    [
     620,
     485
    ],
    [
     490,
     460
    ]
   ],
   [
    [
     815,
     435
    ],
    [
     1000,
     425
    ],
    [
     1025,
     470
    ],
    [
     1000,
     520
    ],
    [
     830,
     520
    ],
    [
     800,
     480
    ]
   ]
  ],
  "spawns": {
   "fromGiantMangalF1": {
    "at": [
     850,
     820
    ],
    "dir": "up"
   },
   "fromGiantMangalF3": {
    "at": [
     1040,
     255
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     775,
     930,
     160,
     14
    ],
    "to": "giant_mangal_f1",
    "spawn": "fromGiantMangalF2"
   },
   {
    "rect": [
     945,
     0,
     65,
     14
    ],
    "to": "giant_mangal_f3",
    "spawn": "fromGiantMangalF2"
   }
  ],
  "scale": [
   0.3,
   0.5
  ],
  "music": "waystone",
  "fireflies": 26,
  "npcs": [],
  "things": [
   {
    "id": "spear_rack",
    "at": [
     600,
     500
    ],
    "r": 80,
    "lines": [
     "* A spear-rack, knocked flat. Hunters camped here. Their fire was put out with water, not left to die.",
     "* Someone scratched a tally into the root beside it. It stops at the second floor."
    ]
   },
   {
    "id": "broken_shafts",
    "at": [
     1040,
     215
    ],
    "r": 60,
    "lines": [
     "* Spear-shafts lie snapped on the lower treads of the upper stair. Lodge spears.",
     "* The hunters who barred the first floor came down this way, and they did not stop to pick these up."
    ]
   },
   {
    "id": "fungus_wall",
    "at": [
     330,
     460
    ],
    "r": 110,
    "lines": [
     "* The fungus gives off a cold light, like moonlight through water.",
     "* A long stripe of it has been scraped off the wall at shoulder height, as if someone had steadied himself here in the dark."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     210,
     60
    ],
    "r": 180,
    "color": 10471679,
    "flicker": false
   },
   {
    "at": [
     600,
     170
    ],
    "r": 120,
    "color": 8382704,
    "flicker": false
   },
   {
    "at": [
     1580,
     250
    ],
    "r": 140,
    "color": 8382704,
    "flicker": false
   },
   {
    "at": [
     200,
     690
    ],
    "r": 130,
    "color": 8382704,
    "flicker": false
   },
   {
    "at": [
     1550,
     620
    ],
    "r": 140,
    "color": 8382704,
    "flicker": false
   },
   {
    "at": [
     960,
     200
    ],
    "r": 110,
    "color": 8382704,
    "flicker": false
   }
  ],
  "triggers": []
 },
 {
  "id": "giant_mangal_f3",
  "name": "Giant Mangal — Third Floor, the Waypoint",
  "bg": "bg_giant_mangal_f3",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     250,
     380
    ],
    [
     430,
     352
    ],
    [
     700,
     342
    ],
    [
     726,
     0
    ],
    [
     830,
     0
    ],
    [
     900,
     340
    ],
    [
     1150,
     348
    ],
    [
     1260,
     362
    ],
    [
     1290,
     368
    ],
    [
     1350,
     372
    ],
    [
     1430,
     440
    ],
    [
     1460,
     560
    ],
    [
     1430,
     660
    ],
    [
     1350,
     760
    ],
    [
     1250,
     830
    ],
    [
     1150,
     862
    ],
    [
     900,
     880
    ],
    [
     880,
     830
    ],
    [
     860,
     760
    ],
    [
     800,
     735
    ],
    [
     745,
     770
    ],
    [
     745,
     944
    ],
    [
     480,
     944
    ],
    [
     470,
     800
    ],
    [
     430,
     762
    ],
    [
     330,
     765
    ],
    [
     230,
     725
    ],
    [
     175,
     640
    ],
    [
     185,
     520
    ],
    [
     205,
     440
    ]
   ]
  ],
  "block": [
   [
    [
     745,
     745
    ],
    [
     792,
     745
    ],
    [
     792,
     800
    ],
    [
     745,
     800
    ]
   ]
  ],
  "spawns": {
   "fromGiantMangalF2": {
    "at": [
     630,
     700
    ],
    "dir": "up"
   },
   "candle": {
    "at": [
     1305,
     392
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     480,
     930,
     265,
     14
    ],
    "to": "giant_mangal_f2",
    "spawn": "fromGiantMangalF3"
   },
   {
    "rect": [
     726,
     0,
     104,
     14
    ],
    "to": "giant_mangal_f4",
    "spawn": "fromGiantMangalF3",
    "locked": "never",
    "lockedText": [
     "* The stair to the fourth floor has been torn out of the trunk. The splinters are fresh; the sap is still running.",
     "* Far above, something heavy moves on the wood, and the whole tree creaks. Not yet."
    ]
   }
  ],
  "scale": [
   0.3,
   0.52
  ],
  "music": "waystone",
  "fireflies": 26,
  "npcs": [],
  "things": [
   {
    "id": "waypoint",
    "at": [
     820,
     470
    ],
    "r": 90,
    "lines": [
     "* A waypoint. The carved ring in the stone glows faintly, like a coal under ash.",
     "* Hunters mark these so they can come back to the same floor. Whoever comes back here will start from this stone."
    ]
   },
   {
    "id": "torn_stair",
    "at": [
     805,
     310
    ],
    "r": 70,
    "lines": [
     "* The upper stair has been ripped away. Not cut. Torn.",
     "* The lodge barred the first floor and called it a barbarian. Looking at this, Kael is not sure the lodge knows what lives up there."
    ]
   },
   {
    "id": "count_of_floors",
    "at": [
     990,
     560
    ],
    "r": 50,
    "lines": [
     "* Eight notches cut into the root, one for each floor. Two are marked with a waypoint ring: the third, and the sixth.",
     "* Beside the seventh, a hunter has carved a small blade. Beside the eighth, nothing. The cut there was never finished."
    ]
   }
  ],
  "candles": [
   {
    "id": "giant_mangal_f3",
    "at": [
     1322,
     262
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     820,
     465
    ],
    "r": 210,
    "color": 7317759,
    "flicker": false
   },
   {
    "at": [
     1322,
     262
    ],
    "r": 130,
    "color": 16756832,
    "flicker": true
   },
   {
    "at": [
     318,
     60
    ],
    "r": 150,
    "color": 12110079,
    "flicker": false
   },
   {
    "at": [
     80,
     300
    ],
    "r": 140,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     500,
     140
    ],
    "r": 110,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     935,
     110
    ],
    "r": 100,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     1040,
     270
    ],
    "r": 100,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     1240,
     330
    ],
    "r": 110,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     1400,
     405
    ],
    "r": 110,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     1595,
     135
    ],
    "r": 130,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     1545,
     560
    ],
    "r": 140,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     1640,
     680
    ],
    "r": 110,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     330,
     815
    ],
    "r": 100,
    "color": 6281471,
    "flicker": false
   },
   {
    "at": [
     785,
     915
    ],
    "r": 90,
    "color": 6281471,
    "flicker": false
   }
  ],
  "triggers": []
 },
 {
  "id": "ringfeld_lower_road",
  "name": "Ringfeld — Lower Road",
  "bg": "bg_ringfeld_lower_road",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     975,
     944
    ],
    [
     975,
     870
    ],
    [
     1015,
     850
    ],
    [
     1018,
     800
    ],
    [
     1012,
     760
    ],
    [
     985,
     715
    ],
    [
     960,
     680
    ],
    [
     938,
     645
    ],
    [
     920,
     600
    ],
    [
     935,
     560
    ],
    [
     970,
     515
    ],
    [
     1015,
     470
    ],
    [
     1040,
     440
    ],
    [
     1030,
     410
    ],
    [
     990,
     380
    ],
    [
     950,
     345
    ],
    [
     915,
     310
    ],
    [
     885,
     285
    ],
    [
     870,
     272
    ],
    [
     790,
     242
    ],
    [
     760,
     236
    ],
    [
     712,
     225
    ],
    [
     665,
     205
    ],
    [
     625,
     175
    ],
    [
     598,
     140
    ],
    [
     575,
     115
    ],
    [
     540,
     102
    ],
    [
     490,
     85
    ],
    [
     455,
     68
    ],
    [
     430,
     48
    ],
    [
     425,
     20
    ],
    [
     480,
     20
    ],
    [
     472,
     40
    ],
    [
     495,
     58
    ],
    [
     545,
     75
    ],
    [
     600,
     92
    ],
    [
     640,
     112
    ],
    [
     668,
     145
    ],
    [
     695,
     178
    ],
    [
     728,
     198
    ],
    [
     765,
     210
    ],
    [
     795,
     214
    ],
    [
     832,
     216
    ],
    [
     925,
     250
    ],
    [
     952,
     284
    ],
    [
     978,
     310
    ],
    [
     1012,
     340
    ],
    [
     1052,
     370
    ],
    [
     1088,
     400
    ],
    [
     1108,
     440
    ],
    [
     1102,
     480
    ],
    [
     1092,
     520
    ],
    [
     1092,
     560
    ],
    [
     1075,
     600
    ],
    [
     1092,
     640
    ],
    [
     1118,
     690
    ],
    [
     1152,
     740
    ],
    [
     1168,
     790
    ],
    [
     1162,
     850
    ],
    [
     1158,
     944
    ]
   ],
   [
    [
     285,
     405
    ],
    [
     350,
     415
    ],
    [
     430,
     445
    ],
    [
     515,
     477
    ],
    [
     605,
     507
    ],
    [
     700,
     542
    ],
    [
     765,
     572
    ],
    [
     808,
     608
    ],
    [
     865,
     648
    ],
    [
     915,
     698
    ],
    [
     945,
     740
    ],
    [
     968,
     788
    ],
    [
     1010,
     815
    ],
    [
     1030,
     838
    ],
    [
     1020,
     856
    ],
    [
     958,
     838
    ],
    [
     928,
     792
    ],
    [
     912,
     745
    ],
    [
     878,
     705
    ],
    [
     838,
     675
    ],
    [
     798,
     645
    ],
    [
     758,
     605
    ],
    [
     700,
     575
    ],
    [
     610,
     540
    ],
    [
     520,
     510
    ],
    [
     428,
     475
    ],
    [
     345,
     440
    ],
    [
     288,
     430
    ]
   ]
  ],
  "block": [],
  "spawns": {
   "fromMangalCrossroads": {
    "at": [
     1065,
     895
    ],
    "dir": "up"
   },
   "fromRingfeldShelter": {
    "at": [
     480,
     62
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     975,
     930,
     180,
     14
    ],
    "to": "mangal_crossroads",
    "spawn": "fromRingfeldLowerRoad"
   },
   {
    "rect": [
     425,
     0,
     55,
     34
    ],
    "to": "ringfeld_shelter",
    "spawn": "fromRingfeldLowerRoad"
   }
  ],
  "scale": [
   0.25,
   0.55
  ],
  "music": "field",
  "fireflies": 26,
  "npcs": [],
  "things": [
   {
    "id": "plank_path",
    "at": [
     620,
     525
    ],
    "r": 70,
    "lines": [
     "* Someone has laid planks along the lip of the slide and staked a rope beside them. The rope is new.",
     "* The mark on the trunk said spring. The keepers on the coast could not wait for spring."
    ]
   },
   {
    "id": "field_wall",
    "at": [
     1000,
     420
    ],
    "r": 70,
    "lines": [
     "* An old field wall of stacked stone. A section has been pulled down to let a cart through.",
     "* The wheel ruts go north, toward the sea."
    ]
   },
   {
    "id": "creek_bridge",
    "at": [
     860,
     245
    ],
    "r": 60,
    "lines": [
     "* The creek tastes of salt. The sea is close.",
     "* Fine grey flakes ride on the water, drifting down from inland. Kael has seen this ash before."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     436,
     25
    ],
    "r": 90,
    "color": 16757594,
    "flicker": true
   },
   {
    "at": [
     1520,
     70
    ],
    "r": 260,
    "color": 10475263,
    "flicker": false
   },
   {
    "at": [
     1300,
     380
    ],
    "r": 200,
    "color": 9418984,
    "flicker": false
   }
  ],
  "triggers": []
 },
 {
  "id": "ringfeld_shelter",
  "name": "Ringfeld — Keepers' Shelter",
  "bg": "bg_ringfeld_shelter",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     340,
     522
    ],
    [
     420,
     482
    ],
    [
     600,
     440
    ],
    [
     700,
     400
    ],
    [
     718,
     300
    ],
    [
     760,
     255
    ],
    [
     940,
     255
    ],
    [
     960,
     350
    ],
    [
     965,
     410
    ],
    [
     1090,
     430
    ],
    [
     1250,
     475
    ],
    [
     1350,
     482
    ],
    [
     1430,
     472
    ],
    [
     1440,
     455
    ],
    [
     1520,
     450
    ],
    [
     1670,
     440
    ],
    [
     1670,
     508
    ],
    [
     1600,
     500
    ],
    [
     1540,
     488
    ],
    [
     1515,
     500
    ],
    [
     1505,
     525
    ],
    [
     1450,
     540
    ],
    [
     1400,
     565
    ],
    [
     1200,
     625
    ],
    [
     950,
     690
    ],
    [
     915,
     712
    ],
    [
     915,
     790
    ],
    [
     960,
     860
    ],
    [
     1000,
     944
    ],
    [
     700,
     944
    ],
    [
     740,
     860
    ],
    [
     740,
     712
    ],
    [
     700,
     690
    ],
    [
     500,
     655
    ],
    [
     300,
     605
    ],
    [
     250,
     565
    ],
    [
     285,
     532
    ]
   ]
  ],
  "block": [
   [
    [
     758,
     432
    ],
    [
     892,
     432
    ],
    [
     900,
     492
    ],
    [
     830,
     505
    ],
    [
     758,
     488
    ]
   ],
   [
    [
     895,
     430
    ],
    [
     918,
     430
    ],
    [
     918,
     452
    ],
    [
     895,
     452
    ]
   ],
   [
    [
     1300,
     430
    ],
    [
     1345,
     430
    ],
    [
     1345,
     478
    ],
    [
     1300,
     478
    ]
   ],
   [
    [
     305,
     505
    ],
    [
     342,
     505
    ],
    [
     342,
     545
    ],
    [
     305,
     545
    ]
   ]
  ],
  "spawns": {
   "fromRingfeldLowerRoad": {
    "at": [
     828,
     760
    ],
    "dir": "up"
   },
   "fromRingfeldShoreRoad": {
    "at": [
     1420,
     500
    ],
    "dir": "left"
   },
   "candle": {
    "at": [
     700,
     560
    ],
    "dir": "up"
   }
  },
  "exits": [
   {
    "rect": [
     700,
     930,
     300,
     14
    ],
    "to": "ringfeld_lower_road",
    "spawn": "fromRingfeldShelter"
   },
   {
    "rect": [
     1656,
     440,
     14,
     68
    ],
    "to": "ringfeld_shore_road",
    "spawn": "fromRingfeldShelter"
   }
  ],
  "scale": [
   0.32,
   0.55
  ],
  "music": "town",
  "fireflies": 12,
  "npcs": [
   {
    "id": "maren",
    "at": [
     420,
     525
    ],
    "sprite": "innkeeper_idle",
    "name": "Maren",
    "portrait": "innkeeper_portrait"
   },
   {
    "id": "osk",
    "at": [
     1360,
     530
    ],
    "sprite": "hunter_idle",
    "name": "Osk",
    "portrait": "hunter_portrait"
   }
  ],
  "things": [
   {
    "id": "shelter_well",
    "at": [
     825,
     470
    ],
    "r": 70,
    "lines": [
     "* A covered well. The rope is wet; someone drew water tonight.",
     "* Cut into the well-cap: the names of keepers, one under the other. The newest name has no year beside it."
    ]
   },
   {
    "id": "dark_lighthouse",
    "at": [
     1470,
     470
    ],
    "r": 55,
    "lines": [
     "* Out on the rock, the Lighthouse stands dark. No lamp has burned in it for many nights.",
     "* The water between here and the rock is never still. Even with no wind."
    ]
   },
   {
    "id": "empty_cart",
    "at": [
     1170,
     465
    ],
    "r": 70,
    "lines": [
     "* A keepers' cart, its traces cut. Grey ash has settled in the boards.",
     "* It came on the wind, from inland. Kael wipes a finger through it. It is cold."
    ]
   }
  ],
  "candles": [
   {
    "id": "ringfeld_shelter",
    "at": [
     680,
     520
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     385,
     355
    ],
    "r": 140,
    "color": 16757594,
    "flicker": true
   },
   {
    "at": [
     360,
     475
    ],
    "r": 120,
    "color": 16752704,
    "flicker": true
   },
   {
    "at": [
     530,
     330
    ],
    "r": 80,
    "color": 16757594,
    "flicker": false
   },
   {
    "at": [
     635,
     290
    ],
    "r": 80,
    "color": 16757594,
    "flicker": false
   },
   {
    "at": [
     873,
     305
    ],
    "r": 160,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1500,
     490
    ],
    "r": 70,
    "color": 16754768,
    "flicker": true
   }
  ],
  "triggers": []
 },
 {
  "id": "ringfeld_shore_road",
  "name": "Ringfeld — Shore Road",
  "bg": "bg_ringfeld_shore_road",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     0,
     505
    ],
    [
     60,
     503
    ],
    [
     110,
     500
    ],
    [
     122,
     460
    ],
    [
     128,
     425
    ],
    [
     165,
     425
    ],
    [
     163,
     470
    ],
    [
     155,
     500
    ],
    [
     300,
     505
    ],
    [
     450,
     515
    ],
    [
     600,
     532
    ],
    [
     750,
     540
    ],
    [
     900,
     540
    ],
    [
     1000,
     512
    ],
    [
     1050,
     522
    ],
    [
     1080,
     545
    ],
    [
     1150,
     578
    ],
    [
     1190,
     620
    ],
    [
     1200,
     680
    ],
    [
     1185,
     760
    ],
    [
     1210,
     830
    ],
    [
     1230,
     890
    ],
    [
     1240,
     944
    ],
    [
     800,
     944
    ],
    [
     790,
     860
    ],
    [
     800,
     780
    ],
    [
     830,
     700
    ],
    [
     880,
     640
    ],
    [
     905,
     590
    ],
    [
     760,
     585
    ],
    [
     600,
     582
    ],
    [
     450,
     565
    ],
    [
     300,
     557
    ],
    [
     150,
     552
    ],
    [
     0,
     548
    ]
   ],
   [
    [
     1000,
     512
    ],
    [
     1015,
     478
    ],
    [
     1060,
     425
    ],
    [
     1140,
     350
    ],
    [
     1185,
     335
    ],
    [
     1198,
     345
    ],
    [
     1150,
     425
    ],
    [
     1100,
     490
    ],
    [
     1050,
     522
    ]
   ]
  ],
  "block": [
   [
    [
     945,
     548
    ],
    [
     968,
     548
    ],
    [
     968,
     562
    ],
    [
     945,
     562
    ]
   ],
   [
    [
     845,
     645
    ],
    [
     890,
     635
    ],
    [
     900,
     680
    ],
    [
     855,
     690
    ]
   ],
   [
    [
     1110,
     710
    ],
    [
     1170,
     700
    ],
    [
     1185,
     735
    ],
    [
     1130,
     750
    ]
   ]
  ],
  "spawns": {
   "fromRingfeldShelter": {
    "at": [
     60,
     527
    ],
    "dir": "right"
   },
   "fromLighthouseF1": {
    "at": [
     1130,
     395
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     0,
     505,
     14,
     43
    ],
    "to": "ringfeld_shelter",
    "spawn": "fromRingfeldShoreRoad"
   },
   {
    "rect": [
     1150,
     330,
     50,
     14
    ],
    "to": "lighthouse_f1",
    "spawn": "fromRingfeldShoreRoad",
    "locked": "never",
    "lockedText": [
     "* The causeway is broken halfway to the rock. The sea boils white over the gap, and something long turns under the water.",
     "* The keepers say the overlord of these waters lets nothing cross to the Lighthouse. Not tonight."
    ]
   }
  ],
  "scale": [
   0.3,
   0.55
  ],
  "music": "field",
  "fireflies": 26,
  "npcs": [],
  "things": [
   {
    "id": "causeway_lantern",
    "at": [
     965,
     540
    ],
    "r": 60,
    "lines": [
     "* The lantern is lit, but no one tends it. The oil is nearly gone.",
     "* Beyond it, the causeway runs out into the dark and then simply stops."
    ]
   },
   {
    "id": "wreck",
    "at": [
     1200,
     760
    ],
    "r": 90,
    "lines": [
     "* A keeper's boat, broken in half. The planks are not rotten. They are crushed.",
     "* Whatever did this came from below."
    ]
   },
   {
    "id": "tide_marks",
    "at": [
     1050,
     600
    ],
    "r": 70,
    "lines": [
     "* A line of grey ash along the high-water mark, as if the sea had been asked to carry it away and refused.",
     "* It fell here the night the Norwoods shook. Whatever he is, his ash reaches further than his road."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     972,
     492
    ],
    "r": 170,
    "color": 16756816,
    "flicker": true
   },
   {
    "at": [
     1240,
     10
    ],
    "r": 260,
    "color": 12375295,
    "flicker": false
   }
  ],
  "triggers": []
 },
 {
  "id": "south_earlsome_valley",
  "name": "South Earlsome — The Valley Climb",
  "bg": "bg_south_earlsome_valley",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     700,
     944
    ],
    [
     740,
     880
    ],
    [
     790,
     820
    ],
    [
     850,
     775
    ],
    [
     890,
     730
    ],
    [
     930,
     702
    ],
    [
     950,
     668
    ],
    [
     935,
     645
    ],
    [
     875,
     625
    ],
    [
     850,
     600
    ],
    [
     820,
     570
    ],
    [
     795,
     530
    ],
    [
     782,
     490
    ],
    [
     785,
     455
    ],
    [
     820,
     425
    ],
    [
     880,
     400
    ],
    [
     960,
     372
    ],
    [
     990,
     345
    ],
    [
     955,
     315
    ],
    [
     935,
     290
    ],
    [
     960,
     268
    ],
    [
     1030,
     245
    ],
    [
     1025,
     215
    ],
    [
     1015,
     185
    ],
    [
     1060,
     165
    ],
    [
     1150,
     148
    ],
    [
     1172,
     120
    ],
    [
     1168,
     75
    ],
    [
     1205,
     75
    ],
    [
     1210,
     105
    ],
    [
     1245,
     128
    ],
    [
     1250,
     160
    ],
    [
     1200,
     178
    ],
    [
     1110,
     192
    ],
    [
     1120,
     215
    ],
    [
     1150,
     250
    ],
    [
     1140,
     285
    ],
    [
     1110,
     302
    ],
    [
     1130,
     345
    ],
    [
     1100,
     400
    ],
    [
     1000,
     432
    ],
    [
     950,
     455
    ],
    [
     950,
     490
    ],
    [
     985,
     535
    ],
    [
     1050,
     570
    ],
    [
     1095,
     592
    ],
    [
     1060,
     640
    ],
    [
     1002,
     650
    ],
    [
     1000,
     690
    ],
    [
     1060,
     705
    ],
    [
     1085,
     730
    ],
    [
     1065,
     770
    ],
    [
     1015,
     820
    ],
    [
     1030,
     880
    ],
    [
     1050,
     944
    ]
   ],
   [
    [
     945,
     602
    ],
    [
     1060,
     592
    ],
    [
     1180,
     598
    ],
    [
     1235,
     615
    ],
    [
     1225,
     648
    ],
    [
     1100,
     650
    ],
    [
     1000,
     652
    ],
    [
     950,
     642
    ]
   ]
  ],
  "block": [],
  "spawns": {
   "fromEastValleyRoad": {
    "at": [
     870,
     870
    ],
    "dir": "up"
   },
   "fromEarlsomeDragonPass": {
    "at": [
     1205,
     140
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     715,
     930,
     320,
     14
    ],
    "to": "east_valley_road",
    "spawn": "fromSouthEarlsomeValley"
   },
   {
    "rect": [
     1160,
     75,
     55,
     22
    ],
    "to": "earlsome_dragon_pass",
    "spawn": "fromSouthEarlsomeValley"
   }
  ],
  "scale": [
   0.24,
   0.5
  ],
  "music": "field",
  "fireflies": 26,
  "npcs": [],
  "things": [
   {
    "id": "felled_pine_moved",
    "at": [
     725,
     835
    ],
    "r": 100,
    "lines": [
     "* The pine Brann felled has been hauled off the road with ropes and horses. His lodge mark is on the cut end.",
     "* He kept his word. The road is open. What waits up it is not his to keep."
    ]
   },
   {
    "id": "drovers_hut",
    "at": [
     900,
     315
    ],
    "r": 90,
    "lines": [
     "* A drovers' hut. The roof is down. Inside, three bedrolls laid side by side: one large, two small.",
     "* The ashes of the fire are grey and fine as flour. He let the children sleep. Then he went on."
    ]
   },
   {
    "id": "red_cleft",
    "at": [
     1195,
     120
    ],
    "r": 70,
    "lines": [
     "* The red light is not fire. It does not flicker. It is cold to look at.",
     "* Hunters' marks are scratched on the boulders here, all pointing back down the valley."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     1175,
     60
    ],
    "r": 170,
    "color": 12861484,
    "flicker": false
   }
  ],
  "triggers": []
 },
 {
  "id": "earlsome_dragon_pass",
  "name": "South Earlsome — The Dragon's Pass",
  "bg": "bg_earlsome_dragon_pass",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     475,
     944
    ],
    [
     510,
     870
    ],
    [
     530,
     820
    ],
    [
     555,
     770
    ],
    [
     540,
     730
    ],
    [
     500,
     690
    ],
    [
     470,
     652
    ],
    [
     420,
     625
    ],
    [
     390,
     590
    ],
    [
     335,
     545
    ],
    [
     312,
     480
    ],
    [
     297,
     410
    ],
    [
     300,
     365
    ],
    [
     340,
     340
    ],
    [
     420,
     322
    ],
    [
     500,
     300
    ],
    [
     580,
     278
    ],
    [
     650,
     258
    ],
    [
     690,
     235
    ],
    [
     705,
     205
    ],
    [
     745,
     186
    ],
    [
     785,
     178
    ],
    [
     800,
     130
    ],
    [
     826,
     80
    ],
    [
     832,
     0
    ],
    [
     876,
     0
    ],
    [
     872,
     80
    ],
    [
     843,
     130
    ],
    [
     843,
     170
    ],
    [
     862,
     180
    ],
    [
     900,
     195
    ],
    [
     940,
     225
    ],
    [
     952,
     246
    ],
    [
     800,
     250
    ],
    [
     740,
     253
    ],
    [
     690,
     285
    ],
    [
     620,
     318
    ],
    [
     560,
     350
    ],
    [
     500,
     385
    ],
    [
     465,
     420
    ],
    [
     455,
     470
    ],
    [
     470,
     530
    ],
    [
     520,
     562
    ],
    [
     580,
     590
    ],
    [
     660,
     612
    ],
    [
     760,
     622
    ],
    [
     880,
     628
    ],
    [
     930,
     645
    ],
    [
     995,
     670
    ],
    [
     1000,
     710
    ],
    [
     975,
     760
    ],
    [
     930,
     790
    ],
    [
     830,
     795
    ],
    [
     720,
     792
    ],
    [
     660,
     822
    ],
    [
     615,
     880
    ],
    [
     610,
     944
    ]
   ]
  ],
  "block": [
   [
    [
     940,
     565
    ],
    [
     985,
     560
    ],
    [
     990,
     650
    ],
    [
     945,
     652
    ]
   ]
  ],
  "spawns": {
   "fromSouthEarlsomeValley": {
    "at": [
     545,
     880
    ],
    "dir": "up"
   },
   "fromLongdaleRoad": {
    "at": [
     850,
     95
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     470,
     930,
     140,
     14
    ],
    "to": "south_earlsome_valley",
    "spawn": "fromEarlsomeDragonPass"
   },
   {
    "rect": [
     825,
     0,
     60,
     14
    ],
    "to": "longdale_road",
    "spawn": "fromEarlsomeDragonPass"
   }
  ],
  "scale": [
   0.3,
   0.55
  ],
  "music": "waystone",
  "fireflies": 26,
  "npcs": [],
  "things": [
   {
    "id": "still_pool",
    "at": [
     820,
     520
    ],
    "r": 120,
    "lines": [
     "* The falls pour into the pool, and the pool does not move. Not a ripple.",
     "* Something very large lies under the surface. It has been lying there a long time."
    ]
   },
   {
    "id": "red_shrine",
    "at": [
     275,
     330
    ],
    "r": 80,
    "lines": [
     "* An old shrine, cut into the cliff out of reach. The red light comes from inside it.",
     "* There is grey ash on the ledge below it. He climbed up there. Kael cannot see how."
    ]
   },
   {
    "id": "weir_tracks",
    "at": [
     705,
     262
    ],
    "r": 45,
    "lines": [
     "* Across the wet weir: one man's prints, and between them, two pairs of small ones.",
     "* They crossed in front of the pool and nothing stopped them. Kael does not understand that. He does not like it."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     240,
     230
    ],
    "r": 180,
    "color": 16724000,
    "flicker": true
   },
   {
    "at": [
     1300,
     330
    ],
    "r": 240,
    "color": 10275071,
    "flicker": false
   },
   {
    "at": [
     850,
     30
    ],
    "r": 110,
    "color": 12112127,
    "flicker": false
   }
  ],
  "triggers": [
   {
    "id": "b:apalala",
    "rect": [
     680,
     170,
     320,
     110
    ],
    "once": "boss_apalala"
   }
  ]
 },
 {
  "id": "longdale_road",
  "name": "South Earlsome — The Longdale Road",
  "bg": "bg_longdale_road",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     300,
     0
    ],
    [
     340,
     0
    ],
    [
     338,
     30
    ],
    [
     360,
     55
    ],
    [
     400,
     75
    ],
    [
     455,
     95
    ],
    [
     520,
     110
    ],
    [
     580,
     122
    ],
    [
     615,
     108
    ],
    [
     645,
     95
    ],
    [
     680,
     92
    ],
    [
     680,
     108
    ],
    [
     660,
     125
    ],
    [
     650,
     145
    ],
    [
     670,
     165
    ],
    [
     688,
     185
    ],
    [
     670,
     205
    ],
    [
     610,
     228
    ],
    [
     555,
     250
    ],
    [
     535,
     272
    ],
    [
     560,
     290
    ],
    [
     620,
     305
    ],
    [
     680,
     330
    ],
    [
     740,
     370
    ],
    [
     800,
     410
    ],
    [
     850,
     450
    ],
    [
     890,
     490
    ],
    [
     910,
     540
    ],
    [
     912,
     600
    ],
    [
     905,
     660
    ],
    [
     900,
     720
    ],
    [
     902,
     780
    ],
    [
     905,
     840
    ],
    [
     920,
     890
    ],
    [
     965,
     944
    ],
    [
     700,
     944
    ],
    [
     712,
     890
    ],
    [
     722,
     840
    ],
    [
     718,
     780
    ],
    [
     702,
     720
    ],
    [
     715,
     660
    ],
    [
     760,
     610
    ],
    [
     800,
     560
    ],
    [
     800,
     520
    ],
    [
     770,
     480
    ],
    [
     720,
     440
    ],
    [
     660,
     400
    ],
    [
     600,
     360
    ],
    [
     530,
     330
    ],
    [
     485,
     300
    ],
    [
     468,
     265
    ],
    [
     480,
     240
    ],
    [
     530,
     218
    ],
    [
     600,
     190
    ],
    [
     625,
     165
    ],
    [
     600,
     148
    ],
    [
     540,
     135
    ],
    [
     460,
     120
    ],
    [
     395,
     100
    ],
    [
     345,
     72
    ],
    [
     312,
     40
    ]
   ]
  ],
  "block": [],
  "spawns": {
   "fromEarlsomeDragonPass": {
    "at": [
     830,
     900
    ],
    "dir": "up"
   },
   "fromLongdaleSquare": {
    "at": [
     325,
     45
    ],
    "dir": "down"
   }
  },
  "exits": [
   {
    "rect": [
     700,
     930,
     270,
     14
    ],
    "to": "earlsome_dragon_pass",
    "spawn": "fromLongdaleRoad"
   },
   {
    "rect": [
     285,
     0,
     60,
     12
    ],
    "to": "longdale_square",
    "spawn": "fromLongdaleRoad"
   }
  ],
  "scale": [
   0.24,
   0.55
  ],
  "music": "field",
  "fireflies": 26,
  "npcs": [],
  "things": [
   {
    "id": "milestone",
    "at": [
     665,
     660
    ],
    "r": 110,
    "lines": [
     "* A milestone. LONGDALE, it says, and below that a number worn smooth.",
     "* Someone has scraped the moss off it recently, as if to read it in the dark."
    ]
   },
   {
    "id": "lamp_niche",
    "at": [
     650,
     450
    ],
    "r": 130,
    "lines": [
     "* A shrine niche with an oil lamp. The oil is fresh, the wick unburnt.",
     "* Travellers light it after the pass, to give thanks. No one has, tonight."
    ]
   },
   {
    "id": "river_bridge",
    "at": [
     840,
     420
    ],
    "r": 120,
    "lines": [
     "* A stone bridge over the river. The road does not cross it.",
     "* South, the river runs on toward Wesburn. The ash is not on the bridge. He did not go south."
    ]
   }
  ],
  "candles": [],
  "lights": [
   {
    "at": [
     660,
     78
    ],
    "r": 110,
    "color": 16756816,
    "flicker": true
   },
   {
    "at": [
     760,
     55
    ],
    "r": 180,
    "color": 16751168,
    "flicker": true
   },
   {
    "at": [
     1548,
     35
    ],
    "r": 220,
    "color": 10467583,
    "flicker": false
   },
   {
    "at": [
     1400,
     550
    ],
    "r": 260,
    "color": 7311312,
    "flicker": false
   }
  ],
  "triggers": []
 },
 {
  "id": "longdale_square",
  "name": "Longdale — Guild Square",
  "bg": "bg_longdale_square",
  "size": [
   1670,
   944
  ],
  "walk": [
   [
    [
     185,
     645
    ],
    [
     250,
     612
    ],
    [
     330,
     592
    ],
    [
     420,
     560
    ],
    [
     485,
     535
    ],
    [
     530,
     472
    ],
    [
     565,
     442
    ],
    [
     630,
     430
    ],
    [
     760,
     416
    ],
    [
     900,
     410
    ],
    [
     960,
     402
    ],
    [
     975,
     345
    ],
    [
     1035,
     325
    ],
    [
     1050,
     250
    ],
    [
     1060,
     172
    ],
    [
     1125,
     172
    ],
    [
     1132,
     250
    ],
    [
     1142,
     330
    ],
    [
     1162,
     400
    ],
    [
     1218,
     458
    ],
    [
     1232,
     520
    ],
    [
     1238,
     600
    ],
    [
     1300,
     660
    ],
    [
     1360,
     700
    ],
    [
     1365,
     730
    ],
    [
     1300,
     758
    ],
    [
     1100,
     788
    ],
    [
     925,
     790
    ],
    [
     925,
     940
    ],
    [
     715,
     940
    ],
    [
     715,
     790
    ],
    [
     540,
     782
    ],
    [
     410,
     772
    ],
    [
     330,
     760
    ],
    [
     292,
     702
    ],
    [
     200,
     690
    ]
   ],
   [
    [
     1242,
     585
    ],
    [
     1300,
     532
    ],
    [
     1330,
     518
    ],
    [
     1440,
     515
    ],
    [
     1478,
     548
    ],
    [
     1480,
     590
    ],
    [
     1418,
     600
    ],
    [
     1410,
     680
    ],
    [
     1360,
     700
    ],
    [
     1300,
     660
    ],
    [
     1238,
     600
    ]
   ]
  ],
  "block": [
   [
    [
     712,
     486
    ],
    [
     790,
     466
    ],
    [
     888,
     500
    ],
    [
     888,
     562
    ],
    [
     812,
     572
    ],
    [
     712,
     542
    ]
   ],
   [
    [
     530,
     775
    ],
    [
     605,
     648
    ],
    [
     715,
     648
    ],
    [
     715,
     800
    ],
    [
     530,
     800
    ]
   ],
   [
    [
     925,
     648
    ],
    [
     1015,
     648
    ],
    [
     1100,
     765
    ],
    [
     1100,
     800
    ],
    [
     925,
     800
    ]
   ]
  ],
  "spawns": {
   "fromLongdaleRoad": {
    "at": [
     820,
     880
    ],
    "dir": "up"
   },
   "fromNorthEarlsomeRoad": {
    "at": [
     1092,
     215
    ],
    "dir": "down"
   },
   "candle": {
    "at": [
     700,
     595
    ],
    "dir": "left"
   }
  },
  "exits": [
   {
    "rect": [
     715,
     930,
     210,
     14
    ],
    "to": "longdale_road",
    "spawn": "fromLongdaleSquare"
   },
   {
    "rect": [
     1055,
     165,
     75,
     22
    ],
    "to": "north_earlsome_road",
    "spawn": "fromLongdaleSquare",
    "locked": "never",
    "lockedText": [
     "* The north gate is shut and barred. Dale-ward closes at dusk, and the ward will not open it before light.",
     "* At the foot of the gate, in the frost, grey ash. He went north."
    ]
   }
  ],
  "scale": [
   0.28,
   0.5
  ],
  "music": "town",
  "fireflies": 12,
  "npcs": [
   {
    "id": "hild",
    "at": [
     330,
     612
    ],
    "sprite": "innkeeper_idle",
    "name": "Hild",
    "portrait": "innkeeper_portrait"
   },
   {
    "id": "tamsin",
    "at": [
     1062,
     295
    ],
    "sprite": "hunter_idle",
    "name": "Tamsin",
    "portrait": "hunter_portrait"
   }
  ],
  "things": [
   {
    "id": "guild_board",
    "at": [
     1540,
     600
    ],
    "r": 90,
    "lines": [
     "* The board is full. More notices than any town Kael has seen. Most are bounties.",
     "* One reads: \"A notorious criminal called al-Rashid has escaped the prisons of Dundean. He is said to have run into the cave north of here.\"",
     "* Another: \"Follow the river south from here. A barbarian has been sighted in the forest on the west bank.\" Someone has written CYRUS beside it."
    ]
   },
   {
    "id": "trough",
    "at": [
     800,
     520
    ],
    "r": 100,
    "lines": [
     "* The water in the trough has a skin of grey on it.",
     "* Ash. Days old, and still floating."
    ]
   },
   {
    "id": "north_gate",
    "at": [
     1092,
     195
    ],
    "r": 55,
    "lines": [
     "* The north gate, barred for the night.",
     "* Past it, the mountain road climbs toward the cave the notices speak of."
    ]
   }
  ],
  "candles": [
   {
    "id": "longdale_square",
    "at": [
     660,
     565
    ],
    "kind": "candle_tall"
   }
  ],
  "lights": [
   {
    "at": [
     335,
     460
    ],
    "r": 120,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     905,
     425
    ],
    "r": 110,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     650,
     850
    ],
    "r": 110,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     970,
     850
    ],
    "r": 110,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1475,
     490
    ],
    "r": 100,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1385,
     440
    ],
    "r": 90,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1580,
     600
    ],
    "r": 90,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1180,
     355
    ],
    "r": 70,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1030,
     215
    ],
    "r": 60,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1050,
     130
    ],
    "r": 60,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1135,
     130
    ],
    "r": 60,
    "color": 16760944,
    "flicker": true
   },
   {
    "at": [
     1325,
     15
    ],
    "r": 80,
    "color": 13162751,
    "flicker": false
   }
  ],
  "triggers": []
 }
];

export const REGION_UNLOCKS: { exitTo: string; requires: string; lockedText: string[] }[] = [
 {
  "exitTo": "giant_mangal_f2",
  "requires": "thanked_wind",
  "lockedText": [
   "* The stair up is lashed shut with rope and timber. The lodge mark reads BARBARIAN ALERT. NO PASSAGE ABOVE THE FIRST FLOOR.",
   "* Carved beneath it: \"Closed by order of the Dundean hunters. Ask at the lodge.\" The lodge owes favours only to those who have served Dundean."
  ]
 },
 {
  "exitTo": "ringfeld_lower_road",
  "requires": "",
  "lockedText": []
 },
 {
  "exitTo": "south_earlsome_valley",
  "requires": "thanked_blood",
  "lockedText": [
   "* A pine lies across the valley road. Felled, not fallen. Brann's mark is cut into the trunk.",
   "* Beyond it the road climbs toward the red glow in the cliffs. Brann will have to lift it."
  ]
 }
];

export const REGION_STORY: RegionStory = {
 "room_entries": {
  "giant_mangal_f2": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The second floor is a hollow chamber cut into living wood. A hunters' spear-rack lies on its side by a ring of fire stones. The ashes in the ring are black and wet, not grey."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Snapped spear-shafts lie scattered down the treads of the upper stair. They were not dropped. Something broke them and threw them back down."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Along one wall, a stripe of glowing fungus has been scraped away at shoulder height, as if someone felt his way along it in the dark."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Hunters camped here, and something drove them out. This is not his work. Whatever lives above did this."
   }
  ],
  "giant_mangal_f3": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A round carved stone sits in a dais of heartwood, its marks worn smooth by old hands. A Waypoint. The air around it is still and faintly warm."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Notches are cut into a root beside the dais, one row for each day. The last row stops in the middle. Nobody came back to finish it."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Where the stair to the fourth floor should be, the trunk is split open. The treads have been torn out of the wood and lie in splinters far below. The sap is still running."
   }
  ],
  "ringfeld_lower_road": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* North of the fallen trunk, the road comes out of the trees onto open fields. A path of planks and rope has been laid around the slide. The knots are new."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The air smells of salt. Along the field wall, a fine grey dust lies in the cracks between the stones, old and dry. It came on the wind, not on anyone's boots."
   }
  ],
  "ringfeld_shelter": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A longhouse, a covered well and a stable lean-to stand inside a low wall. Smoke rises from the chimney. Past the sea gate, the Lighthouse stands dark on its rock."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "There is no town on this coast, the hunters said. Only the keepers. If anyone here has news, it is them."
   }
  ],
  "ringfeld_shore_road": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The shore road runs down to a stone causeway. At its landward end, a lantern on a post burns low, though the keepers filled it at dusk. The causeway runs out toward the dark Lighthouse."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A thin line of grey lies along the tide mark, left by the sea. Further out, the water is too still. Once, something vast moves beneath it, and the surface does not break."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "His ash, carried all the way from the Norwoods. The night he put out the Waystone, it reached even this coast. But he did not come this way."
   }
  ],
  "south_earlsome_valley": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Past the stump of Brann's pine, the valley road climbs between steep cliffs. By the ruined drovers' hut, three sets of prints: one long stride, two small ones keeping pace."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The prints are days old, their edges crumbled. Grey ash lies in each heel mark, as if it fell from him with every step."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Still walking. Still together. Above, the cliffs glow red. Whatever guards this pass, he went straight toward it."
   }
  ],
  "earlsome_dragon_pass": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* The road ends at a stone basin below a falls. A pool lies in it, black and perfectly still, though the water pours in from above. High in the cliff, a shrine glows red."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Footprints cross the stone weir toward the rock stair: one long stride, two small. They do not hurry. They do not stop."
   }
  ],
  "longdale_road": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Below the pass, the road runs down into a green dale. An old milestone stands at the roadside. Around its base, someone has tied a single strand of blue thread."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Blue, like her ribbon. Lira pulled a thread from her sleeve and tied it where I would see it. She is still telling me which way."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* In the shrine niche beside it, the old wick has been pinched out. A new one has been threaded beside it, and the oil is fresh. No one lit it."
   }
  ],
  "longdale_square": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "* Longdale is busy, even now. Hunters crowd the guild notice board, and the stone trough steams in the cold. Up the street, the north gate is shut."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* A faint line of grey ash runs along the cobbles, days old and nearly trodden away. It leads up the street and under the north gate."
   }
  ]
 },
 "npc_dialogue": {
  "maren": {
   "first": [
    {
     "speaker": "Maren",
     "portrait": "innkeeper_portrait",
     "text": "You came up the slide road? Then Osk's planks held. Come in from the wind. The well is clean and the fire is lit, and nobody here asks a traveller's business."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "I am looking for a man covered in grey ash. He has two children with him. A girl and a small boy."
    },
    {
     "speaker": "Maren",
     "portrait": "innkeeper_portrait",
     "text": "The Lighthouse had gone dark some nights before it came. Then, the night the ground shook in the Norwoods, grey ash fell on this coast for an hour. On the well and the sea."
    },
    {
     "speaker": "Maren",
     "portrait": "innkeeper_portrait",
     "text": "Days later a hunter came up from the Safaris. He spoke of a grey man walking east toward Dundean with two children. He did not come this way. The coast was not his road."
    },
    {
     "speaker": "Maren",
     "portrait": "innkeeper_portrait",
     "text": "If you want him, go back to the Safaris. Ask in Dundean. I am sorry. I wish I had better news to give you."
    }
   ],
   "repeat": [
    "Rest while you can. The road back to the Safaris is long, and it does not get kinder.",
    "The Lighthouse went dark and has stayed dark. I will not say what is in the water. Only that it is old, and it is waiting.",
    "Draw from the well before you go. Whatever else you find on the road, you will not find water as clean.",
    "My mother kept the shelter before me. She said the Lighthouse goes dark once in seven years, for a moon, then burns again. Not what lights it."
   ],
   "name": "Maren",
   "portrait": "innkeeper_portrait"
  },
  "osk": {
   "first": [
    {
     "speaker": "Osk",
     "portrait": "hunter_portrait",
     "text": "Stop there. ...You came round the slide. Good. I laid those planks myself. The keepers could not wait for spring, and neither could the people who need this shelter."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Where does the shore road go?"
    },
    {
     "speaker": "Osk",
     "portrait": "hunter_portrait",
     "text": "Down to the causeway and the Lighthouse. You can walk the shore. You cannot cross. The overlord in the water lets nothing across. Archelon, the old ones call it."
    },
    {
     "speaker": "Osk",
     "portrait": "hunter_portrait",
     "text": "I have watched boats try. I have pulled what was left of them out of the cove. Look at the water if you must. Do not set foot on the causeway."
    }
   ],
   "repeat": [
    "The sea gate stays open in daylight. After dark, I bar it. Be back inside by then.",
    "Archelon does not hunt the shore. It guards the causeway. As long as you stay on land, it lets you be.",
    "The ribs in the cove were a keeper's boat. He meant to light the Lighthouse again himself. He thought the fog would hide him."
   ],
   "name": "Osk",
   "portrait": "hunter_portrait"
  },
  "hild": {
   "first": [
    {
     "speaker": "Hild",
     "portrait": "innkeeper_portrait",
     "text": "Long day, short road. Sit, traveller. You look like you came down from the pass, and nobody comes down from the pass looking rested."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "A man in grey ash, with a girl and a small boy. Did they come through Longdale?"
    },
    {
     "speaker": "Hild",
     "portrait": "innkeeper_portrait",
     "text": "Some nights ago. He came down from the pass with them at evening. The dragon in the pool did not rise for him. It rises for everyone. Not for him."
    },
    {
     "speaker": "Hild",
     "portrait": "innkeeper_portrait",
     "text": "He paid for nothing and slept nowhere. The children ate what I gave them standing in the doorway. The girl thanked me. He never once looked at me."
    },
    {
     "speaker": "Hild",
     "portrait": "innkeeper_portrait",
     "text": "The girl asked me for a cup of lamp oil. For the road, she said. I gave it to her."
    },
    {
     "speaker": "Hild",
     "portrait": "innkeeper_portrait",
     "text": "The guild's notice about them went up on the board the day before they came."
    },
    {
     "speaker": "Hild",
     "portrait": "innkeeper_portrait",
     "text": "He left by the north gate before it shut. Tamsin keeps that gate. Ask her, if she will talk. She has not said much since."
    }
   ],
   "repeat": [
    "Long day, short road. There is soup on the fire and a bed upstairs. Use both.",
    "The guild board has more work on it than any board in the land. None of it pays well enough for the north road at night.",
    "The girl kept the boy's hand in hers the whole time. She did not let go even to eat."
   ],
   "name": "Hild",
   "portrait": "innkeeper_portrait"
  },
  "tamsin": {
   "first": [
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "Dale-ward closes at dusk. The north gate is barred, and it stays barred until morning. That is the law here, and I keep it."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "The grey man went through this gate. With two children. You saw him."
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "I saw him. He went out with the children just before I barred it. The light was going. I had my bow in my hand, and I did not raise it."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Why not?"
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "...Years ago I hunted these passes with a man from Azurelake, before he went home to the lake. He talked of nothing but his boy."
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "What is your name?"
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Kael."
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "The girl held his sleeve at this gate and said: Father, will Kael be all right? He said: He always comes."
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "I called him by his name. He looked at me as if I were a gatepost."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "...Father."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Tamsin takes a folded paper from inside her coat. The guild's seal is broken on it."
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "This came from your guild, the long way, by Wesing, the day before he did. Do not raise a bow to the man. The boy is to be let through the north gate at whatever hour he comes."
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "I barred it anyway. Dale-ward closes at dusk. That is the law here, and I keep it. One night is all I can give you."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "The day before..."
    },
    {
     "speaker": "Tamsin",
     "portrait": "hunter_portrait",
     "text": "The north road runs past the cave al-Rashid fled into. The guild says a breeder blocks the path beyond it. Go at first light, if you go."
    }
   ],
   "repeat": [
    "Dale-ward closes at dusk. I will not open it at night. Not for you, not for anyone.",
    "The guild posted a notice about the breeder on the mountain path. Nobody has taken it.",
    "He did not look back when he went out. The boy did."
   ],
   "name": "Tamsin",
   "portrait": "hunter_portrait"
  }
 },
 "bosses": {
  "apalala": {
   "before": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* As Kael steps onto the weir, the still pool breaks. A long blue shape rises from the basin, scaled like deep water, and the falls part around it."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Apalala. The Dragon Overlord of South Earlsome. Its body coils across the rock stair, and water streams from it onto the stones."
    },
    {
     "speaker": "Apalala",
     "portrait": "none",
     "text": "This pass is mine. No one goes down to the dale without my leave. Turn back, or be taken by the water."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "Someone went down before me. With two children. I am following them, and I am not turning back."
    }
   ],
   "after_peace": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Apalala lowers its head to the water. The waves in the basin settle, and the pool grows still again."
    },
    {
     "speaker": "Apalala",
     "portrait": "none",
     "text": "You did not come for my blood. Few who reach this weir can say that. Go down, then."
    },
    {
     "speaker": "Apalala",
     "portrait": "none",
     "text": "The grey one crossed here with the little ones. I did not rise for him. There was nothing in him I could take that he had not already given away."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "What does that mean? What did he give away?"
    },
    {
     "speaker": "Apalala",
     "portrait": "none",
     "text": "...Not even you."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* It sinks into the pool without another word. The rock stair to Longdale lies open."
    }
   ],
   "after_won": [
    {
     "speaker": "",
     "portrait": "none",
     "text": "* Apalala sinks across the weir, beaten. The water it held drains back into the basin, and the falls pour down unbroken again."
    },
    {
     "speaker": "",
     "portrait": "none",
     "text": "* The red glow in the cliff shrine dims, but does not go out. Beyond the weir, the rock stair to Longdale lies open."
    },
    {
     "speaker": "Kael",
     "portrait": "hero_portrait",
     "text": "It let him pass. It fought me. Whatever he is, even the dragons treat him differently."
    }
   ]
  }
 },
 "unlock_lines": {
  "giant_mangal_f2": [
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "My sister's ribbon. I never showed it to you, Edda."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Not mine to tell, boy. Eat first."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* She sets a bowl in front of him and does not sit down. For a while, the only sound is the fire."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "The one at the shrine was my husband. Twenty years he rowed those oars to that hill."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Four years ago the boat came back across the river empty, with the oars shipped inside it."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "The boots in the hut were my grandson's. He went up to bring his grandfather home."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "So keep the oars. I want nothing of his back in this house."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "The lodge met this morning. They have cut the lashings on the Giant Mangal stair. You served Dundean, and the hunters pay their debts."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Before the bar went up, two of ours climbed after the barbarian. They have not come down. If you go up, look for them. Bring back what you find."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I will look. Whatever is up there."
   }
  ],
  "ringfeld_lower_road": [
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "Word came down from the coast. The keepers at Ringfeld have laid a plank path round the slide, past the fallen trunk at the Mangal crossroads."
   },
   {
    "speaker": "Old Edda",
    "portrait": "innkeeper_portrait",
    "text": "The lodge has marked the north road open. It is a narrow way, and the ravine is deep. Walk it in daylight."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Then I will see the coast. If anyone there saw him, I need to know."
   }
  ],
  "south_earlsome_valley": [
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "I had the pine hauled off the valley road this morning. Four of us and a team of oxen. The road to Longdale is open."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "You know who made that page."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "That is not mine to say."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The ring was Seren's. My wife. I cut it from my father's hunting horn, the one carved on his stone."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The small grave beside it is our daughter's. She went to Azurelake as a guild apprentice when she was six. A letter came back that said fever."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "There was never anything in it to bury. Seren dug it open, years ago, and found that out for herself."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "The first night of the fires, she walked down the south track barefoot, and I crossed her name off the board myself."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "I thanked you for my father's stone. I should have told you whose hand was on the grave beside it."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Listen to me. Between here and Longdale, the road climbs to a pass. A dragon guards it, in the pool below the falls. Do not think it will let you walk by."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "He walked by. With them. I will find a way."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Then go. Dun vael. Keep to the trail, and come back the same way you..."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "* He stops, and looks down the valley toward the graveyard."
   },
   {
    "speaker": "Brann",
    "portrait": "hunter_portrait",
    "text": "Dun vael."
   }
  ]
 },
 "map_text_addendum": "Three roads now lead on from the lands around Dundean. In the Norwoods, the stair of the Giant Mangal climbs to its second floor and to a Waypoint on the third, where the way up is torn out of the trunk. North of the Mangal crossroads, a plank path skirts the slide into Ringfeld, open coastal fields where the keepers' shelter stands. Its shore road ends at the causeway to the dark Lighthouse, which Archelon guards from the water. East of Dundean, the valley road climbs into South Earlsome. A dragon, Apalala, guards the pass between the valley and Longdale, the guild town of the dale. Longdale's north gate shuts at dusk, and the road beyond runs on toward North Earlsome. The map does not end here. It has only been drawn this far."
};

export const REGION_NPC_SHEETS: string[] = ["hunter", "innkeeper"];

export const REGION_SPAWN_PATCHES: { room: string; name: string; spawn: { at: [number, number]; dir: 'up' | 'down' | 'left' | 'right' } }[] = [{"room": "east_valley_road", "name": "fromSouthEarlsomeValley", "spawn": {"at": [1403, 279], "dir": "right"}}];
