// GENERATED by tools/gen_story.py — the four Dragon Island Blue starter hatchlings (wiki data).
import type { StarterData } from './storyTypes';

export const STARTERS: StarterData[] = [
 {
  "choice": "earth",
  "name": "Gold Hatchling",
  "id": "gold_hatchling",
  "number": "013",
  "element": "Earth",
  "stars": 2,
  "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/9/96/Gold_Hatchling.png/revision/latest?cb=20121208174934&format=original",
  "image_size": [
   112,
   140
  ],
  "sprite_description": "A young gold/ochre-scaled dragon sitting inside a cracked white eggshell, the upper shell still covering its head like a helmet; one red eye shows through a hole in the shell, dark grey beak-like snout, small dark horn, gold clawed feet and spiked tail poking out of the shell.",
  "lv1": {
   "hp": 33,
   "attack": 8,
   "magic": 8,
   "speed": 21,
   "defense": 13,
   "resist": 13
  },
  "abilities": [
   {
    "name": "Mother",
    "tu": "250",
    "target": "1 Foe",
    "effect": "16-19 Magical Damage (Earth). The wiki lists no other effect: it is the hatchling's heavy, slow (250 TU) magical attack, its only magic move."
   },
   {
    "name": "Tail",
    "tu": "70",
    "target": "1 Foe",
    "effect": "5-6 Physical Damage (Earth)"
   }
  ],
  "evolution": {
   "next_name": "Gold Dragonling",
   "next_number": "014",
   "at_level": 6,
   "next_image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/f/ff/Gold_Dragonling.png/revision/latest?cb=20121208175046&format=original",
   "next_abilities": [
    {
     "name": "Landslide",
     "tu": "130",
     "target": "1 Foe",
     "effect": "13-16 Magical Damage (Earth)"
    },
    {
     "name": "Outrage",
     "tu": "160",
     "target": "1 Foe",
     "effect": "16-19 Physical Damage (Earth)"
    },
    {
     "name": "Tail",
     "tu": "70",
     "target": "1 Foe",
     "effect": "8-9 Physical Damage (Earth)"
    }
   ],
   "chain": "Gold Hatchling (013) -> Gold Dragonling (014, lv 6) -> Gold Dragon (lv 30) -> Gold Wyrm (lv 55)"
  },
  "guild_blurb": "The gold one. Earth runs in its blood, and it is slow to anger but strikes from the ground itself when it does. Raise it past its sixth season and it will shed the shell for good.",
  "notes": "Number given as '13' in infobox; padded to 013 to match file 013_gold_hatchling.PNG. Gold Dragonling level-1 stats: HP35 Atk12 Mag12 Spd22 Def22 Res22, 3.5 stars. Evolution level conflict: Gold Hatchling page and Gold Dragonling 'How to Obtain' say level 6, but the Gold Dragonling page's evolution table says 'Evolves at level 8' -> used 6 (majority, the hatchling's own page). Hatchling page evolution table also has a stray 'level 56' under Gold Wyrm (ignored). Sprite verified visually (Gold_Hatchling.png, 112x140); the numbered file 013_gold_hatchling.PNG (203x250) is a larger alternative. CDN serves WebP unless '&format=original' is appended; URLs above include it and return real PNG. 'Mother' has no description on the wiki beyond its damage line."
 },
 {
  "choice": "wind",
  "name": "Spark Hatchling",
  "id": "spark_hatchling",
  "number": "009",
  "element": "Air",
  "stars": 2,
  "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/c/c3/Spark_Hatchling.png/revision/latest?cb=20121208174509&format=original",
  "image_size": [
   112,
   140
  ],
  "sprite_description": "A pale white/lavender-scaled young dragon in a cracked white eggshell worn over its head; one amber-brown eye peers through the shell, pale beak-like snout, small cream horn, pale clawed feet and spiked tail emerging from the shell.",
  "lv1": {
   "hp": 33,
   "attack": 8,
   "magic": 8,
   "speed": 21,
   "defense": 13,
   "resist": 13
  },
  "abilities": [
   {
    "name": "Mother",
    "tu": "250",
    "target": "One Foe",
    "effect": "16-19 Magical Damage (Air). No other effect listed: a slow (250 TU) magical strike, the hatchling's only magic move."
   },
   {
    "name": "Tail",
    "tu": "70",
    "target": "One Foe",
    "effect": "5-6 Physical Damage (Air)"
   }
  ],
  "evolution": {
   "next_name": "White Dragonling",
   "next_number": "010",
   "at_level": 6,
   "next_image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/3/3b/White_Dragonling.png/revision/latest?cb=20121208174653&format=original",
   "next_abilities": [
    {
     "name": "Outrage",
     "tu": "160",
     "target": "One Foe",
     "effect": "16-19 Physical Damage (Air) (row incomplete on wiki; target/effect inferred from the identical Outrage of the other three Dragonlings)"
    },
    {
     "name": "Sonic Blast",
     "tu": "130",
     "target": "One Foe",
     "effect": "13-16 Magical Damage (Air)"
    },
    {
     "name": "Tail",
     "tu": "70",
     "target": "One Foe",
     "effect": "8-9 Physical Damage (Air)"
    }
   ],
   "chain": "Spark Hatchling (009) -> White Dragonling (010, lv 6) -> White Dragon (lv 30) -> White Wyrm (lv 55)"
  },
  "guild_blurb": "The pale one. It carries the air in it, and it is quick, but quick does not mean strong. Keep it alive long enough and it grows into a White Dragonling.",
  "notes": "DIB element is Air (category Air, Element_Air.png); used for the 'wind' choice. Stats table mislabels the last row 'Magic' (13) - it is Resist (same layout as the other three). White Dragonling ability table: Outrage row only has TU 160, no target/effect - the parser may drop/mangle it; filled from the other Dragonlings' Outrage (16-19 Physical, One Foe) and flagged. White Dragonling lv1: HP35 Atk12 Mag12 Spd22 Def22 Res22, 3.5 stars. Evolution level conflict: Spark Hatchling page says level 6, White Dragonling page table says level 8 -> used 6. Sprite verified visually. CDN serves WebP without '&format=original'."
 },
 {
  "choice": "water",
  "name": "Water Hatchling",
  "id": "water_hatchling",
  "number": "005",
  "element": "Water",
  "stars": 2,
  "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/d/da/Water_Hatchling.png/revision/latest?cb=20121208173957&format=original",
  "image_size": [
   112,
   140
  ],
  "sprite_description": "A blue-scaled young dragon in a cracked white eggshell worn over its head; one pale blue eye through the shell, dark grey beak-like snout, small black horn, blue clawed feet and blue spiked tail poking out of the shell.",
  "lv1": {
   "hp": 33,
   "attack": 8,
   "magic": 8,
   "speed": 21,
   "defense": 13,
   "resist": 13
  },
  "abilities": [
   {
    "name": "Mother",
    "tu": "250",
    "target": "1 Foe",
    "effect": "16-19 Magical Damage (Water). No other effect listed: a slow (250 TU) magical strike, the hatchling's only magic move."
   },
   {
    "name": "Tail",
    "tu": "130",
    "target": "1 Foe",
    "effect": "5-6 Physical Damage (Water)"
   }
  ],
  "evolution": {
   "next_name": "Blue Dragonling",
   "next_number": "006",
   "at_level": 6,
   "next_image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/e/e3/Blue_Dragonling.png/revision/latest?cb=20121208174124&format=original",
   "next_abilities": [
    {
     "name": "Outrage",
     "tu": "160",
     "target": "1 Foe",
     "effect": "16-19 Physical Damage (Water)"
    },
    {
     "name": "Rapid Water",
     "tu": "130",
     "target": "1 Foe",
     "effect": "13-16 Magical Damage (Water)"
    },
    {
     "name": "Tail",
     "tu": "70",
     "target": "1 Foe",
     "effect": "8-9 Physical Damage (Water)"
    }
   ],
   "chain": "Water Hatchling (005) -> Blue Dragonling (006, lv 6) -> Blue Dragon (lv 30) -> Blue Wyrm (lv 55)"
  },
  "guild_blurb": "The blue one, of the water. Hatchlings like it are almost never seen in the wild. At its sixth season it becomes a Blue Dragonling.",
  "notes": "Number given as '5' (Blue Dragonling '6'); padded to 005/006 to match file 005_water_hatchling.png. Tail TU is 130 on this page vs 70 on the other three hatchlings and on Blue Dragonling's Tail - possibly a wiki typo; kept 130 as written (could normalise to 70). Wiki also says it can be found in Southern Alvalon at ~0.1% chance. Blue Dragonling lv1: HP35 Atk12 Mag12 Spd22 Def22 Res22, 3.5 stars; trivia: it is the dragon on the DIB logo. Evolution level 6 on both pages (consistent). Infobox image File:Water_Hatchling.png verified visually; WaterHatchling.png is a near-duplicate. CDN serves WebP without '&format=original'."
 },
 {
  "choice": "fire",
  "name": "Fire Hatchling",
  "id": "fire_hatchling",
  "number": "001",
  "element": "Fire",
  "stars": 2,
  "image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/5/56/Fire_Hatchling.png/revision/latest?cb=20121122002252&format=original",
  "image_size": [
   112,
   140
  ],
  "sprite_description": "A red-scaled young dragon in a cracked white eggshell worn over its head; one orange-brown eye through the shell, cream beak-like snout, small black horn, red clawed feet and a red spiked tail with a dark tip poking out of the shell.",
  "lv1": {
   "hp": 33,
   "attack": 8,
   "magic": 8,
   "speed": 21,
   "defense": 13,
   "resist": 13
  },
  "abilities": [
   {
    "name": "Mother",
    "tu": "250",
    "target": "One Foe",
    "effect": "16-19 Magical Damage (Fire). No other effect listed: a slow (250 TU) magical strike, the hatchling's only magic move."
   },
   {
    "name": "Tail",
    "tu": "70",
    "target": "One Foe",
    "effect": "5-6 Physical Damage (Fire)"
   }
  ],
  "evolution": {
   "next_name": "Red Dragonling",
   "next_number": "002",
   "at_level": 6,
   "next_image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/0/0a/Red_Dragonling.png/revision/latest?cb=20121122002605&format=original",
   "next_abilities": [
    {
     "name": "Flame",
     "tu": "130",
     "target": "One Foe",
     "effect": "13-19 Magical Damage (Fire)"
    },
    {
     "name": "Outrage",
     "tu": "160",
     "target": "One Foe",
     "effect": "16-19 Physical Damage (Fire)"
    },
    {
     "name": "Tail",
     "tu": "70",
     "target": "One Foe",
     "effect": "8-9 Physical Damage (Fire)"
    }
   ],
   "chain": "Fire Hatchling (001) -> Red Dragonling (002, lv 6) -> Red Dragon (lv 30) -> Red Wyrm (lv 55)"
  },
  "guild_blurb": "The red one. Fire, and it will not let you forget it. It is the first of the four in the guild's ledger. Raise it well and it becomes a Red Dragonling.",
  "notes": "Infobox image 'FireHatchling.png' does not exist on the wiki (missing sprite); the real file is Fire_Hatchling.png (from the evolution table), verified visually. 001_Fire_Hatchling.png (240x300) is a larger alternative. Evolution level conflict: Fire Hatchling page says level 6; Red Dragonling page says level 8 in both 'How to Obtain' and its table -> used 6 for consistency with the other three chains (could be 8). Red Dragonling lv1 differs slightly from the other Dragonlings: HP34 Atk12 Mag12 Spd22 Def21 Res21, 3.5 stars; Flame is 13-19 (others' magic move is 13-16). Red Dragonling can also appear wild in Ringfield forest at ~0.1%. CDN serves WebP without '&format=original'."
 }
];
