// GENERATED by tools/gen_story.py — the kidnapping storyline, key-item texts and village names.
import type { StoryData } from './storyTypes';

export const STORY: StoryData = {
 "names": {
  "sister": "Lira",
  "brother": "Tobin",
  "guild_master": "Master Halvard",
  "guild": "Azurelake Tamers' Guild",
  "kidnapper_epithet": "the Ashen Stranger"
 },
 "intro_pages": [
  {
   "bg": "bg_plaza",
   "tint": "",
   "text": "Azurelake was a quiet town. Lamps on the water, a guild hall on the plaza, and children who were told never to cross the west bridge after dark."
  },
  {
   "bg": "bg_plaza",
   "tint": "#b04030",
   "text": "On the night of the new moon, a stranger in grey ash walked into the town. No one saw him arrive. Everyone remembers the screaming."
  },
  {
   "bg": "bg_gate",
   "tint": "#b04030",
   "text": "Three Celestial Rank Hunters met him at the West Gate, the strongest the guild had. He went through all three of them. None stood up again before dawn."
  },
  {
   "bg": "bg_gate_talk",
   "tint": "",
   "text": "When the smoke cleared, two beds in a small house by the fountain were empty. Lira, nine years old. Tobin, seven."
  },
  {
   "bg": "bg_outskirts",
   "tint": "#5060a0",
   "text": "He crossed the bridge and left the town behind. A watchman saw him once more on the field road west, a child under each arm. Then the forest swallowed him."
  },
  {
   "bg": "bg_plaza",
   "tint": "",
   "text": "Their older brother Kael woke to the sound of bells. He has no dragon, no license, and no plan. He only knows which way the road goes."
  }
 ],
 "items": {
  "manual": {
   "title": "Tamer's Manual of the Azurelake Guild",
   "pages": [
    {
     "heading": "Time Units",
     "text": "Every action in battle costs Time Units, or TU. Quick strikes cost little and come around fast. Heavy techniques cost more and leave you open. Know the cost before you commit."
    },
    {
     "heading": "Your Hatchling",
     "text": "Every guild hatchling knows two techniques. Tail is a quick physical strike. Mother is a slow magical attack of 250 TU that hits far harder. Learn when each is worth the wait."
    },
    {
     "heading": "The Elements",
     "text": "Earth, Air, Water and Fire are the four the hatchlings carry. Out in the wild you will also meet creatures of Life, Death and Arcane. Learn what each element fears."
    },
    {
     "heading": "Training and Evolution",
     "text": "Creatures grow through battle. A hatchling that reaches level 6 becomes a Dragonling, at 30 a Dragon, at 55 a Wyrm. A hatchling driven too hard will not live to grow."
    },
    {
     "heading": "Sparring and Mercy",
     "text": "Not every creature must be destroyed. Use ACT to read, calm or reason with a foe. When it has no will left to fight, MERCY lets it go. The wild remembers tamers who spare."
    },
    {
     "heading": "Capture",
     "text": "Capture cards take a wild creature into your company. The more damaged it is, the higher the chance; a calmed creature yields more easily. A regular card rarely holds a creature at full strength. A Silver Card holds far better, and a Gold Card never fails. Cards can be bought even in the middle of a fight."
    },
    {
     "heading": "Candle Rest Points",
     "text": "Along the old roads, candles burn at rest points kept by travellers before you. Rest there to recover your strength and record your progress. Never pass one by without need."
    },
    {
     "heading": "A Last Word",
     "text": "Your dragon is not a weapon. It is a companion that has chosen to trust you. Earn that trust every day, and it will follow you anywhere. Even into the dark."
    }
   ]
  },
  "translation_guide": {
   "title": "Translation Guide to the Villages",
   "intro": "Collected by guild couriers over many years. The words below are local custom, not law. Use them with respect and you will find doors open more easily.",
   "villages": [
    {
     "village": "Dundean",
     "region": "Safaris",
     "phrases": [
      {
       "phrase": "Dun ar, open road.",
       "meaning": "Greeting to travellers coming in from the wild."
      },
      {
       "phrase": "The grass hears.",
       "meaning": "Speak quietly; there are beasts close by."
      },
      {
       "phrase": "Dun vael.",
       "meaning": "Farewell, keep to the trail."
      }
     ]
    },
    {
     "village": "Wesing",
     "region": "Greater Wesing",
     "phrases": [
      {
       "phrase": "Ves an hollo, wayfarer.",
       "meaning": "Peace on your road, traveller."
      },
      {
       "phrase": "Mind the deep stair.",
       "meaning": "Warning: do not wander toward the Igneous Passage."
      },
      {
       "phrase": "Hollo-vesk.",
       "meaning": "Farewell, return safely."
      }
     ]
    },
    {
     "village": "Saint Wesburn",
     "region": "Wesburn",
     "phrases": [
      {
       "phrase": "Light on your threshold.",
       "meaning": "Formal greeting at any door in the city."
      },
      {
       "phrase": "Not below the holy stair.",
       "meaning": "Warning: do not enter the Holy Cave without leave."
      }
     ]
    },
    {
     "village": "Longdale",
     "region": "South Earlsome",
     "phrases": [
      {
       "phrase": "Long day, short road.",
       "meaning": "Welcome; rest here before you go on."
      },
      {
       "phrase": "Dale-ward closes at dusk.",
       "meaning": "The gates are shut after sundown."
      }
     ]
    },
    {
     "village": "Olympia",
     "region": "Reached by the road through Endergate",
     "phrases": [
      {
       "phrase": "Olym sath, thel-varo.",
       "meaning": "I come in good faith, keeper of the gate."
      },
      {
       "phrase": "Thel-varo sath.",
       "meaning": "The keeper accepts you."
      },
      {
       "phrase": "Sath nem.",
       "meaning": "No faith; leave now."
      }
     ]
    },
    {
     "village": "Corova",
     "region": "Southern Alvalon",
     "phrases": [
      {
       "phrase": "Corra, sea-kin.",
       "meaning": "Greetings, friend of the coast."
      },
      {
       "phrase": "Tide brings, tide takes.",
       "meaning": "Do not linger by the shore at night."
      }
     ]
    },
    {
     "village": "Lorensia",
     "region": "Western Gracia",
     "phrases": [
      {
       "phrase": "Lor en'sei.",
       "meaning": "Good day to you."
      },
      {
       "phrase": "Sei mor, sei vel.",
       "meaning": "Speak plainly and you are welcome."
      },
      {
       "phrase": "Vel nae.",
       "meaning": "You are not welcome here."
      }
     ]
    },
    {
     "village": "Westguard",
     "region": "Northern Alvalon",
     "phrases": [
      {
       "phrase": "Shield up, stranger.",
       "meaning": "State your business at the gate."
      },
      {
       "phrase": "Licensed and listed.",
       "meaning": "I am a registered tamer."
      },
      {
       "phrase": "Ward holds.",
       "meaning": "Safe passage granted."
      }
     ]
    }
   ]
  },
  "map": {
   "title": "Map of the Nearest Villages",
   "text": "Drawn by the Azurelake Guild. The road leaves by the West Gate, crosses the field road and enters the Norwoods at the sun-carved waystones. The Stranger was last seen here.",
   "nearest": [
    {
     "name": "Norwoods",
     "direction": "West",
     "note": "The forest road, the mosswood and the great Waystone fork all lie within it. Domain of the Overlord Orochi. The dungeon Giant Mangal is here."
    },
    {
     "name": "Dundean",
     "direction": "West, past the Norwoods, in the Safaris",
     "note": "The nearest town beyond the forest. Open wild country all around it. Ask here first."
    },
    {
     "name": "Forest of Mangal",
     "direction": "Northwest, past the Norwoods",
     "note": "Wide woodland bordering the Norwoods and the Safaris. Its roads lead on to Ringfeld."
    },
    {
     "name": "Ringfeld",
     "direction": "Northwest, past the Forest of Mangal",
     "note": "Coastal fields and the old Lighthouse. No town, but travellers shelter there. Ask the keepers for news."
    },
    {
     "name": "Wesing",
     "direction": "Far road, in Greater Wesing",
     "note": "A large city. The guild keeps a courier there. Send word home from Wesing."
    },
    {
     "name": "Westguard",
     "direction": "Far north, in Northern Alvalon",
     "note": "A guarded city. Its gate is tested before any tamer may enter. Licensed hunters can be found there."
    }
   ],
   "world_map_image_url": "https://static.wikia.nocookie.net/dragonislandblue/images/7/71/1920px-00WorldMap.png/revision/latest?cb=20121207044928"
  }
 },
 "scenes": {
  "wake_aftermath": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The bells have stopped. The smell of smoke hangs over the plaza. Somewhere, a woman is crying."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Lira... Tobin... Their blankets were still warm. He took them right out of the house."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "They said he went west. Through the gate, over the bridge, down the forest road."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Kael tightens the strap of his cloak. His hands will not stop shaking."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Every hour I stand here, he gets further away. I am going after him."
   }
  ],
  "guildmaster_stops_you": [
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "Kael. Stop. Where do you think you are going?"
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "West. After him."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "I carried three Celestial Rank Hunters off that bridge tonight. Hunters who have stood before Dragon Overlords. He broke them like kindling."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "You have no dragon. You have never fought a wild creature in your life. Walking out that gate is not courage, boy. It is suicide."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "The guild will send word to Westguard. Licensed hunters will come. Go home and wait."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "There is no one at home to wait with.",
    "choices": [
     "I'm going.",
     "Then I go alone."
    ]
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "By the time anyone comes from Westguard, they will be gone. I will not wait for that. You cannot stop me."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "The old man looks at him for a long time. Then at the gate. Then at the blood still drying on the stones."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "...Your father said those same words to me once. I could not stop him either."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "If you are going to die out there, you will not do it empty-handed. Come to the Guild Hall. Now."
   }
  ],
  "guild_hall_choice_intro": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The Guild Hall is cold. Its lamps are low. Four hatchlings rest in straw beneath the guild's old banner, their broken shells still beside them."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "These hatched last week. They were meant for this spring's apprentices. They have never seen a fight."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "A Gold Hatchling of earth. A Spark Hatchling of wind. A Water Hatchling. A Fire Hatchling. One of each, and you may take one."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "They are weak now. Train one to level six and it becomes a Dragonling. If you both live long enough."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "Choose carefully. Whichever you take will follow you into that forest. Its life is in your hands as much as your own."
   }
  ],
  "after_choice": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The {HATCHLING} lifts its head and looks at Kael. Then it climbs, slowly, into his arms."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "{ELEMENT}, then. It chose you back. That is not always the case."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I will keep it safe. I promise."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "Keep each other safe. Out there, that is the only promise that means anything."
   }
  ],
  "items_handover": [
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "Three more things. Take them, and read them before you sleep."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Kael received the Tamer's Manual."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "The guild manual. Training, fighting, capture. Everything an apprentice is meant to learn in a year. You have one night."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Kael received the Translation Guide."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "Every village past the forest speaks its own way. A wrong word at the wrong gate can get you turned away. Or worse."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Kael received the Map of the Nearest Villages."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "The road west runs into the Norwoods. Past them lie the Safaris and the town of Dundean. Ask there first."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "Ask at every village if they saw a man in grey ash with two children. Someone always sees."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "And Kael. If you find him, do not fight him. Find where he takes them. Then send word. Promise me that much."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "...I will send word."
   },
   {
    "speaker": "Master Halvard",
    "portrait": "guildmaster_portrait",
    "text": "Go, then. The West Gate is open. May the old lights keep you."
   }
  ],
  "wren_first": [
   {
    "speaker": "Wren",
    "portrait": "wren_portrait",
    "text": "Kael. I heard. I am so sorry."
   },
   {
    "speaker": "Wren",
    "portrait": "wren_portrait",
    "text": "Lira used to follow me on my rounds. She wanted to light the lamp by the fountain herself. I always let her."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I am going after them, Wren."
   },
   {
    "speaker": "Wren",
    "portrait": "wren_portrait",
    "text": "I know. I could see it on you from across the plaza."
   },
   {
    "speaker": "Wren",
    "portrait": "wren_portrait",
    "text": "I will keep their lamp lit. Every night, until you bring them home. So they can find their way back."
   }
  ],
  "wren_hint_1": [
   {
    "speaker": "Wren",
    "portrait": "wren_portrait",
    "text": "The lamps by the West Gate went out when he passed. All of them, at once. Whatever he is, light does not like him."
   }
  ],
  "wren_hint_2": [
   {
    "speaker": "Wren",
    "portrait": "wren_portrait",
    "text": "The candles at the old rest points still burn along the road. Stop at them. Rest. You will not help them if you collapse."
   }
  ],
  "wren_hint_3": [
   {
    "speaker": "Wren",
    "portrait": "wren_portrait",
    "text": "Travellers say the great Waystone at the fork has gone dark. It has never been dark in my lifetime. Be careful there, Kael."
   }
  ],
  "gate_guard_or_sign": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The West Gate stands open. Its timbers are scorched black, and deep claw marks run across the stone."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "A notice has been nailed to the post: BY ORDER OF THE GUILD. ROAD WEST CLOSED. NO CIVILIAN PASSAGE."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Below it, a guard has scrawled in charcoal: He went this way. Gods help whoever follows."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Hold on, Lira. Tobin. I am coming."
   }
  ],
  "lich_encounter": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The moss here is dead and grey, as if something burning walked over it. A cold figure rises from the roots."
   },
   {
    "speaker": "Lich",
    "portrait": "none",
    "text": "Turn back, child of the lake. The one you follow walked this path an hour before the dawn."
   },
   {
    "speaker": "Lich",
    "portrait": "none",
    "text": "He spoke a name the forest had not heard in a hundred years. The dead woke to listen. I woke."
   },
   {
    "speaker": "Lich",
    "portrait": "none",
    "text": "Turn back. What waits at the Waystone is not meant for you."
   }
  ],
  "after_lich_peace": [
   {
    "speaker": "Lich",
    "portrait": "none",
    "text": "You did not strike me. Strange. The living rarely spare what they fear."
   },
   {
    "speaker": "Lich",
    "portrait": "none",
    "text": "The children were alive when he passed. The small one was crying. The girl was not. She was watching the road."
   },
   {
    "speaker": "Lich",
    "portrait": "none",
    "text": "He stopped at the Waystone and laid his hand on it. Go if you must. But you were warned."
   }
  ],
  "after_lich_won": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The Lich crumbles into the moss. Its last whisper drifts along the trail."
   },
   {
    "speaker": "Lich",
    "portrait": "none",
    "text": "...You will not stop him. He has already woken it..."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Woken what?"
   }
  ],
  "orochi_awakens": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The great Waystone is cold and black. A handprint of grey ash has been burned into its face."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "The ground shifts. Beneath the fork, something vast is uncoiling. One serpent head rises from the dark. Then another. Then eight."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "He did this. He woke it, so no one could follow him."
   },
   {
    "speaker": "Orochi",
    "portrait": "none",
    "text": "Who walks the roots of the Norwoods... The grey one promised me the first to follow. A boy. How small."
   },
   {
    "speaker": "Orochi",
    "portrait": "none",
    "text": "I am Orochi, Overlord of the Norwoods. Turn your back, and I will take you quickly."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I am not turning back. Not for him. Not for you."
   }
  ],
  "ending_peace_divine": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "Orochi lowers its eight heads. The ash fades from the Waystone, and its old carvings glow again, faint and gold."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "A pale light descends through the trees. A celestial form, calm and silent, hovers above the fork."
   },
   {
    "speaker": "Divine",
    "portrait": "mon_divine",
    "text": "You showed mercy where you had every reason to show none. That is rarer than strength."
   },
   {
    "speaker": "Divine",
    "portrait": "mon_divine",
    "text": "The one you hunt is no ordinary tamer. He did not break the Overlord's sleep with force. He bargained with it."
   },
   {
    "speaker": "Divine",
    "portrait": "mon_divine",
    "text": "Your sister and brother live. He carries them northwest, toward the Forest of Mangal and the roads beyond."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "At the foot of the Waystone lies a small blue ribbon. Lira's. Tied in a careful knot, like a signal."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "She left this for me. She knew I would come."
   },
   {
    "speaker": "Divine",
    "portrait": "mon_divine",
    "text": "Then do not keep her waiting. The road is long, and he does not rest."
   }
  ],
  "ending_cold": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "Orochi falls, and the forest goes silent. The Waystone stays dark."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "In the ash at its foot lies a small blue ribbon. Lira's. Tied in a careful knot, pointing down the northwest road."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "She left this for me. She is still alive. They both are."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "Far ahead, past the trees, a single line of grey smoke rises and drifts away to the northwest."
   },
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "I am coming. However far you take them."
   }
  ],
  "ending_card_peace": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The Waystone burns gold behind him. Kael walks on, the ribbon tied around his wrist, toward the Forest of Mangal."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "The hunt for the Ashen Stranger has only begun. To be continued."
   }
  ],
  "ending_card_cold": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The dark Waystone watches him go. Kael walks on alone, the ribbon tied around his wrist, toward the Forest of Mangal."
   },
   {
    "speaker": "",
    "portrait": "none",
    "text": "The hunt for the Ashen Stranger has only begun. To be continued."
   }
  ],
  "gameover_line": [
   {
    "speaker": "",
    "portrait": "none",
    "text": "The road grows dark. Somewhere far ahead, two children are still waiting. Get up, Kael."
   }
  ],
  "locked_gate_before_starter": [
   {
    "speaker": "Kael",
    "portrait": "hero_portrait",
    "text": "Halvard was right about one thing. Without a dragon, I would not last a night out there. The Guild Hall first."
   }
  ]
 }
};
